// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"testing"

	"github.com/mark3labs/mcp-go/server"
	"github.com/spf13/cobra"
)

func TestRegisterAllExposesNestedDocsSearchAndSkipsTopLevelSearch(t *testing.T) {
	root := &cobra.Command{Use: "test-cli"}
	topLevelSearch := &cobra.Command{Use: "search", Run: func(*cobra.Command, []string) {}}
	docs := &cobra.Command{Use: "docs"}
	docsSearch := &cobra.Command{Use: "search <query>", Run: func(*cobra.Command, []string) {}}
	docs.AddCommand(docsSearch)
	root.AddCommand(topLevelSearch, docs)

	if got := classify(topLevelSearch); got != commandFramework {
		t.Fatalf("top-level search classified as %v, want commandFramework", got)
	}
	if got := classify(docsSearch); got != commandNovel {
		t.Fatalf("nested docs search classified as %v, want commandNovel", got)
	}

	mcpServer := server.NewMCPServer("test", "0.0.0")
	RegisterAll(mcpServer, root, func() (string, error) { return "/bin/echo", nil })
	tools := mcpServer.ListTools()

	if _, ok := tools["search"]; ok {
		t.Fatalf("top-level search should stay covered by the typed MCP search tool, got shell-out tool")
	}
	if _, ok := tools["docs_search"]; !ok {
		t.Fatalf("docs_search shell-out tool was not registered; tools = %#v", tools)
	}
}
