// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsListCmd(flags *rootFlags) *cobra.Command {
	var flagPageNumber int
	var flagPageSize int
	var flagSortBy string
	var flagSortOrder string
	var flagSearchText string
	var flagStatus string
	var flagType string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Returns a list of accounts associated with your Straddle platform integration. The accounts are returned sorted by...",
		Example:     "  straddle-pp-cli accounts list",
		Annotations: map[string]string{"pp:endpoint": "accounts.list", "pp:method": "GET", "pp:path": "/v1/accounts", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort-order") {
				allowedSortOrder := []string{"asc", "desc"}
				validSortOrder := false
				for _, v := range allowedSortOrder {
					if flagSortOrder == v {
						validSortOrder = true
						break
					}
				}
				if !validSortOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-order", flagSortOrder, allowedSortOrder)
				}
			}
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"created", "onboarding", "active", "rejected", "inactive"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			if cmd.Flags().Changed("type") {
				allowedType := []string{"business"}
				validType := false
				for _, v := range allowedType {
					if flagType == v {
						validType = true
						break
					}
				}
				if !validType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "type", flagType, allowedType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/accounts"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "accounts", path, map[string]string{
				"page_number": fmt.Sprintf("%v", flagPageNumber),
				"page_size":   fmt.Sprintf("%v", flagPageSize),
				"sort_by":     fmt.Sprintf("%v", flagSortBy),
				"sort_order":  fmt.Sprintf("%v", flagSortOrder),
				"search_text": fmt.Sprintf("%v", flagSearchText),
				"status":      fmt.Sprintf("%v", flagStatus),
				"type":        fmt.Sprintf("%v", flagType),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number. Starts at page 1. Default value: 1")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "Page size. Default value: 100. Max value: 1000")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "id", "Sort By. Default value: 'id'.")
	cmd.Flags().StringVar(&flagSortOrder, "sort-order", "asc", "Sort Order. Default value: 'asc'. (one of: asc, desc)")
	cmd.Flags().StringVar(&flagSearchText, "search-text", "", "Search text")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Status (one of: created, onboarding, active, rejected, inactive)")
	cmd.Flags().StringVar(&flagType, "type", "", "Type (one of: business)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
