// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsCapabilityRequestsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "capability-requests",
		Short: "Capabilities enable specific features and services for an Account. Use capability requests to unlock higher...",
	}

	cmd.AddCommand(newAccountsCapabilityRequestsCreateCmd(flags))
	cmd.AddCommand(newAccountsCapabilityRequestsListCmd(flags))
	return cmd
}
