// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"testing"
)

func TestAgentContextAgentUsesTargetEnvelope(t *testing.T) {
	cmd := RootCmd()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)
	cmd.SetArgs([]string{"agent-context", "--agent"})

	if err := cmd.Execute(); err != nil {
		t.Fatalf("agent-context --agent returned error: %v", err)
	}
	if stderr.String() != "" {
		t.Fatalf("agent-context --agent wrote stderr: %q", stderr.String())
	}

	var got struct {
		SchemaVersion string          `json:"schema_version"`
		Data          json.RawMessage `json:"data"`
		Results       json.RawMessage `json:"results"`
		Meta          json.RawMessage `json:"meta"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &got); err != nil {
		t.Fatalf("agent-context --agent emitted invalid JSON: %v\n%s", err, stdout.String())
	}

	if got.SchemaVersion != "1.0" {
		t.Fatalf("schema_version: want 1.0, got %q", got.SchemaVersion)
	}
	if len(got.Data) == 0 {
		t.Fatalf("data should contain the agent context object")
	}
	if got.Results != nil {
		t.Fatalf("target envelope should not include results: %s", string(got.Results))
	}
	if got.Meta != nil {
		t.Fatalf("target envelope should not include meta: %s", string(got.Meta))
	}

	var data struct {
		SchemaVersion string `json:"schema_version"`
		CLI           struct {
			Name string `json:"name"`
		} `json:"cli"`
		Commands []agentContextCommand `json:"commands"`
	}
	if err := json.Unmarshal(got.Data, &data); err != nil {
		t.Fatalf("data should be the agent context object: %v\n%s", err, string(got.Data))
	}
	if data.SchemaVersion != agentContextSchemaVersion {
		t.Fatalf("data schema_version: want %s, got %q", agentContextSchemaVersion, data.SchemaVersion)
	}
	if data.CLI.Name != "straddle-pp-cli" {
		t.Fatalf("data cli.name: want straddle-pp-cli, got %q", data.CLI.Name)
	}
	if len(data.Commands) == 0 {
		t.Fatalf("data commands should be populated")
	}
}
