// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"straddle-pp-cli/internal/config"
)

func runCLIForAuthTest(t *testing.T, stdin string, args ...string) (string, string, error) {
	t.Helper()

	cmd := RootCmd()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)
	cmd.SetIn(strings.NewReader(stdin))
	cmd.SetArgs(args)

	err := cmd.Execute()
	return stdout.String(), stderr.String(), err
}

func assertCLIAuthReadinessGuidance(t *testing.T, text string) {
	t.Helper()

	unsafe := []string{
		"export STRADDLE_TOKEN=<your-key>",
		"export STRADDLE_TOKEN=<your-token>",
		strings.Join([]string{"straddle-pp-cli auth set-token", "<token>"}, " "),
	}
	for _, wantAbsent := range unsafe {
		if strings.Contains(text, wantAbsent) {
			t.Fatalf("auth guidance should not include %q in %q", wantAbsent, text)
		}
	}
	required := []string{
		"straddle-pp-cli setup check --json",
		"straddle-pp-cli auth set-token --stdin",
		"secret manager",
		"Optional live sandbox reachability",
		"explicit sandbox base URL and credentials",
		"straddle-pp-cli doctor --json",
	}
	for _, want := range required {
		if !strings.Contains(text, want) {
			t.Fatalf("auth guidance missing %q in %q", want, text)
		}
	}
}

func TestAuthSetTokenReadsTokenFromStdin(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "")
	configPath := filepath.Join(t.TempDir(), "config.toml")
	token := "stdin-token-secret"

	stdout, stderr, err := runCLIForAuthTest(t, token+"\n", "auth", "set-token", "--stdin", "--config", configPath)
	if err != nil {
		t.Fatalf("auth set-token --stdin returned error: %v", err)
	}
	if strings.Contains(stdout, token) || strings.Contains(stderr, token) {
		t.Fatalf("command output leaked token")
	}

	cfg, err := config.Load(configPath)
	if err != nil {
		t.Fatalf("load saved config: %v", err)
	}
	if got := cfg.AuthHeader(); got != "Bearer "+token {
		t.Fatalf("saved auth header did not use stdin token")
	}
}

func TestAuthSetTokenStdinDoesNotPersistEnvToken(t *testing.T) {
	configPath := filepath.Join(t.TempDir(), "config.toml")
	envToken := "env-token-secret"
	stdinToken := "stdin-token-secret"
	t.Setenv("STRADDLE_TOKEN", envToken)

	stdout, stderr, err := runCLIForAuthTest(t, stdinToken+"\n", "auth", "set-token", "--stdin", "--config", configPath)
	if err != nil {
		t.Fatalf("auth set-token --stdin returned error: %v", err)
	}
	output := stdout + stderr
	if strings.Contains(output, envToken) || strings.Contains(output, stdinToken) {
		t.Fatalf("command output leaked token")
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("read saved config: %v", err)
	}
	if strings.Contains(string(data), envToken) {
		t.Fatalf("saved config persisted env token")
	}

	t.Setenv("STRADDLE_TOKEN", "")
	cfg, err := config.Load(configPath)
	if err != nil {
		t.Fatalf("load saved config: %v", err)
	}
	if got := cfg.AuthHeader(); got != "Bearer "+stdinToken {
		t.Fatalf("saved auth header did not use stdin token")
	}
}

func TestAuthSetTokenRejectsEmptyStdinWithoutLeakingTokenText(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "")
	configPath := filepath.Join(t.TempDir(), "config.toml")

	stdout, stderr, err := runCLIForAuthTest(t, " \n\t", "auth", "set-token", "--stdin", "--config", configPath)
	if err == nil {
		t.Fatalf("expected empty stdin to fail")
	}
	output := stdout + stderr + err.Error()
	if strings.Contains(output, " \n\t") {
		t.Fatalf("empty stdin error included raw input")
	}
	if !strings.Contains(output, "stdin") {
		t.Fatalf("empty stdin error should mention stdin, got %q", output)
	}
}

func TestAuthHelpAndStatusPreferStdinGuidance(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "")
	configPath := filepath.Join(t.TempDir(), "missing.toml")
	token := "guidance-token-secret"

	helpOut, helpErr, err := runCLIForAuthTest(t, token, "auth", "set-token", "--help")
	if err != nil {
		t.Fatalf("auth set-token --help returned error: %v", err)
	}
	helpText := helpOut + helpErr
	if !strings.Contains(helpText, "--stdin") {
		t.Fatalf("help should mention --stdin, got %q", helpText)
	}
	if strings.Contains(helpText, "[token]") || strings.Contains(helpText, "argv") || strings.Contains(helpText, "positional") {
		t.Fatalf("help should not present token arguments as an active path, got %q", helpText)
	}
	if strings.Contains(helpText, token) {
		t.Fatalf("help output leaked token text")
	}

	statusOut, statusErr, err := runCLIForAuthTest(t, "", "auth", "status", "--config", configPath)
	if err == nil {
		t.Fatalf("expected unauthenticated status to fail")
	}
	statusText := statusOut + statusErr + err.Error()
	if !strings.Contains(statusText, "straddle-pp-cli setup check --json") {
		t.Fatalf("status guidance should route to setup check first, got %q", statusText)
	}
	if !strings.Contains(statusText, "auth set-token --stdin") {
		t.Fatalf("status guidance should prefer --stdin, got %q", statusText)
	}
	if !strings.Contains(statusText, "secret manager") {
		t.Fatalf("status guidance should mention secret manager env injection, got %q", statusText)
	}
	if !strings.Contains(statusText, "Optional live sandbox reachability") ||
		!strings.Contains(statusText, "explicit sandbox base URL and credentials") ||
		!strings.Contains(statusText, "straddle-pp-cli doctor --json") {
		t.Fatalf("status guidance should sandbox-qualify optional doctor, got %q", statusText)
	}
	if strings.Contains(statusText, "set-token <"+"token"+">") {
		t.Fatalf("status guidance should not recommend argv token form, got %q", statusText)
	}
	if strings.Contains(statusText, token) {
		t.Fatalf("status output leaked token text")
	}
}

func TestAuthStatusJSONUnauthenticatedRoutesThroughSetupCheck(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "")
	configPath := filepath.Join(t.TempDir(), "missing.toml")

	stdout, stderr, err := runCLIForAuthTest(t, "", "auth", "status", "--json", "--config", configPath)
	if err == nil {
		t.Fatalf("expected unauthenticated status JSON to fail")
	}
	statusText := stdout + stderr + err.Error()
	assertCLIAuthReadinessGuidance(t, statusText)
}
