// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newBridgeCreateSpeedchexCmd(flags *rootFlags) *cobra.Command {
	var bodyConfig string
	var bodyCustomerId string
	var bodyExternalId string
	var bodyMetadata string
	var bodySpeedchexToken string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-speedchex",
		Short:       "Creates a new paykey using a Speedchex token as the source. This endpoint allows you to create a secure payment...",
		Example:     "  straddle-pp-cli bridge create-speedchex --customer-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "bridge.create-speedchex", "pp:method": "POST", "pp:path": "/v1/bridge/speedchex"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("customer-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "customer-id")
				}
				if !cmd.Flags().Changed("speedchex-token") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "speedchex-token")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/bridge/speedchex"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyConfig != "" {
					var parsedConfig any
					if err := json.Unmarshal([]byte(bodyConfig), &parsedConfig); err != nil {
						return fmt.Errorf("parsing --config JSON: %w", err)
					}
					body["config"] = parsedConfig
				}
				if bodyCustomerId != "" {
					body["customer_id"] = bodyCustomerId
				}
				if bodyExternalId != "" {
					body["external_id"] = bodyExternalId
				}
				if bodyMetadata != "" {
					var parsedMetadata any
					if err := json.Unmarshal([]byte(bodyMetadata), &parsedMetadata); err != nil {
						return fmt.Errorf("parsing --metadata JSON: %w", err)
					}
					body["metadata"] = parsedMetadata
				}
				if bodySpeedchexToken != "" {
					body["speedchex_token"] = bodySpeedchexToken
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "bridge",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyConfig, "config", "", "Config")
	cmd.Flags().StringVar(&bodyCustomerId, "customer-id", "", "Unique identifier of the related customer object.")
	cmd.Flags().StringVar(&bodyExternalId, "external-id", "", "Unique identifier for the paykey in your database, used for cross-referencing between Straddle and your systems.")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Up to 20 additional user-defined key-value pairs. Useful for storing additional information about the paykey in a...")
	cmd.Flags().StringVar(&bodySpeedchexToken, "speedchex-token", "", "Speedchex token generated by your application for use with the Straddle API.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
