// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCH: workflow-plan adds local-only structured workflow plans without live execution.

package cli

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"straddle-pp-cli/internal/store"
)

type workflowPlanSafety struct {
	GuidanceOnly                 bool `json:"guidance_only"`
	LocalOnly                    bool `json:"local_only"`
	NoAPICalls                   bool `json:"no_api_calls"`
	NoDocsEndpointCalls          bool `json:"no_docs_endpoint_calls"`
	NoMCPExecution               bool `json:"no_mcp_execution"`
	NoWebhookPosts               bool `json:"no_webhook_posts"`
	NoSandbox                    bool `json:"no_sandbox"`
	NoProduction                 bool `json:"no_production"`
	NoCredentialsRead            bool `json:"no_credentials_read"`
	NoTokenLiterals              bool `json:"no_token_literals"`
	NoWrites                     bool `json:"no_writes"`
	DoesNotApproveLiveExecution  bool `json:"does_not_approve_live_execution"`
	RequiresFreshDocsLookup      bool `json:"requires_fresh_docs_lookup"`
	RequiresExplicitApproval     bool `json:"requires_explicit_approval"`
	RequiresReadOnlyCommandScope bool `json:"requires_read_only_command_scope"`
}

type workflowPlanStep struct {
	Name        string   `json:"name"`
	Commands    []string `json:"commands,omitempty"`
	Checks      []string `json:"checks,omitempty"`
	Notes       []string `json:"notes,omitempty"`
	StopIf      []string `json:"stop_if,omitempty"`
	ApprovalFor string   `json:"approval_for,omitempty"`
}

type workflowPlanPhase struct {
	Name  string             `json:"name"`
	Goal  string             `json:"goal"`
	Steps []workflowPlanStep `json:"steps"`
}

type workflowPlanWorkflow struct {
	Name                                 string              `json:"name"`
	Title                                string              `json:"title"`
	Summary                              string              `json:"summary"`
	Phases                               []workflowPlanPhase `json:"phases"`
	DocsSearchTopics                     []string            `json:"docs_search_topics"`
	ReadOnlyCLICommands                  []string            `json:"read_only_cli_commands"`
	DryRunCommands                       []string            `json:"dry_run_commands,omitempty"`
	BlockedWriteActions                  []string            `json:"blocked_write_actions"`
	RequiredApprovalsBeforeLiveExecution []string            `json:"required_approvals_before_live_execution"`
}

type workflowPlanResponse struct {
	Command            string                 `json:"command"`
	Workflow           string                 `json:"workflow,omitempty"`
	AvailableWorkflows []string               `json:"available_workflows,omitempty"`
	WorkflowPlan       *workflowPlanWorkflow  `json:"workflow_plan,omitempty"`
	WorkflowPlans      []workflowPlanWorkflow `json:"workflow_plans,omitempty"`
	Safety             workflowPlanSafety     `json:"safety"`
	RunbookPurpose     string                 `json:"runbook_purpose"`
	BlockedByDefault   []string               `json:"blocked_by_default"`
}

func newWorkflowCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "workflow",
		Short: "Compound workflows that combine multiple API operations",
	}

	cmd.AddCommand(newWorkflowArchiveCmd(flags))
	cmd.AddCommand(newWorkflowPlanCmd(flags))
	cmd.AddCommand(newWorkflowStatusCmd(flags))

	return cmd
}

func newWorkflowPlanCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "plan [workflow]",
		Short: "Generate a local-only structured workflow plan",
		Long: `Generate a local-only structured workflow plan.

This command prints command plans for reconciliation, fraud monitoring, collections, reporting, and monitoring. It does not call Straddle APIs, docs endpoints, MCP tools, webhooks, sandbox, production, credentials, or write paths.`,
		Example: `  straddle-pp-cli workflow plan
  straddle-pp-cli workflow plan reconciliation --json
  straddle-pp-cli workflow plan all --json
  straddle-pp-cli workflow plan monitoring --agent`,
		Annotations: map[string]string{
			"mcp:read-only":              "true",
			localOnlyNoPreloadAnnotation: "true",
		},
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if flags.deliverSpec != "" {
				return usageErr(fmt.Errorf("workflow plan does not support --deliver; use normal stdout, JSON, or agent output"))
			}

			workflow := ""
			if len(args) == 1 {
				workflow = strings.ToLower(strings.TrimSpace(args[0]))
			}
			payload, err := buildWorkflowPlanResponse(workflow)
			if err != nil {
				return usageErr(err)
			}
			return renderWorkflowPlanResponse(cmd, flags, payload)
		},
	}
	return cmd
}

func buildWorkflowPlanResponse(workflow string) (workflowPlanResponse, error) {
	payload := workflowPlanResponse{
		Command:            "workflow plan",
		AvailableWorkflows: workflowPlanNamesWithAll(),
		Safety: workflowPlanSafety{
			GuidanceOnly:                 true,
			LocalOnly:                    true,
			NoAPICalls:                   true,
			NoDocsEndpointCalls:          true,
			NoMCPExecution:               true,
			NoWebhookPosts:               true,
			NoSandbox:                    true,
			NoProduction:                 true,
			NoCredentialsRead:            true,
			NoTokenLiterals:              true,
			NoWrites:                     true,
			DoesNotApproveLiveExecution:  true,
			RequiresFreshDocsLookup:      true,
			RequiresExplicitApproval:     true,
			RequiresReadOnlyCommandScope: true,
		},
		RunbookPurpose: "Reduce the richer workflow behavior gap by turning operational guidance into structured, agent-useful command plans. This command only prints the plan.",
		BlockedByDefault: []string{
			"Live API reads or writes",
			"Docs endpoint calls",
			"MCP tool execution",
			"Webhook posts",
			"Sandbox or production execution",
			"Credential or token inspection",
			"Any write action without separate explicit approval",
		},
	}
	if workflow == "" {
		return payload, nil
	}
	if workflow == "all" {
		payload.Workflow = workflow
		payload.WorkflowPlans = workflowPlans()
		return payload, nil
	}
	plan, ok := workflowPlanByName(workflow)
	if !ok {
		return payload, fmt.Errorf("invalid workflow %q: supported workflows are %s", workflow, strings.Join(workflowPlanNamesWithAll(), ", "))
	}
	payload.Workflow = plan.Name
	payload.WorkflowPlan = &plan
	return payload, nil
}

func renderWorkflowPlanResponse(cmd *cobra.Command, flags *rootFlags, payload workflowPlanResponse) error {
	asJSON := flags.asJSON || flags.agent || !isTerminal(cmd.OutOrStdout())
	if asJSON {
		return printJSONFiltered(cmd.OutOrStdout(), payload, flags)
	}

	w := cmd.OutOrStdout()
	if payload.Workflow == "" {
		fmt.Fprintln(w, "Workflow plan")
		fmt.Fprintln(w, "Safety: local guidance only. No API calls, docs calls, MCP execution, webhooks, credentials, sandbox, production, or writes.")
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Workflows:")
		for _, workflow := range payload.AvailableWorkflows {
			fmt.Fprintf(w, "  %s\n", workflow)
		}
		return nil
	}
	if payload.Workflow == "all" {
		fmt.Fprintln(w, "Workflow plan: all")
		fmt.Fprintln(w, "Safety: local guidance only. Live execution still needs explicit approval.")
		for _, plan := range payload.WorkflowPlans {
			fmt.Fprintf(w, "  %s - %s\n", plan.Name, plan.Summary)
		}
		return nil
	}

	plan := payload.WorkflowPlan
	fmt.Fprintf(w, "Workflow plan: %s\n", plan.Name)
	fmt.Fprintf(w, "%s\n", plan.Summary)
	fmt.Fprintln(w, "Safety: local guidance only. Live execution still needs explicit approval.")
	fmt.Fprintln(w)
	for _, phase := range plan.Phases {
		fmt.Fprintf(w, "%s: %s\n", phase.Name, phase.Goal)
		for _, step := range phase.Steps {
			fmt.Fprintf(w, "  - %s\n", step.Name)
		}
	}
	return nil
}

func workflowPlanNamesWithAll() []string {
	names := workflowPlanNames()
	return append(names, "all")
}

func workflowPlanNames() []string {
	plans := workflowPlans()
	names := make([]string, 0, len(plans))
	for _, plan := range plans {
		names = append(names, plan.Name)
	}
	return names
}

func workflowPlanByName(name string) (workflowPlanWorkflow, bool) {
	for _, plan := range workflowPlans() {
		if plan.Name == name {
			return plan, true
		}
	}
	return workflowPlanWorkflow{}, false
}

func workflowPlans() []workflowPlanWorkflow {
	return []workflowPlanWorkflow{
		{
			Name:    "reconciliation",
			Title:   "Reconciliation",
			Summary: "Plan read-side inspection of funding events, payments, charges, payouts, and local store data before matching money movement.",
			Phases: []workflowPlanPhase{
				localSetupPhase("Confirm local setup without contacting Straddle."),
				{
					Name: "Inspect read surfaces",
					Goal: "Identify the exact read commands and filters before any approved live read.",
					Steps: []workflowPlanStep{
						{Name: "Review funding event list filters", Commands: []string{"straddle-pp-cli funding-events list --help"}},
						{Name: "Review payment search filters for charge and payout records", Commands: []string{"straddle-pp-cli payments --help"}},
						{Name: "Review charge and payout command groups", Commands: []string{"straddle-pp-cli charges --help", "straddle-pp-cli payouts --help"}},
					},
				},
				localAnalysisPhase("Use local search or analytics only after a separately approved archive exists."),
			},
			DocsSearchTopics: []string{
				"funding events reconciliation charges payouts settlement",
				"charge payout status funding event webhooks reconciliation",
			},
			ReadOnlyCLICommands: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli funding-events list --help",
				"straddle-pp-cli payments --help",
				"straddle-pp-cli charges --help",
				"straddle-pp-cli payouts --help",
				"straddle-pp-cli search --help",
				"straddle-pp-cli analytics --help",
			},
			DryRunCommands: []string{
				"straddle-pp-cli funding-events list --dry-run --agent",
				"straddle-pp-cli payments --dry-run --agent",
			},
			BlockedWriteActions: []string{
				"Creating, updating, canceling, holding, releasing, or resubmitting payments",
				"Posting webhooks or changing operational state",
				"Running archive or sync without separate approval for the target environment",
			},
			RequiredApprovalsBeforeLiveExecution: commonLiveApprovals("reconciliation"),
		},
		{
			Name:    "fraud-monitoring",
			Title:   "Fraud monitoring",
			Summary: "Plan read-side review of customers, paykeys, charges, returns, and risk signals without taking enforcement action.",
			Phases: []workflowPlanPhase{
				localSetupPhase("Confirm local setup and environment classification."),
				{
					Name: "Inspect review evidence",
					Goal: "Prepare read-only commands that gather evidence without mutating risk state.",
					Steps: []workflowPlanStep{
						{Name: "Review customer and paykey read filters", Commands: []string{"straddle-pp-cli customers list --help", "straddle-pp-cli paykeys list --help"}},
						{Name: "Review payment search and funding event read filters", Commands: []string{"straddle-pp-cli payments --help", "straddle-pp-cli funding-events list --help"}},
					},
				},
				{
					Name: "Escalation boundary",
					Goal: "Keep suspected fraud action outside this local plan.",
					Steps: []workflowPlanStep{
						{Name: "Record write actions as blocked", StopIf: []string{"The next step blocks a paykey, updates a customer, changes a payment, or posts a webhook."}},
					},
				},
			},
			DocsSearchTopics: []string{
				"fraud monitoring customers paykeys returns risk review",
				"ACH return codes unauthorized fraud R05 R07 R10 R29",
			},
			ReadOnlyCLICommands: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli customers list --help",
				"straddle-pp-cli paykeys list --help",
				"straddle-pp-cli payments --help",
				"straddle-pp-cli funding-events list --help",
				"straddle-pp-cli sandbox guide ach-returns --json",
			},
			DryRunCommands: []string{
				"straddle-pp-cli customers list --dry-run --agent",
				"straddle-pp-cli paykeys list --dry-run --agent",
				"straddle-pp-cli payments --dry-run --agent",
			},
			BlockedWriteActions: []string{
				"Blocking or unblocking paykeys",
				"Updating customer or account status",
				"Canceling, holding, releasing, or resubmitting charges",
				"Posting operational webhooks",
			},
			RequiredApprovalsBeforeLiveExecution: commonLiveApprovals("fraud monitoring"),
		},
		{
			Name:    "collections",
			Title:   "Collections",
			Summary: "Plan read-side review for failed or returned charges and customer follow-up without initiating recovery actions.",
			Phases: []workflowPlanPhase{
				localSetupPhase("Confirm local setup without reading credentials."),
				{
					Name: "Inspect recovery evidence",
					Goal: "Review read and dry-run command shapes before any customer action or payment retry.",
					Steps: []workflowPlanStep{
						{Name: "Review payment search and paykey command shape", Commands: []string{"straddle-pp-cli payments --help", "straddle-pp-cli charges get --help", "straddle-pp-cli paykeys list --help"}},
						{Name: "Inspect resubmit request shape without running it", Commands: []string{"straddle-pp-cli charges resubmit create --help"}},
					},
				},
			},
			DocsSearchTopics: []string{
				"collections failed charges returns resubmit",
				"charge status failed reversed return customer communication",
			},
			ReadOnlyCLICommands: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli payments --help",
				"straddle-pp-cli charges get --help",
				"straddle-pp-cli paykeys list --help",
				"straddle-pp-cli charges resubmit create --help",
			},
			DryRunCommands: []string{
				"straddle-pp-cli payments --dry-run --agent",
				"straddle-pp-cli paykeys list --dry-run --agent",
			},
			BlockedWriteActions: []string{
				"Resubmitting charges",
				"Changing payment dates or amounts",
				"Sending customer notices from this CLI plan",
				"Updating customer or paykey records",
			},
			RequiredApprovalsBeforeLiveExecution: commonLiveApprovals("collections"),
		},
		{
			Name:    "reporting",
			Title:   "Reporting",
			Summary: "Plan read-side report inputs and local analysis without running live report generation or exporting sensitive data.",
			Phases: []workflowPlanPhase{
				localSetupPhase("Confirm local setup and base URL classification."),
				{
					Name: "Inspect report inputs",
					Goal: "List available read filters for customers, payments, and funding events.",
					Steps: []workflowPlanStep{
						{Name: "Review read command filters", Commands: []string{"straddle-pp-cli customers list --help", "straddle-pp-cli payments --help", "straddle-pp-cli funding-events list --help"}},
						{Name: "Inspect generated report command shape only", Commands: []string{"straddle-pp-cli reports --help"}},
					},
				},
				localAnalysisPhase("Use analytics, search, or SQL only against an approved local archive."),
			},
			DocsSearchTopics: []string{
				"reporting payment status customer status funding events exports",
				"reports total customers by status charges payouts funding events",
			},
			ReadOnlyCLICommands: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli customers list --help",
				"straddle-pp-cli payments --help",
				"straddle-pp-cli funding-events list --help",
				"straddle-pp-cli reports --help",
				"straddle-pp-cli analytics --help",
				"straddle-pp-cli search --help",
			},
			DryRunCommands: []string{
				"straddle-pp-cli customers list --dry-run --agent",
				"straddle-pp-cli payments --dry-run --agent",
				"straddle-pp-cli funding-events list --dry-run --agent",
			},
			BlockedWriteActions: []string{
				"Running live report exports without approval",
				"Writing customer or payment records",
				"Uploading, publishing, or emailing report output",
			},
			RequiredApprovalsBeforeLiveExecution: commonLiveApprovals("reporting"),
		},
		{
			Name:    "monitoring",
			Title:   "Monitoring",
			Summary: "Plan monitoring checks for payments, funding events, webhooks, and local archive data without polling live systems.",
			Phases: []workflowPlanPhase{
				localSetupPhase("Confirm local setup and classify the configured target."),
				{
					Name: "Inspect monitoring surfaces",
					Goal: "Prepare help and dry-run commands for future approved polling or local analysis.",
					Steps: []workflowPlanStep{
						{Name: "Review tail surfaces", Commands: []string{"straddle-pp-cli tail --json", "straddle-pp-cli tail charges --help", "straddle-pp-cli tail funding-events --help"}},
						{Name: "Review webhook sandbox guidance without posting events", Commands: []string{"straddle-pp-cli sandbox guide webhooks --json"}},
					},
				},
				localAnalysisPhase("Use local analytics only after an approved archive exists."),
			},
			DocsSearchTopics: []string{
				"monitoring payment statuses funding event webhooks errors",
				"webhook event types charge payout funding event monitoring",
			},
			ReadOnlyCLICommands: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli tail --json",
				"straddle-pp-cli tail charges --help",
				"straddle-pp-cli tail funding-events --help",
				"straddle-pp-cli sandbox guide webhooks --json",
				"straddle-pp-cli analytics --help",
				"straddle-pp-cli search --help",
			},
			DryRunCommands: []string{
				"straddle-pp-cli payments --dry-run --agent",
				"straddle-pp-cli funding-events list --dry-run --agent",
			},
			BlockedWriteActions: []string{
				"Polling live systems without approval",
				"Posting webhook test events",
				"Changing payment or funding event state",
				"Opening a production incident action from this plan",
			},
			RequiredApprovalsBeforeLiveExecution: commonLiveApprovals("monitoring"),
		},
	}
}

func localSetupPhase(goal string) workflowPlanPhase {
	return workflowPlanPhase{
		Name: "Local setup",
		Goal: goal,
		Steps: []workflowPlanStep{
			{
				Name:     "Check local CLI readiness",
				Commands: []string{"straddle-pp-cli setup check --json"},
				Checks:   []string{"Confirm output classifies local config without reading or printing credential values."},
			},
		},
	}
}

func localAnalysisPhase(goal string) workflowPlanPhase {
	return workflowPlanPhase{
		Name: "Local analysis",
		Goal: goal,
		Steps: []workflowPlanStep{
			{Name: "Inspect local search and analytics surfaces", Commands: []string{"straddle-pp-cli search --help", "straddle-pp-cli analytics --help"}},
			{Name: "Stop before archive or live reads", StopIf: []string{"The next command would call Straddle, read credentials, sync data, post a webhook, or write output outside stdout."}},
		},
	}
}

func commonLiveApprovals(workflow string) []string {
	return []string{
		"Explicit approval to move the " + workflow + " plan from local guidance to live execution.",
		"Fresh docs lookup approval and review of current fields, statuses, return codes, and webhook names.",
		"Credential scope approval through the caller's secure secret flow.",
		"Environment approval that identifies sandbox or production before any live command runs.",
		"Read-only command list approval; any write action requires a separate approval.",
	}
}

func newWorkflowArchiveCmd(flags *rootFlags) *cobra.Command {
	var dbPath string
	var full bool

	cmd := &cobra.Command{
		Use:   "archive",
		Short: "Sync all resources to local store for offline access and search",
		Long: `Archive fetches all syncable resources from the API and stores them in a
local SQLite database. Supports incremental sync (only new data since last run)
and full resync. After archiving, use 'search' for instant full-text search.`,
		Example: `  # Archive all resources
  straddle-pp-cli workflow archive

  # Full re-archive (ignore previous sync state)
  straddle-pp-cli workflow archive --full`,
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c.NoCache = true

			if dbPath == "" {
				dbPath = defaultDBPath("straddle-pp-cli")
			}
			s, err := store.OpenWithContext(cmd.Context(), dbPath)
			if err != nil {
				return fmt.Errorf("opening store: %w", err)
			}
			defer s.Close()

			resources := []string{"accounts", "customers", "funding-events", "linked-bank-accounts", "organizations", "paykeys", "payments", "representatives"}
			totalSynced := 0

			for _, resource := range resources {
				cursor := ""
				if !full {
					existing, _, _, err := s.GetSyncState(resource)
					if err == nil && existing != "" {
						cursor = existing
					}
				}

				fmt.Fprintf(cmd.ErrOrStderr(), "Syncing %s...\n", resource)

				params := map[string]string{"limit": "100"}
				if cursor != "" {
					params["after"] = cursor
				}

				count := 0
				for {
					data, fetchErr := c.Get("/"+resource, params)
					if fetchErr != nil {
						fmt.Fprintf(cmd.ErrOrStderr(), "  warning: %s: %v\n", resource, fetchErr)
						break
					}
					var items []json.RawMessage
					if err := json.Unmarshal(data, &items); err != nil {
						// Might be a single object, not array
						if err := s.Upsert(resource, resource+"-singleton", data); err != nil {
							fmt.Fprintf(cmd.ErrOrStderr(), "  warning: store %s: %v\n", resource, err)
						}
						count++
						break
					}
					if len(items) == 0 {
						break
					}
					for _, item := range items {
						var obj struct {
							ID string `json:"id"`
						}
						json.Unmarshal(item, &obj)
						id := obj.ID
						if id == "" {
							id = fmt.Sprintf("%s-%d", resource, count)
						}
						if err := s.Upsert(resource, id, item); err != nil {
							fmt.Fprintf(cmd.ErrOrStderr(), "  warning: store %s/%s: %v\n", resource, id, err)
						}
						cursor = id
						count++
					}
					if len(items) < 100 {
						break
					}
					params["after"] = cursor
				}

				if count > 0 {
					s.SaveSyncState(resource, cursor, count)
				}
				totalSynced += count
				fmt.Fprintf(cmd.ErrOrStderr(), "  %s: %d items\n", resource, count)
			}

			if flags.asJSON {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(map[string]any{
					"resources_synced": len(resources),
					"total_items":      totalSynced,
					"store_path":       dbPath,
					"timestamp":        time.Now().UTC().Format(time.RFC3339),
				})
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Archived %d items across %d resources to %s\n", totalSynced, len(resources), dbPath)
			return nil
		},
	}

	cmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/straddle-pp-cli/data.db)")
	cmd.Flags().BoolVar(&full, "full", false, "Full re-archive (ignore previous sync state)")

	return cmd
}

func newWorkflowStatusCmd(flags *rootFlags) *cobra.Command {
	var dbPath string

	cmd := &cobra.Command{
		Use:         "status",
		Short:       "Show local archive status and sync state for all resources",
		Annotations: map[string]string{"mcp:read-only": "true"},
		Example: `  # Show archive status
  straddle-pp-cli workflow status

  # Show status as JSON
  straddle-pp-cli workflow status --json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if dbPath == "" {
				dbPath = defaultDBPath("straddle-pp-cli")
			}
			s, err := store.OpenWithContext(cmd.Context(), dbPath)
			if err != nil {
				return fmt.Errorf("opening store: %w", err)
			}
			defer s.Close()

			status, err := s.Status()
			if err != nil {
				return err
			}

			if flags.asJSON {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(status)
			}

			if len(status) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "No archived data. Run 'workflow archive' to sync.")
				return nil
			}

			fmt.Fprintln(cmd.OutOrStdout(), "Archive Status:")
			total := 0
			for resource, count := range status {
				fmt.Fprintf(cmd.OutOrStdout(), "  %-30s %d items\n", resource, count)
				total += count
			}
			fmt.Fprintf(cmd.OutOrStdout(), "\n  Total: %d items\n", total)
			fmt.Fprintf(cmd.OutOrStdout(), "  Store: %s\n", dbPath)
			return nil
		},
	}

	cmd.Flags().StringVar(&dbPath, "db", "", "Database path")

	return cmd
}

// defaultDBPath is defined in helpers.go
