// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newChargesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAmount int
	var bodyConfig string
	var bodyConsentType string
	var bodyCurrency string
	var bodyDescription string
	var bodyDevice string
	var bodyExternalId string
	var bodyMetadata string
	var bodyPaykey string
	var bodyPaymentDate string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Use charges to collect money from a customer for the sale of goods or services.",
		Example:     "  straddle-pp-cli charges create --consent-type example-value",
		Annotations: map[string]string{"pp:endpoint": "charges.create", "pp:method": "POST", "pp:path": "/v1/charges"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("amount") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "amount")
				}
				if !cmd.Flags().Changed("config") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "config")
				}
				if !cmd.Flags().Changed("consent-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "consent-type")
				}
				if !cmd.Flags().Changed("description") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "description")
				}
				if !cmd.Flags().Changed("device") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "device")
				}
				if !cmd.Flags().Changed("external-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "external-id")
				}
				if !cmd.Flags().Changed("paykey") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "paykey")
				}
				if !cmd.Flags().Changed("payment-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "payment-date")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/charges"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAmount != 0 {
					body["amount"] = bodyAmount
				}
				if bodyConfig != "" {
					var parsedConfig any
					if err := json.Unmarshal([]byte(bodyConfig), &parsedConfig); err != nil {
						return fmt.Errorf("parsing --config JSON: %w", err)
					}
					body["config"] = parsedConfig
				}
				if bodyConsentType != "" {
					body["consent_type"] = bodyConsentType
				}
				if bodyCurrency != "" {
					body["currency"] = bodyCurrency
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyDevice != "" {
					var parsedDevice any
					if err := json.Unmarshal([]byte(bodyDevice), &parsedDevice); err != nil {
						return fmt.Errorf("parsing --device JSON: %w", err)
					}
					body["device"] = parsedDevice
				}
				if bodyExternalId != "" {
					body["external_id"] = bodyExternalId
				}
				if bodyMetadata != "" {
					var parsedMetadata any
					if err := json.Unmarshal([]byte(bodyMetadata), &parsedMetadata); err != nil {
						return fmt.Errorf("parsing --metadata JSON: %w", err)
					}
					body["metadata"] = parsedMetadata
				}
				if bodyPaykey != "" {
					body["paykey"] = bodyPaykey
				}
				if bodyPaymentDate != "" {
					body["payment_date"] = bodyPaymentDate
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "charges",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyAmount, "amount", 0, "The amount of the charge in cents.")
	cmd.Flags().StringVar(&bodyConfig, "config", "", "Config")
	cmd.Flags().StringVar(&bodyConsentType, "consent-type", "", "The channel or mechanism through which the payment was authorized. Use `internet` for payments made online or...")
	cmd.Flags().StringVar(&bodyCurrency, "currency", "USD", "The currency of the charge. Only USD is supported.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "An arbitrary description for the charge.")
	cmd.Flags().StringVar(&bodyDevice, "device", "", "Device")
	cmd.Flags().StringVar(&bodyExternalId, "external-id", "", "Unique identifier for the charge in your database. This value must be unique across all charges.")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Up to 20 additional user-defined key-value pairs. Useful for storing additional information about the charge in a...")
	cmd.Flags().StringVar(&bodyPaykey, "paykey", "", "Value of the `paykey` used for the charge.")
	cmd.Flags().StringVar(&bodyPaymentDate, "payment-date", "", "The desired date on which the payment should be occur. For charges, this means the date you want the customer to be...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
