// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// PATCH: credentials-plan covers local-only credential storage guidance without reading or exposing token values.
func TestCredentialsPlanNoArgJSONReturnsSurfacesAndSafety(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "fixture-secret-token-never-print")

	stdout, stderr, err := runCLIForDocsTest(t, "credentials", "plan", "--json")
	if err != nil {
		t.Fatalf("credentials plan --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("credentials plan wrote stderr: %q", stderr)
	}

	var got credentialsPlanResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("credentials plan --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "credentials plan" {
		t.Fatalf("command = %q, want credentials plan", got.Command)
	}
	wantSurfaces := []string{"config", "environment", "mcp", "keychain", "packaged-client", "launch", "all"}
	if strings.Join(got.AvailableSurfaces, ",") != strings.Join(wantSurfaces, ",") {
		t.Fatalf("available surfaces = %#v, want %#v", got.AvailableSurfaces, wantSurfaces)
	}
	if len(got.Blockers) == 0 {
		t.Fatalf("credentials plan should include top-level blockers")
	}
	if !got.Safety.GuidanceOnly || !got.Safety.LocalOnly || !got.Safety.DoesNotReadSecrets || !got.Safety.DoesNotPrintSecrets || !got.Safety.DoesNotInspectEnvironmentTokenValue {
		t.Fatalf("credentials plan should be local guidance without secret reads or token inspection: %#v", got.Safety)
	}
	if got.Safety.WritesCredentials || got.Safety.CallsStraddleAPIs || got.Safety.CallsDocsEndpoints || got.Safety.ExecutesMCPTools || got.Safety.Publishes || got.Safety.Signs || got.Safety.Notarizes || got.Safety.ApprovesLaunch {
		t.Fatalf("credentials plan should not write, call services, execute MCP, publish, sign, notarize, or approve launch: %#v", got.Safety)
	}
	if strings.Contains(stdout, "fixture-secret-token-never-print") {
		t.Fatalf("credentials plan leaked STRADDLE_TOKEN value:\n%s", stdout)
	}
}

func TestCredentialsPlanNamedSurfacesIncludeRequiredRunbookData(t *testing.T) {
	tests := map[string][]string{
		"config": {
			"auth set-token --stdin",
			"Config path can be customized",
			"launch-grade storage still needs approval",
		},
		"environment": {
			"shells, CI, and MCP launches",
			"should not be printed, logged, committed, or passed through argv",
		},
		"mcp": {
			"MCP STRADDLE_TOKEN environment injection",
			"CLI config-file auth",
			"desktop MCP public install remains future work",
		},
		"keychain": {
			"keychain-backed storage exists as opt-in preview support",
			"auth set-token --stdin --keychain",
			"owner/security approval",
			"Run and review packaged-client smoke before broad launch",
			"packaged-client smoke is only planned or local evidence until run and reviewed",
			"Signed/notarized packaging posture is still required before broad public launch",
			"Desktop MCP packaging posture is still required before broad public launch",
			"approved live read-only smoke",
		},
		"packaged-client": {
			"built CLI/MCP binaries",
			"make package-readiness",
			"dist/local/straddle-pp-cli setup check --json",
			"dist/local/straddle-pp-cli credentials plan packaged-client --json",
			"dist/local/straddle-pp-cli auth status --json",
			"dist/local/straddle-pp-mcp",
			"JSON-RPC tools/list",
			"credential-bearing MCP tools",
			"packaged-client smoke is only planned or local evidence until run and reviewed",
			"broad public launch remains blocked",
			"does not build packages",
			"does not read secrets",
			"does not write credentials",
			"does not approve launch",
		},
		"launch": {
			"blocking decision set",
			"keychain-backed storage exists as opt-in preview support",
			"Run and review packaged-client smoke before broad public launch",
			"packaged-client smoke is only planned or local evidence until run and reviewed",
			"Signed/notarized packaging posture is missing",
			"Desktop MCP packaging posture is missing",
			"approved live read-only smoke",
			"docs wording",
		},
	}

	for surface, wantStrings := range tests {
		t.Run(surface, func(t *testing.T) {
			t.Setenv("STRADDLE_TOKEN", "fixture-secret-token-never-print")

			stdout, stderr, err := runCLIForDocsTest(t, "credentials", "plan", surface, "--json")
			if err != nil {
				t.Fatalf("credentials plan %s --json returned error: %v", surface, err)
			}
			if stderr != "" {
				t.Fatalf("credentials plan %s wrote stderr: %q", surface, stderr)
			}

			var got credentialsPlanResponse
			if err := json.Unmarshal([]byte(stdout), &got); err != nil {
				t.Fatalf("credentials plan %s --json emitted invalid JSON: %v\n%s", surface, err, stdout)
			}
			if got.Surface != surface || got.SurfacePlan == nil {
				t.Fatalf("expected %s surface plan, got %#v", surface, got)
			}
			if got.SurfacePlan.CurrentSupport == "" {
				t.Fatalf("%s surface should include current support", surface)
			}
			if len(got.SurfacePlan.LocalProofCommands) == 0 && len(got.SurfacePlan.LocalChecks) == 0 {
				t.Fatalf("%s surface should include local proof commands or local checks", surface)
			}
			if len(got.SurfacePlan.LaunchDecisionNeeded) == 0 {
				t.Fatalf("%s surface should include launch decisions", surface)
			}
			if len(got.SurfacePlan.Blockers) == 0 {
				t.Fatalf("%s surface should include blockers", surface)
			}
			if len(got.SurfacePlan.Notes) == 0 {
				t.Fatalf("%s surface should include notes", surface)
			}
			if surface == "packaged-client" {
				foundMCPToolsListProof := false
				for _, command := range got.SurfacePlan.LocalProofCommands {
					if strings.Contains(command, "dist/local/straddle-pp-mcp") && strings.Contains(command, "tools/list") {
						foundMCPToolsListProof = true
						break
					}
				}
				if !foundMCPToolsListProof {
					t.Fatalf("packaged-client local proof commands should include a runnable dist/local/straddle-pp-mcp tools/list command: %#v", got.SurfacePlan.LocalProofCommands)
				}
			}
			for _, want := range wantStrings {
				if !strings.Contains(stdout, want) {
					t.Fatalf("%s surface should include %q:\n%s", surface, want, stdout)
				}
			}
			if strings.Contains(stdout, "fixture-secret-token-never-print") || strings.Contains(stdout, "Bearer ") || strings.Contains(stdout, "STRADDLE_TOKEN=") {
				t.Fatalf("credentials plan should not emit token values, bearer examples, or env assignments:\n%s", stdout)
			}
		})
	}
}

func TestCredentialsPlanAllIncludesEveryConcreteSurfacePlan(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "credentials", "plan", "all", "--json")
	if err != nil {
		t.Fatalf("credentials plan all --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("credentials plan all wrote stderr: %q", stderr)
	}

	var got credentialsPlanResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("credentials plan all --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Surface != "all" {
		t.Fatalf("surface = %q, want all", got.Surface)
	}
	if len(got.SurfacePlans) != 6 {
		t.Fatalf("all surface should include six concrete surface plans, got %d: %#v", len(got.SurfacePlans), got.SurfacePlans)
	}
	if got.SurfacePlan != nil {
		t.Fatalf("all surface should use surface_plans, not surface_plan: %#v", got.SurfacePlan)
	}
}

func TestCredentialsPlanInvalidSurfaceReturnsUsageError(t *testing.T) {
	_, _, err := runCLIForDocsTest(t, "credentials", "plan", "not-a-surface", "--json")
	if err == nil {
		t.Fatalf("credentials plan should reject invalid surfaces")
	}
	var cliErr *cliError
	if !errors.As(err, &cliErr) || cliErr.code != 2 {
		t.Fatalf("invalid surface should be a usage error, got %#v", err)
	}
	if !strings.Contains(err.Error(), "supported surfaces") {
		t.Fatalf("invalid surface error should list supported surfaces, got %v", err)
	}
}

func TestCredentialsPlanAgentUsesTargetEnvelope(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "credentials", "plan", "keychain", "--agent")
	if err != nil {
		t.Fatalf("credentials plan --agent returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("credentials plan --agent wrote stderr: %q", stderr)
	}

	var got struct {
		SchemaVersion string `json:"schema_version"`
		Data          struct {
			Command     string                  `json:"command"`
			Surface     string                  `json:"surface"`
			SurfacePlan *credentialsSurfacePlan `json:"surface_plan"`
			Safety      credentialsSafety       `json:"safety"`
		} `json:"data"`
		Warnings []string        `json:"warnings"`
		Results  json.RawMessage `json:"results"`
		Meta     json.RawMessage `json:"meta"`
	}
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("credentials plan --agent emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.SchemaVersion != "1.0" {
		t.Fatalf("schema_version: want 1.0, got %q", got.SchemaVersion)
	}
	if got.Data.Command != "credentials plan" || got.Data.Surface != "keychain" || got.Data.SurfacePlan == nil {
		t.Fatalf("agent data should contain keychain credentials plan: %#v", got.Data)
	}
	if !got.Data.Safety.GuidanceOnly || !got.Data.Safety.DoesNotReadSecrets || got.Data.Safety.WritesCredentials || got.Data.Safety.ApprovesLaunch {
		t.Fatalf("agent safety should remain local guidance only: %#v", got.Data.Safety)
	}
	if got.Warnings == nil {
		t.Fatalf("warnings should be an empty array, not null")
	}
	if got.Results != nil || got.Meta != nil {
		t.Fatalf("target envelope should not include top-level results/meta")
	}
}

func TestCredentialsPlanRejectsDeliverBeforeDelivery(t *testing.T) {
	target := filepath.Join(t.TempDir(), "credentials-plan-delivery.json")

	oldArgs := os.Args
	t.Cleanup(func() {
		os.Args = oldArgs
	})
	os.Args = []string{
		"straddle-pp-cli",
		"credentials",
		"plan",
		"--deliver",
		"file:" + target,
	}

	err := Execute()
	if err == nil {
		t.Fatalf("credentials plan should reject --deliver")
	}
	if !strings.Contains(err.Error(), "credentials plan does not support --deliver") {
		t.Fatalf("error should explain --deliver is unsupported, got %v", err)
	}
	if _, statErr := os.Stat(target); !os.IsNotExist(statErr) {
		t.Fatalf("credentials plan should reject --deliver before writing output, stat err=%v", statErr)
	}
}
