// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCH: credentials-plan adds local-only credential storage guidance without reading or exposing secrets.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

type credentialsSafety struct {
	GuidanceOnly                        bool `json:"guidance_only"`
	LocalOnly                           bool `json:"local_only"`
	DoesNotReadSecrets                  bool `json:"does_not_read_secrets"`
	DoesNotPrintSecrets                 bool `json:"does_not_print_secrets"`
	DoesNotWriteCredentials             bool `json:"does_not_write_credentials"`
	DoesNotInspectEnvironmentTokenValue bool `json:"does_not_inspect_environment_token_value"`
	WritesCredentials                   bool `json:"writes_credentials"`
	CallsStraddleAPIs                   bool `json:"calls_straddle_apis"`
	CallsDocsEndpoints                  bool `json:"calls_docs_endpoints"`
	ExecutesMCPTools                    bool `json:"executes_mcp_tools"`
	Publishes                           bool `json:"publishes"`
	Signs                               bool `json:"signs"`
	Notarizes                           bool `json:"notarizes"`
	ApprovesLaunch                      bool `json:"approves_launch"`
}

type credentialsSurfacePlan struct {
	Name                 string   `json:"name"`
	Title                string   `json:"title"`
	Summary              string   `json:"summary"`
	CurrentSupport       string   `json:"current_support"`
	LocalProofCommands   []string `json:"local_proof_commands,omitempty"`
	LocalChecks          []string `json:"local_checks,omitempty"`
	LaunchDecisionNeeded []string `json:"launch_decision_needed"`
	Blockers             []string `json:"blockers"`
	Notes                []string `json:"notes,omitempty"`
}

type credentialsPlanResponse struct {
	Command           string                   `json:"command"`
	Surface           string                   `json:"surface,omitempty"`
	AvailableSurfaces []string                 `json:"available_surfaces,omitempty"`
	SurfacePlan       *credentialsSurfacePlan  `json:"surface_plan,omitempty"`
	SurfacePlans      []credentialsSurfacePlan `json:"surface_plans,omitempty"`
	Safety            credentialsSafety        `json:"safety"`
	RunbookPurpose    string                   `json:"runbook_purpose"`
	Blockers          []string                 `json:"blockers"`
}

func newCredentialsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "credentials",
		Short: "Plan credential storage readiness",
		Long:  "Plan credential storage readiness without reading, writing, or printing secrets.",
	}
	cmd.AddCommand(newCredentialsPlanCmd(flags))
	return cmd
}

func newCredentialsPlanCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "plan [surface]",
		Short: "Generate a local-only credential storage runbook",
		Long: `Generate local-only credential storage guidance.

This command is guidance-only. It does not read secrets, print secrets, write credentials, call Straddle APIs, call docs endpoints, execute MCP tools, inspect the environment token value, publish, sign, notarize, or approve launch.`,
		Example: `  straddle-pp-cli credentials plan
  straddle-pp-cli credentials plan all --json
  straddle-pp-cli credentials plan keychain --agent`,
		Annotations: map[string]string{
			"mcp:read-only": "true",
		},
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if flags.deliverSpec != "" {
				return usageErr(fmt.Errorf("credentials plan does not support --deliver; use normal stdout, JSON, or agent output"))
			}

			surface := ""
			if len(args) == 1 {
				surface = strings.ToLower(strings.TrimSpace(args[0]))
			}
			payload, err := buildCredentialsPlanResponse(surface)
			if err != nil {
				return usageErr(err)
			}
			return renderCredentialsPlanResponse(cmd, flags, payload)
		},
	}
	return cmd
}

func buildCredentialsPlanResponse(surface string) (credentialsPlanResponse, error) {
	payload := credentialsPlanResponse{
		Command:           "credentials plan",
		AvailableSurfaces: credentialsSurfaceNames(),
		Safety: credentialsSafety{
			GuidanceOnly:                        true,
			LocalOnly:                           true,
			DoesNotReadSecrets:                  true,
			DoesNotPrintSecrets:                 true,
			DoesNotWriteCredentials:             true,
			DoesNotInspectEnvironmentTokenValue: true,
			WritesCredentials:                   false,
			CallsStraddleAPIs:                   false,
			CallsDocsEndpoints:                  false,
			ExecutesMCPTools:                    false,
			Publishes:                           false,
			Signs:                               false,
			Notarizes:                           false,
			ApprovesLaunch:                      false,
		},
		RunbookPurpose: "Reduce the credential storage launch blocker by listing current support, safe local checks, required decisions, and blockers. This command only prints guidance.",
		Blockers: []string{
			"No OS keychain or secure-store implementation exists yet.",
			"Launch needs an explicit decision: approve env/config-only for first public release or implement OS secure storage.",
			"Desktop MCP public install remains future work.",
		},
	}
	if surface == "" {
		return payload, nil
	}
	if surface == "all" {
		payload.Surface = surface
		payload.SurfacePlans = credentialsSurfacePlans()
		return payload, nil
	}
	plan, ok := credentialsSurfacePlanByName(surface)
	if !ok {
		return payload, fmt.Errorf("invalid credentials surface %q: supported surfaces are %s", surface, strings.Join(credentialsSurfaceNames(), ", "))
	}
	payload.Surface = plan.Name
	payload.SurfacePlan = &plan
	return payload, nil
}

func renderCredentialsPlanResponse(cmd *cobra.Command, flags *rootFlags, payload credentialsPlanResponse) error {
	asJSON := flags.asJSON || flags.agent || !isTerminal(cmd.OutOrStdout())
	if asJSON {
		return printJSONFiltered(cmd.OutOrStdout(), payload, flags)
	}

	w := cmd.OutOrStdout()
	if payload.Surface == "" {
		fmt.Fprintln(w, "Credentials plan")
		fmt.Fprintln(w, "Safety: local guidance only. No secret reads, credential writes, API calls, docs calls, MCP execution, publishing, signing, notarization, or launch approval.")
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Surfaces:")
		for _, surface := range payload.AvailableSurfaces {
			fmt.Fprintf(w, "  %s\n", surface)
		}
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Blockers:")
		for _, blocker := range payload.Blockers {
			fmt.Fprintf(w, "  %s\n", blocker)
		}
		return nil
	}
	if payload.Surface == "all" {
		fmt.Fprintln(w, "Credentials plan: all")
		fmt.Fprintln(w, "Safety: local guidance only. Public launch still needs credential storage decisions.")
		for _, plan := range payload.SurfacePlans {
			fmt.Fprintf(w, "  %s - %s\n", plan.Name, plan.Summary)
		}
		return nil
	}

	plan := payload.SurfacePlan
	fmt.Fprintf(w, "Credentials plan: %s\n", plan.Name)
	fmt.Fprintf(w, "Current support: %s\n", plan.CurrentSupport)
	fmt.Fprintln(w, "Launch decision needed:")
	for _, decision := range plan.LaunchDecisionNeeded {
		fmt.Fprintf(w, "  %s\n", decision)
	}
	fmt.Fprintln(w, "Blockers:")
	for _, blocker := range plan.Blockers {
		fmt.Fprintf(w, "  %s\n", blocker)
	}
	return nil
}

func credentialsSurfaceNames() []string {
	return []string{"config", "environment", "mcp", "keychain", "launch", "all"}
}

func credentialsSurfacePlanByName(name string) (credentialsSurfacePlan, bool) {
	for _, plan := range credentialsSurfacePlans() {
		if plan.Name == name {
			return plan, true
		}
	}
	return credentialsSurfacePlan{}, false
}

func credentialsSurfacePlans() []credentialsSurfacePlan {
	return []credentialsSurfacePlan{
		{
			Name:           "config",
			Title:          "CLI config-file credential storage",
			Summary:        "Use the existing config-file token path while keeping launch-grade storage approval explicit.",
			CurrentSupport: "Current config-file token setup uses auth set-token --stdin. Config path can be customized with --config or STRADDLE_CONFIG.",
			LocalProofCommands: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli auth status --json",
				"straddle-pp-cli auth set-token --stdin",
			},
			LocalChecks: []string{
				"Confirm help and docs route token entry through stdin.",
				"Confirm config path can be customized without printing the token value.",
			},
			LaunchDecisionNeeded: []string{
				"Approve whether config-file token storage is acceptable for the first public release.",
				"Decide whether launch-grade storage still needs approval before public docs recommend config-file auth.",
			},
			Blockers: []string{
				"Config-file auth exists, but launch-grade storage still needs approval.",
				"No OS secure storage is connected to the config path.",
			},
			Notes: []string{
				"This command does not open or inspect the config file.",
			},
		},
		{
			Name:           "environment",
			Title:          "Environment and secret-manager injection",
			Summary:        "Use caller-controlled environment injection for shells, CI, and MCP launches without printing token values.",
			CurrentSupport: "Environment or secret-manager injection is supported for shells, CI, and MCP launches through STRADDLE_TOKEN.",
			LocalProofCommands: []string{
				"test -n \"${STRADDLE_TOKEN+x}\" && echo STRADDLE_TOKEN is present",
				"straddle-pp-cli setup check --json",
			},
			LocalChecks: []string{
				"Verify the token variable is present without printing its value.",
				"Confirm token values are not printed, logged, committed, or passed through argv.",
			},
			LaunchDecisionNeeded: []string{
				"Approve whether environment and secret-manager injection is sufficient for first public release.",
				"Decide the public docs wording for shell, CI, and MCP launch token injection.",
			},
			Blockers: []string{
				"Environment injection depends on the caller's secret manager and process environment controls.",
				"Public launch still needs guidance that token values should not be printed, logged, committed, or passed through argv.",
			},
			Notes: []string{
				"This command does not read or inspect STRADDLE_TOKEN value.",
			},
		},
		{
			Name:           "mcp",
			Title:          "MCP credential injection",
			Summary:        "Keep MCP token injection separate from CLI config-file auth.",
			CurrentSupport: "MCP STRADDLE_TOKEN environment injection is separate from CLI config-file auth.",
			LocalProofCommands: []string{
				"straddle-pp-cli credentials plan mcp --json",
				"straddle-pp-cli setup check --json",
			},
			LocalChecks: []string{
				"Confirm MCP launch configuration injects STRADDLE_TOKEN through the host environment.",
				"Confirm CLI config-file auth remains a separate local CLI path.",
			},
			LaunchDecisionNeeded: []string{
				"Decide whether first public release documents MCP env injection only.",
				"Decide when desktop MCP public install becomes a supported launch path.",
			},
			Blockers: []string{
				"desktop MCP public install remains future work.",
				"MCP STRADDLE_TOKEN environment injection must not be confused with CLI config-file auth.",
			},
			Notes: []string{
				"This command does not execute MCP tools or inspect host MCP configuration.",
			},
		},
		{
			Name:           "keychain",
			Title:          "OS keychain or secure-store decision",
			Summary:        "Record that no OS keychain or secure-store implementation exists yet.",
			CurrentSupport: "No OS keychain or secure-store implementation exists yet.",
			LocalChecks: []string{
				"Review credential storage code for config-file and environment paths only.",
				"Confirm no launch docs claim OS keychain support.",
			},
			LaunchDecisionNeeded: []string{
				"Explicitly approve env/config-only for first public release or implement OS secure storage.",
			},
			Blockers: []string{
				"No OS keychain or secure-store implementation exists yet.",
				"Launch needs an explicit decision: approve env/config-only for first public release or implement OS secure storage.",
			},
			Notes: []string{
				"This command does not probe OS credential stores.",
			},
		},
		{
			Name:           "launch",
			Title:          "Credential launch decision set",
			Summary:        "Summarize the blocking decision set for public launch.",
			CurrentSupport: "Safe stdin config-file auth and environment injection exist. OS secure storage and desktop MCP public install do not.",
			LocalProofCommands: []string{
				"straddle-pp-cli credentials plan all --json",
				"straddle-pp-cli release plan all --json",
			},
			LocalChecks: []string{
				"Confirm docs and generated skill describe current support without approving launch.",
				"Confirm launch notes do not claim OS secure storage or desktop MCP public install.",
			},
			LaunchDecisionNeeded: []string{
				"Resolve the blocking decision set: ship env/config-only, or implement OS secure storage before public release.",
				"Decide whether MCP env injection is enough for first release while desktop MCP public install remains future work.",
				"Decide public wording for config path customization and secret-manager injection.",
			},
			Blockers: []string{
				"Credential storage launch decision remains open.",
				"env/config-only approval is missing.",
				"OS secure storage implementation is missing.",
				"Desktop MCP public install remains future work.",
			},
			Notes: []string{
				"This command records required decisions only and does not approve launch.",
			},
		},
	}
}
