// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCustomersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "customers",
		Short: "Customers represent the end users who send or receive payments through your integration. Each customer undergoes...",
	}

	cmd.AddCommand(newCustomersCreateCmd(flags))
	cmd.AddCommand(newCustomersDeleteCmd(flags))
	cmd.AddCommand(newCustomersGetCmd(flags))
	cmd.AddCommand(newCustomersListCmd(flags))
	cmd.AddCommand(newCustomersUpdateCmd(flags))
	cmd.AddCommand(newCustomersRefreshReviewCmd(flags))
	cmd.AddCommand(newCustomersReviewCmd(flags))
	cmd.AddCommand(newCustomersUnmaskedCmd(flags))
	return cmd
}
