// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCustomersCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAddress string
	var bodyComplianceProfile string
	var bodyConfig string
	var bodyDevice string
	var bodyEmail string
	var bodyExternalId string
	var bodyMetadata string
	var bodyName string
	var bodyPhone string
	var bodyType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Creates a new customer record and automatically initiates identity, fraud, and risk assessment scores. This endpoint...",
		Example:     "  straddle-pp-cli customers create --email user@example.com",
		Annotations: map[string]string{"pp:endpoint": "customers.create", "pp:method": "POST", "pp:path": "/v1/customers"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("device") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "device")
				}
				if !cmd.Flags().Changed("email") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "email")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("phone") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "phone")
				}
				if !cmd.Flags().Changed("type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/customers"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAddress != "" {
					var parsedAddress any
					if err := json.Unmarshal([]byte(bodyAddress), &parsedAddress); err != nil {
						return fmt.Errorf("parsing --address JSON: %w", err)
					}
					body["address"] = parsedAddress
				}
				if bodyComplianceProfile != "" {
					body["compliance_profile"] = bodyComplianceProfile
				}
				if bodyConfig != "" {
					var parsedConfig any
					if err := json.Unmarshal([]byte(bodyConfig), &parsedConfig); err != nil {
						return fmt.Errorf("parsing --config JSON: %w", err)
					}
					body["config"] = parsedConfig
				}
				if bodyDevice != "" {
					var parsedDevice any
					if err := json.Unmarshal([]byte(bodyDevice), &parsedDevice); err != nil {
						return fmt.Errorf("parsing --device JSON: %w", err)
					}
					body["device"] = parsedDevice
				}
				if bodyEmail != "" {
					body["email"] = bodyEmail
				}
				if bodyExternalId != "" {
					body["external_id"] = bodyExternalId
				}
				if bodyMetadata != "" {
					var parsedMetadata any
					if err := json.Unmarshal([]byte(bodyMetadata), &parsedMetadata); err != nil {
						return fmt.Errorf("parsing --metadata JSON: %w", err)
					}
					body["metadata"] = parsedMetadata
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyPhone != "" {
					body["phone"] = bodyPhone
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "customers",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAddress, "address", "", "An object containing the customer's address. **This is optional.** If used, all required fields must be present.")
	cmd.Flags().StringVar(&bodyComplianceProfile, "compliance-profile", "", "An object containing the customer's compliance profile. **This is optional.** If all required fields must be present...")
	cmd.Flags().StringVar(&bodyConfig, "config", "", "Config")
	cmd.Flags().StringVar(&bodyDevice, "device", "", "Device")
	cmd.Flags().StringVar(&bodyEmail, "email", "", "The customer's email address.")
	cmd.Flags().StringVar(&bodyExternalId, "external-id", "", "Unique identifier for the customer in your database, used for cross-referencing between Straddle and your systems.")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Up to 20 additional user-defined key-value pairs. Useful for storing additional information about the customer in a...")
	cmd.Flags().StringVar(&bodyName, "name", "", "Full name of the individual or business name.")
	cmd.Flags().StringVar(&bodyPhone, "phone", "", "The customer's phone number in E.164 format. Mobile number is preferred.")
	cmd.Flags().StringVar(&bodyType, "type", "", "Type")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
