// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCH: dry-run-agent-output guards generated endpoint dry-runs in agent mode.

package cli

import (
	"bytes"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCustomersListDryRunAgentSuppressesHumanPreview(t *testing.T) {
	configPath := writeDryRunTestConfig(t)

	cmd := RootCmd()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)
	cmd.SetArgs([]string{"customers", "list", "--dry-run", "--agent", "--config", configPath})

	processStderr, err := captureProcessStderr(t, func() error {
		return cmd.Execute()
	})
	if err != nil {
		t.Fatalf("customers list --dry-run --agent returned error: %v", err)
	}
	if stderr.Len() != 0 {
		t.Fatalf("customers list --dry-run --agent wrote command stderr: %q", stderr.String())
	}
	if processStderr != "" {
		t.Fatalf("customers list --dry-run --agent wrote human preview to process stderr: %q", processStderr)
	}
	if strings.Contains(stdout.String(), "GET ") || strings.Contains(stdout.String(), "dry run - no request sent") {
		t.Fatalf("stdout should contain only JSON agent output, got %q", stdout.String())
	}

	var got struct {
		SchemaVersion string `json:"schema_version"`
		Data          struct {
			DryRun bool `json:"dry_run"`
		} `json:"data"`
		Error any `json:"error"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &got); err != nil {
		t.Fatalf("customers list --dry-run --agent emitted invalid JSON: %v\n%s", err, stdout.String())
	}
	if got.SchemaVersion != "1.0" {
		t.Fatalf("schema_version: want 1.0, got %q", got.SchemaVersion)
	}
	if !got.Data.DryRun {
		t.Fatalf("agent data should report dry_run true: %#v", got.Data)
	}
	if got.Error != nil {
		t.Fatalf("agent error should be null: %#v", got.Error)
	}
}

func TestCustomersListDryRunWithoutAgentKeepsHumanPreview(t *testing.T) {
	configPath := writeDryRunTestConfig(t)

	cmd := RootCmd()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)
	cmd.SetArgs([]string{"customers", "list", "--dry-run", "--config", configPath})

	processStderr, err := captureProcessStderr(t, func() error {
		return cmd.Execute()
	})
	if err != nil {
		t.Fatalf("customers list --dry-run returned error: %v", err)
	}
	if stderr.Len() != 0 {
		t.Fatalf("customers list --dry-run wrote command stderr: %q", stderr.String())
	}
	if !strings.Contains(processStderr, "GET https://sandbox.straddle.com/v1/customers") {
		t.Fatalf("non-agent dry-run should keep request preview, got %q", processStderr)
	}
	if !strings.Contains(processStderr, "(dry run - no request sent)") {
		t.Fatalf("non-agent dry-run should keep no-request notice, got %q", processStderr)
	}
	if stdout.Len() == 0 {
		t.Fatalf("dry-run should still emit command result data")
	}
}

func TestPrintProvenanceSuppressesAgentModeWhenTerminal(t *testing.T) {
	restore := forceTerminalForDryRunTest(t)
	defer restore()

	cmd := RootCmd()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)
	if err := cmd.PersistentFlags().Set("agent", "true"); err != nil {
		t.Fatalf("setting agent flag: %v", err)
	}

	printProvenance(cmd, 3, DataProvenance{Source: "live"})

	if stderr.Len() != 0 {
		t.Fatalf("agent provenance should be suppressed, got %q", stderr.String())
	}
}

func TestPrintProvenanceKeepsNonAgentTerminalOutput(t *testing.T) {
	restore := forceTerminalForDryRunTest(t)
	defer restore()

	cmd := RootCmd()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)

	printProvenance(cmd, 3, DataProvenance{Source: "live"})

	if got := stderr.String(); got != "3 results (live)\n" {
		t.Fatalf("non-agent provenance should be preserved, got %q", got)
	}
}

func writeDryRunTestConfig(t *testing.T) string {
	t.Helper()

	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("STRADDLE_CONFIG", "")
	t.Setenv("STRADDLE_BASE_URL", "")
	t.Setenv("STRADDLE_TOKEN", "")

	configPath := filepath.Join(home, ".config", "straddle-pp-cli", "config.toml")
	if err := os.MkdirAll(filepath.Dir(configPath), 0o700); err != nil {
		t.Fatalf("creating config dir: %v", err)
	}
	if err := os.WriteFile(configPath, []byte("base_url = \"https://sandbox.straddle.com\"\n"), 0o600); err != nil {
		t.Fatalf("writing config: %v", err)
	}
	return configPath
}

func forceTerminalForDryRunTest(t *testing.T) func() {
	t.Helper()

	old := isTerminalWriter
	isTerminalWriter = func(io.Writer) bool {
		return true
	}
	return func() {
		isTerminalWriter = old
	}
}

func captureProcessStderr(t *testing.T, fn func() error) (string, error) {
	t.Helper()

	oldStderr := os.Stderr
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("creating stderr pipe: %v", err)
	}
	os.Stderr = w
	defer func() {
		os.Stderr = oldStderr
	}()

	callErr := fn()
	if err := w.Close(); err != nil {
		t.Fatalf("closing stderr pipe: %v", err)
	}
	out, readErr := io.ReadAll(r)
	if closeErr := r.Close(); closeErr != nil {
		t.Fatalf("closing stderr reader: %v", closeErr)
	}
	if readErr != nil {
		t.Fatalf("reading stderr pipe: %v", readErr)
	}
	return string(out), callErr
}
