// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFundingEventsListCmd(flags *rootFlags) *cobra.Command {
	var flagPageNumber int
	var flagPageSize int
	var flagSortBy string
	var flagSortOrder string
	var flagCreatedFrom string
	var flagCreatedTo string
	var flagDirection string
	var flagEventType string
	var flagTraceNumber string
	var flagSearchText string
	var flagStatus string
	var flagTraceId string
	var flagStatusReason string
	var flagStatusSource string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Retrieves a list of funding events for your account. This endpoint supports advanced sorting and filtering options.",
		Example:     "  straddle-pp-cli funding-events list",
		Annotations: map[string]string{"pp:endpoint": "funding-events.list", "pp:method": "GET", "pp:path": "/v1/funding_events", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort-by") {
				allowedSortBy := []string{"transfer_date", "id", "amount"}
				validSortBy := false
				for _, v := range allowedSortBy {
					if flagSortBy == v {
						validSortBy = true
						break
					}
				}
				if !validSortBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-by", flagSortBy, allowedSortBy)
				}
			}
			if cmd.Flags().Changed("sort-order") {
				allowedSortOrder := []string{"asc", "desc"}
				validSortOrder := false
				for _, v := range allowedSortOrder {
					if flagSortOrder == v {
						validSortOrder = true
						break
					}
				}
				if !validSortOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-order", flagSortOrder, allowedSortOrder)
				}
			}
			if cmd.Flags().Changed("direction") {
				allowedDirection := []string{"deposit", "withdrawal"}
				validDirection := false
				for _, v := range allowedDirection {
					if flagDirection == v {
						validDirection = true
						break
					}
				}
				if !validDirection {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "direction", flagDirection, allowedDirection)
				}
			}
			if cmd.Flags().Changed("event-type") {
				allowedEventType := []string{"charge_deposit", "charge_reversal", "payout_return", "payout_withdrawal"}
				validEventType := false
				for _, v := range allowedEventType {
					if flagEventType == v {
						validEventType = true
						break
					}
				}
				if !validEventType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "event-type", flagEventType, allowedEventType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/funding_events"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "funding-events", path, map[string]string{
				"page_number":   fmt.Sprintf("%v", flagPageNumber),
				"page_size":     fmt.Sprintf("%v", flagPageSize),
				"sort_by":       fmt.Sprintf("%v", flagSortBy),
				"sort_order":    fmt.Sprintf("%v", flagSortOrder),
				"created_from":  fmt.Sprintf("%v", flagCreatedFrom),
				"created_to":    fmt.Sprintf("%v", flagCreatedTo),
				"direction":     fmt.Sprintf("%v", flagDirection),
				"event_type":    fmt.Sprintf("%v", flagEventType),
				"trace_number":  fmt.Sprintf("%v", flagTraceNumber),
				"search_text":   fmt.Sprintf("%v", flagSearchText),
				"status":        fmt.Sprintf("%v", flagStatus),
				"trace_id":      fmt.Sprintf("%v", flagTraceId),
				"status_reason": fmt.Sprintf("%v", flagStatusReason),
				"status_source": fmt.Sprintf("%v", flagStatusSource),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number. Starts at page 1.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "Results page size. Max value: 1000")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "id", "Sort by (one of: transfer_date, id, amount)")
	cmd.Flags().StringVar(&flagSortOrder, "sort-order", "asc", "Sort order (one of: asc, desc)")
	cmd.Flags().StringVar(&flagCreatedFrom, "created-from", "", "The start date of the range to filter by using the `YYYY-MM-DD` format.")
	cmd.Flags().StringVar(&flagCreatedTo, "created-to", "", "The end date of the range to filter by using the `YYYY-MM-DD` format.")
	cmd.Flags().StringVar(&flagDirection, "direction", "", "Direction (one of: deposit, withdrawal)")
	cmd.Flags().StringVar(&flagEventType, "event-type", "", "Event type (one of: charge_deposit, charge_reversal, payout_return, payout_withdrawal)")
	cmd.Flags().StringVar(&flagTraceNumber, "trace-number", "", "Trace number.")
	cmd.Flags().StringVar(&flagSearchText, "search-text", "", "Search text.")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Funding Event status.")
	cmd.Flags().StringVar(&flagTraceId, "trace-id", "", "Trace Id.")
	cmd.Flags().StringVar(&flagStatusReason, "status-reason", "", "Reason for latest payment status change.")
	cmd.Flags().StringVar(&flagStatusSource, "status-source", "", "Source of latest payment status change.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
