// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFundingEventsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "funding-events",
		Short: "Funding events represent all money movement between Straddle and an Account's external bank accounts. They are...",
	}

	cmd.AddCommand(newFundingEventsCreateCmd(flags))
	cmd.AddCommand(newFundingEventsGetCmd(flags))
	cmd.AddCommand(newFundingEventsListCmd(flags))
	return cmd
}
