// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"testing"
)

func TestWrapWithProvenanceUsesTargetEnvelopeForValidJSON(t *testing.T) {
	// PATCH: target-agent-envelope verifies generated provenance-backed reads use the target agent envelope.
	wrapped, err := wrapWithProvenance(json.RawMessage(`[{"id":"cus_123","status":"active"}]`), DataProvenance{Source: "live"})
	if err != nil {
		t.Fatalf("wrapWithProvenance returned error: %v", err)
	}

	var envelope struct {
		SchemaVersion string           `json:"schema_version"`
		Data          []map[string]any `json:"data"`
		Pagination    any              `json:"pagination"`
		Warnings      []string         `json:"warnings"`
		TraceID       any              `json:"trace_id"`
		Error         any              `json:"error"`
		Results       json.RawMessage  `json:"results"`
		Meta          json.RawMessage  `json:"meta"`
	}
	if err := json.Unmarshal(wrapped, &envelope); err != nil {
		t.Fatalf("wrapped output is not valid JSON: %v", err)
	}

	if envelope.SchemaVersion != "1.0" {
		t.Fatalf("schema_version: want 1.0, got %q", envelope.SchemaVersion)
	}
	if len(envelope.Data) != 1 || envelope.Data[0]["id"] != "cus_123" {
		t.Fatalf("data was not embedded as parsed JSON: %#v", envelope.Data)
	}
	if envelope.Pagination != nil {
		t.Fatalf("pagination: want nil, got %#v", envelope.Pagination)
	}
	if len(envelope.Warnings) != 0 {
		t.Fatalf("warnings: want empty array, got %#v", envelope.Warnings)
	}
	if envelope.TraceID != nil {
		t.Fatalf("trace_id: want nil, got %#v", envelope.TraceID)
	}
	if envelope.Error != nil {
		t.Fatalf("error: want nil, got %#v", envelope.Error)
	}
	if envelope.Results != nil {
		t.Fatalf("target envelope should not include results: %s", string(envelope.Results))
	}
	if envelope.Meta != nil {
		t.Fatalf("target envelope should not include meta: %s", string(envelope.Meta))
	}
}

func TestWrapWithProvenanceEmbedsInvalidJSONAsString(t *testing.T) {
	wrapped, err := wrapWithProvenance(json.RawMessage(`not json`), DataProvenance{Source: "local"})
	if err != nil {
		t.Fatalf("wrapWithProvenance returned error: %v", err)
	}

	var envelope struct {
		SchemaVersion string `json:"schema_version"`
		Data          string `json:"data"`
		Warnings      []any  `json:"warnings"`
	}
	if err := json.Unmarshal(wrapped, &envelope); err != nil {
		t.Fatalf("wrapped output is not valid JSON: %v", err)
	}

	if envelope.SchemaVersion != "1.0" {
		t.Fatalf("schema_version: want 1.0, got %q", envelope.SchemaVersion)
	}
	if envelope.Data != "not json" {
		t.Fatalf("data: want raw string payload, got %q", envelope.Data)
	}
	if envelope.Warnings == nil {
		t.Fatalf("warnings should marshal as an empty array, not null")
	}
}
