// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newLinkedBankAccountsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAccountId string
	var bodyBankAccount string
	var bodyDescription string
	var bodyMetadata string
	var bodyPlatformId string
	var bodyPurposes string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Creates a new linked bank account associated with a Straddle account. This endpoint allows you to associate external...",
		Example:     "  straddle-pp-cli linked-bank-accounts create --account-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "linked-bank-accounts.create", "pp:method": "POST", "pp:path": "/v1/linked_bank_accounts"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("account-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "account-id")
				}
				if !cmd.Flags().Changed("bank-account") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "bank-account")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/linked_bank_accounts"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAccountId != "" {
					body["account_id"] = bodyAccountId
				}
				if bodyBankAccount != "" {
					var parsedBankAccount any
					if err := json.Unmarshal([]byte(bodyBankAccount), &parsedBankAccount); err != nil {
						return fmt.Errorf("parsing --bank-account JSON: %w", err)
					}
					body["bank_account"] = parsedBankAccount
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyMetadata != "" {
					var parsedMetadata any
					if err := json.Unmarshal([]byte(bodyMetadata), &parsedMetadata); err != nil {
						return fmt.Errorf("parsing --metadata JSON: %w", err)
					}
					body["metadata"] = parsedMetadata
				}
				if bodyPlatformId != "" {
					body["platform_id"] = bodyPlatformId
				}
				if bodyPurposes != "" {
					var parsedPurposes any
					if err := json.Unmarshal([]byte(bodyPurposes), &parsedPurposes); err != nil {
						return fmt.Errorf("parsing --purposes JSON: %w", err)
					}
					body["purposes"] = parsedPurposes
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "linked-bank-accounts",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The unique identifier of the Straddle account to associate this bank account with.")
	cmd.Flags().StringVar(&bodyBankAccount, "bank-account", "", "Bank account")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Optional description for the bank account.")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Up to 20 additional user-defined key-value pairs. Useful for storing additional information about the linked bank...")
	cmd.Flags().StringVar(&bodyPlatformId, "platform-id", "", "The unique identifier of the Straddle Platform to associate this bank account with.")
	cmd.Flags().StringVar(&bodyPurposes, "purposes", "", "The purposes for the linked bank account.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
