// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newLinkedBankAccountsListCmd(flags *rootFlags) *cobra.Command {
	var flagAccountId string
	var flagPageNumber int
	var flagPageSize int
	var flagSortBy string
	var flagSortOrder string
	var flagLevel string
	var flagPurpose string
	var flagStatus string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Returns a list of bank accounts associated with a specific Straddle account. The linked bank accounts are returned...",
		Example:     "  straddle-pp-cli linked-bank-accounts list",
		Annotations: map[string]string{"pp:endpoint": "linked-bank-accounts.list", "pp:method": "GET", "pp:path": "/v1/linked_bank_accounts", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort-order") {
				allowedSortOrder := []string{"asc", "desc"}
				validSortOrder := false
				for _, v := range allowedSortOrder {
					if flagSortOrder == v {
						validSortOrder = true
						break
					}
				}
				if !validSortOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-order", flagSortOrder, allowedSortOrder)
				}
			}
			if cmd.Flags().Changed("level") {
				allowedLevel := []string{"account", "platform"}
				validLevel := false
				for _, v := range allowedLevel {
					if flagLevel == v {
						validLevel = true
						break
					}
				}
				if !validLevel {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "level", flagLevel, allowedLevel)
				}
			}
			if cmd.Flags().Changed("purpose") {
				allowedPurpose := []string{"charges", "payouts", "billing"}
				validPurpose := false
				for _, v := range allowedPurpose {
					if flagPurpose == v {
						validPurpose = true
						break
					}
				}
				if !validPurpose {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "purpose", flagPurpose, allowedPurpose)
				}
			}
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"created", "onboarding", "active", "rejected", "inactive", "canceled"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/linked_bank_accounts"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "linked-bank-accounts", path, map[string]string{
				"account_id":  fmt.Sprintf("%v", flagAccountId),
				"page_number": fmt.Sprintf("%v", flagPageNumber),
				"page_size":   fmt.Sprintf("%v", flagPageSize),
				"sort_by":     fmt.Sprintf("%v", flagSortBy),
				"sort_order":  fmt.Sprintf("%v", flagSortOrder),
				"level":       fmt.Sprintf("%v", flagLevel),
				"purpose":     fmt.Sprintf("%v", flagPurpose),
				"status":      fmt.Sprintf("%v", flagStatus),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAccountId, "account-id", "", "The unique identifier of the related account.")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number. Starts at page 1.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "Page size. Max value: 1000")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "id", "Sort By.")
	cmd.Flags().StringVar(&flagSortOrder, "sort-order", "asc", "Sort Order. (one of: asc, desc)")
	cmd.Flags().StringVar(&flagLevel, "level", "", "Level (one of: account, platform)")
	cmd.Flags().StringVar(&flagPurpose, "purpose", "", "The purpose of the linked bank accounts to return. Possible values: 'charges', 'payouts', 'billing'. (one of: charges, payouts, billing)")
	cmd.Flags().StringVar(&flagStatus, "status", "", "The status of the linked bank accounts to return. Possible values: 'created', 'onboarding', 'active', 'inactive',... (one of: created, onboarding, active, rejected, inactive, canceled)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
