// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// PATCH: ops-guide covers local-only operational workflow guidance and safety metadata.
func TestOpsGuideNoArgJSONReturnsWorkflowsAndSafety(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "ops", "guide", "--json")
	if err != nil {
		t.Fatalf("ops guide --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("ops guide wrote stderr: %q", stderr)
	}

	var got opsGuideResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("ops guide --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "ops guide" {
		t.Fatalf("command = %q, want ops guide", got.Command)
	}
	wantWorkflows := []string{"reconciliation", "fraud-monitoring", "collections", "reporting", "monitoring"}
	if len(got.AvailableWorkflows) != len(wantWorkflows) {
		t.Fatalf("workflow count = %d, want %d: %#v", len(got.AvailableWorkflows), len(wantWorkflows), got.AvailableWorkflows)
	}
	if gotNames := opsWorkflowNamesFromGuides(got.AvailableWorkflows); strings.Join(gotNames, ",") != strings.Join(wantWorkflows, ",") {
		t.Fatalf("workflow names = %#v, want %#v", gotNames, wantWorkflows)
	}
	if !got.Safety.GuidanceOnly || !got.Safety.RequiresCurrentDocsLookup {
		t.Fatalf("ops guide should be guidance-only and require docs lookup: %#v", got.Safety)
	}
	if got.Safety.MakesAPICalls || got.Safety.CallsDocsEndpoint || got.Safety.ExecutesMCP || got.Safety.PostsWebhook || got.Safety.WritesProduction {
		t.Fatalf("ops guide should not call APIs, docs, MCP, webhooks, or production: %#v", got.Safety)
	}
}

func TestOpsGuideNamedWorkflowsIncludeDocsQueriesAndSteps(t *testing.T) {
	for _, workflow := range []string{"reconciliation", "fraud-monitoring", "collections", "reporting", "monitoring"} {
		t.Run(workflow, func(t *testing.T) {
			stdout, stderr, err := runCLIForDocsTest(t, "ops", "guide", workflow, "--json")
			if err != nil {
				t.Fatalf("ops guide %s --json returned error: %v", workflow, err)
			}
			if stderr != "" {
				t.Fatalf("ops guide %s wrote stderr: %q", workflow, stderr)
			}

			var got opsGuideResponse
			if err := json.Unmarshal([]byte(stdout), &got); err != nil {
				t.Fatalf("ops guide %s --json emitted invalid JSON: %v\n%s", workflow, err, stdout)
			}
			if got.Workflow != workflow || got.WorkflowGuide == nil {
				t.Fatalf("expected %s workflow guide, got %#v", workflow, got)
			}
			if len(got.WorkflowGuide.DocsQueries) == 0 {
				t.Fatalf("%s should include docs lookup query strings", workflow)
			}
			if len(got.WorkflowGuide.NextSteps) == 0 {
				t.Fatalf("%s should include concrete next steps", workflow)
			}
			joined := strings.Join(got.WorkflowGuide.NextSteps, " ")
			if !strings.Contains(joined, "straddle-pp-cli") {
				t.Fatalf("%s steps should reference existing CLI surfaces as guidance, got %#v", workflow, got.WorkflowGuide.NextSteps)
			}
		})
	}
}

func TestOpsGuideInvalidWorkflowReturnsUsageError(t *testing.T) {
	_, _, err := runCLIForDocsTest(t, "ops", "guide", "not-a-workflow", "--json")
	if err == nil {
		t.Fatalf("ops guide should reject invalid workflows")
	}
	var cliErr *cliError
	if !errors.As(err, &cliErr) || cliErr.code != 2 {
		t.Fatalf("invalid workflow should be a usage error, got %#v", err)
	}
	if !strings.Contains(err.Error(), "supported workflows") {
		t.Fatalf("invalid workflow error should list supported workflows, got %v", err)
	}
}

func TestOpsGuideAgentUsesTargetEnvelope(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "ops", "guide", "reconciliation", "--agent")
	if err != nil {
		t.Fatalf("ops guide --agent returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("ops guide --agent wrote stderr: %q", stderr)
	}

	var got struct {
		SchemaVersion string `json:"schema_version"`
		Data          struct {
			Command       string            `json:"command"`
			Workflow      string            `json:"workflow"`
			WorkflowGuide *opsWorkflowGuide `json:"workflow_guide"`
			Safety        opsSafety         `json:"safety"`
		} `json:"data"`
		Warnings []string        `json:"warnings"`
		Results  json.RawMessage `json:"results"`
		Meta     json.RawMessage `json:"meta"`
	}
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("ops guide --agent emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.SchemaVersion != "1.0" {
		t.Fatalf("schema_version: want 1.0, got %q", got.SchemaVersion)
	}
	if got.Data.Command != "ops guide" || got.Data.Workflow != "reconciliation" || got.Data.WorkflowGuide == nil {
		t.Fatalf("agent data should contain reconciliation guide: %#v", got.Data)
	}
	if !got.Data.Safety.GuidanceOnly || got.Data.Safety.MakesAPICalls || got.Data.Safety.CallsDocsEndpoint || got.Data.Safety.ExecutesMCP {
		t.Fatalf("agent safety should remain local guidance only: %#v", got.Data.Safety)
	}
	if got.Warnings == nil {
		t.Fatalf("warnings should be an empty array, not null")
	}
	if got.Results != nil || got.Meta != nil {
		t.Fatalf("target envelope should not include top-level results/meta")
	}
}

func TestOpsGuideRejectsDeliverBeforeDelivery(t *testing.T) {
	target := filepath.Join(t.TempDir(), "ops-guide-delivery.json")

	oldArgs := os.Args
	t.Cleanup(func() {
		os.Args = oldArgs
	})
	os.Args = []string{
		"straddle-pp-cli",
		"ops",
		"guide",
		"--deliver",
		"file:" + target,
	}

	err := Execute()
	if err == nil {
		t.Fatalf("ops guide should reject --deliver")
	}
	if !strings.Contains(err.Error(), "ops guide does not support --deliver") {
		t.Fatalf("error should explain --deliver is unsupported, got %v", err)
	}
	if _, statErr := os.Stat(target); !os.IsNotExist(statErr) {
		t.Fatalf("ops guide should reject --deliver before writing output, stat err=%v", statErr)
	}
}

func opsWorkflowNamesFromGuides(values []opsWorkflowGuide) []string {
	names := make([]string, 0, len(values))
	for _, value := range values {
		names = append(names, value.Name)
	}
	return names
}
