// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPaykeysCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "paykeys",
		Short: "Paykeys are secure tokens that link verified customer identities to their bank accounts. Each Paykey includes...",
	}

	cmd.AddCommand(newPaykeysGetCmd(flags))
	cmd.AddCommand(newPaykeysListCmd(flags))
	cmd.AddCommand(newPaykeysCancelCmd(flags))
	cmd.AddCommand(newPaykeysRefreshBalanceCmd(flags))
	cmd.AddCommand(newPaykeysRefreshReviewCmd(flags))
	cmd.AddCommand(newPaykeysRevealCmd(flags))
	cmd.AddCommand(newPaykeysReviewCmd(flags))
	cmd.AddCommand(newPaykeysUnblockCmd(flags))
	cmd.AddCommand(newPaykeysUnmaskedCmd(flags))
	return cmd
}
