// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFundingEventPaymentsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPageNumber int
	var flagPageSize int
	var flagIncludeMetadata bool
	var flagDefaultPageSize int
	var flagDefaultSort string
	var flagDefaultSortOrder string
	var flagSortBy string
	var flagSortOrder string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "funding-event-payments <id>",
		Short:       "All the payments that made up the funding event",
		Long:        "Shortcut for 'funding-event-payments get'. All the payments that made up the funding event",
		Example:     "  straddle-pp-cli funding-event-payments 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "funding-event-payments.get", "pp:method": "GET", "pp:path": "/v1/funding_event_payments/{id}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("default-sort") {
				allowedDefaultSort := []string{"created_at", "payment_date", "effective_at", "id"}
				validDefaultSort := false
				for _, v := range allowedDefaultSort {
					if flagDefaultSort == v {
						validDefaultSort = true
						break
					}
				}
				if !validDefaultSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "default-sort", flagDefaultSort, allowedDefaultSort)
				}
			}
			if cmd.Flags().Changed("default-sort-order") {
				allowedDefaultSortOrder := []string{"asc", "desc"}
				validDefaultSortOrder := false
				for _, v := range allowedDefaultSortOrder {
					if flagDefaultSortOrder == v {
						validDefaultSortOrder = true
						break
					}
				}
				if !validDefaultSortOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "default-sort-order", flagDefaultSortOrder, allowedDefaultSortOrder)
				}
			}
			if cmd.Flags().Changed("sort-by") {
				allowedSortBy := []string{"created_at", "payment_date", "effective_at", "id"}
				validSortBy := false
				for _, v := range allowedSortBy {
					if flagSortBy == v {
						validSortBy = true
						break
					}
				}
				if !validSortBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-by", flagSortBy, allowedSortBy)
				}
			}
			if cmd.Flags().Changed("sort-order") {
				allowedSortOrder := []string{"asc", "desc"}
				validSortOrder := false
				for _, v := range allowedSortOrder {
					if flagSortOrder == v {
						validSortOrder = true
						break
					}
				}
				if !validSortOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-order", flagSortOrder, allowedSortOrder)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/funding_event_payments/{id}"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "funding-event-payments", path, map[string]string{
				"page_number":        fmt.Sprintf("%v", flagPageNumber),
				"page_size":          fmt.Sprintf("%v", flagPageSize),
				"include_metadata":   fmt.Sprintf("%v", flagIncludeMetadata),
				"default_page_size":  fmt.Sprintf("%v", flagDefaultPageSize),
				"default_sort":       fmt.Sprintf("%v", flagDefaultSort),
				"default_sort_order": fmt.Sprintf("%v", flagDefaultSortOrder),
				"sort_by":            fmt.Sprintf("%v", flagSortBy),
				"sort_order":         fmt.Sprintf("%v", flagSortOrder),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 0, "Results page number. Starts at page 1. Default value: 1")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "Results page size. Default value: 100. Max value: 1000")
	cmd.Flags().BoolVar(&flagIncludeMetadata, "include-metadata", false, "Include the metadata for payments in the returned data.")
	cmd.Flags().IntVar(&flagDefaultPageSize, "default-page-size", 0, "Default page size")
	cmd.Flags().StringVar(&flagDefaultSort, "default-sort", "", "Default sort (one of: created_at, payment_date, effective_at, id)")
	cmd.Flags().StringVar(&flagDefaultSortOrder, "default-sort-order", "asc", "Default sort order (one of: asc, desc)")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "Sort by (one of: created_at, payment_date, effective_at, id)")
	cmd.Flags().StringVar(&flagSortOrder, "sort-order", "asc", "Sort order (one of: asc, desc)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
