// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
)

// PATCH: sandbox-guide covers help-only local sandbox guidance and safety metadata.
func TestSandboxGuideNoArgJSONReturnsScenariosAndPolicy(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "sandbox", "guide", "--json")
	if err != nil {
		t.Fatalf("sandbox guide --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("sandbox guide wrote stderr: %q", stderr)
	}

	var got sandboxGuideResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("sandbox guide --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "sandbox guide" {
		t.Fatalf("command = %q, want sandbox guide", got.Command)
	}
	if len(got.AvailableScenarios) != 8 {
		t.Fatalf("scenario count = %d, want 8: %#v", len(got.AvailableScenarios), got.AvailableScenarios)
	}
	for _, scenario := range got.AvailableScenarios {
		if !scenario.GuidanceOnly || !scenario.SandboxOnly || len(scenario.LiveExecutionRequirements) == 0 {
			t.Fatalf("scenario should carry guidance-only sandbox safety metadata: %#v", scenario)
		}
	}
	if got.Policy.MakesAPICalls || got.Policy.CallsDocsEndpoint || got.Policy.WritesProduction {
		t.Fatalf("sandbox guide should not call APIs, docs, or production: %#v", got.Policy)
	}
	if !got.Policy.SandboxOnly || !got.Policy.GuidanceOnly || !got.Policy.RequiresCurrentDocsLookup {
		t.Fatalf("sandbox guide should be guidance-only, sandbox-only, and require docs lookup: %#v", got.Policy)
	}
	if !strings.Contains(got.DocsLookupInstruction, "docs search") {
		t.Fatalf("docs lookup instruction should mention docs search, got %q", got.DocsLookupInstruction)
	}
}

func TestSandboxGuideAllJSONReturnsScenariosAndPolicy(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "sandbox", "guide", "all", "--json")
	if err != nil {
		t.Fatalf("sandbox guide all --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("sandbox guide all wrote stderr: %q", stderr)
	}

	var got sandboxGuideResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("sandbox guide all --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Scenario != "all" {
		t.Fatalf("scenario = %q, want all", got.Scenario)
	}
	if len(got.AvailableScenarios) != 8 {
		t.Fatalf("scenario count = %d, want 8: %#v", len(got.AvailableScenarios), got.AvailableScenarios)
	}
	if got.ScenarioGuide != nil {
		t.Fatalf("all should list scenarios, not return a single scenario guide: %#v", got.ScenarioGuide)
	}
	if !got.Policy.GuidanceOnly || !got.Policy.SandboxOnly || got.Policy.MakesAPICalls || got.Policy.CallsDocsEndpoint || got.Policy.WritesProduction {
		t.Fatalf("all should preserve local-only sandbox policy: %#v", got.Policy)
	}
}

func TestSandboxGuideACHReturnsJSONIncludesGuidanceAndDocsLookup(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "sandbox", "guide", "ach-returns", "--json")
	if err != nil {
		t.Fatalf("sandbox guide ach-returns --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("sandbox guide ach-returns wrote stderr: %q", stderr)
	}

	var got sandboxGuideResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("sandbox guide ach-returns --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Scenario != "ach-returns" || got.ScenarioGuide == nil {
		t.Fatalf("expected ach-returns scenario guide, got %#v", got)
	}
	if !strings.Contains(got.ScenarioGuide.DocsQuery, "ACH returns") {
		t.Fatalf("ACH return guide should include a docs lookup query, got %q", got.ScenarioGuide.DocsQuery)
	}
	if !got.ScenarioGuide.GuidanceOnly || !got.ScenarioGuide.SandboxOnly {
		t.Fatalf("ACH return guide should be marked guidance-only and sandbox-only: %#v", got.ScenarioGuide)
	}
	if !containsString(got.ScenarioGuide.ReturnCodes, "R29") {
		t.Fatalf("ACH return guide should include R29, got %#v", got.ScenarioGuide.ReturnCodes)
	}
	if !strings.Contains(strings.Join(got.ScenarioGuide.Steps, " "), "fraud") {
		t.Fatalf("ACH return guide should explain fraud-return impact, got %#v", got.ScenarioGuide.Steps)
	}
	if !got.Policy.RequiresCurrentDocsLookup || got.Policy.MakesAPICalls || got.Policy.CallsDocsEndpoint {
		t.Fatalf("ACH guide should require docs lookup without doing one: %#v", got.Policy)
	}
}

func TestSandboxGuideInvalidScenarioReturnsUsageError(t *testing.T) {
	_, _, err := runCLIForDocsTest(t, "sandbox", "guide", "not-a-scenario", "--json")
	if err == nil {
		t.Fatalf("sandbox guide should reject invalid scenarios")
	}
	var cliErr *cliError
	if !errors.As(err, &cliErr) || cliErr.code != 2 {
		t.Fatalf("invalid scenario should be a usage error, got %#v", err)
	}
	if !strings.Contains(err.Error(), "supported scenarios") {
		t.Fatalf("invalid scenario error should list supported scenarios, got %v", err)
	}
}

func TestSandboxGuideAgentUsesTargetEnvelope(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "sandbox", "guide", "--agent")
	if err != nil {
		t.Fatalf("sandbox guide --agent returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("sandbox guide --agent wrote stderr: %q", stderr)
	}

	var got struct {
		SchemaVersion string `json:"schema_version"`
		Data          struct {
			Command            string            `json:"command"`
			AvailableScenarios []sandboxScenario `json:"available_scenarios"`
			Policy             sandboxPolicy     `json:"policy"`
		} `json:"data"`
		Warnings []string        `json:"warnings"`
		Results  json.RawMessage `json:"results"`
		Meta     json.RawMessage `json:"meta"`
	}
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("sandbox guide --agent emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.SchemaVersion != "1.0" {
		t.Fatalf("schema_version: want 1.0, got %q", got.SchemaVersion)
	}
	if got.Data.Command != "sandbox guide" || len(got.Data.AvailableScenarios) != 8 {
		t.Fatalf("agent data should contain sandbox guide scenarios: %#v", got.Data)
	}
	if !got.Data.Policy.GuidanceOnly || got.Data.Policy.MakesAPICalls {
		t.Fatalf("agent policy should remain local guidance only: %#v", got.Data.Policy)
	}
	if got.Warnings == nil {
		t.Fatalf("warnings should be an empty array, not null")
	}
	if got.Results != nil || got.Meta != nil {
		t.Fatalf("target envelope should not include top-level results/meta")
	}
}

func TestSandboxGuideRejectsDeliverBeforeDelivery(t *testing.T) {
	var deliveryCount int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		deliveryCount++
		t.Fatalf("sandbox guide should reject --deliver before posting delivery output")
	}))
	defer server.Close()

	oldArgs := os.Args
	t.Cleanup(func() {
		os.Args = oldArgs
	})
	os.Args = []string{
		"straddle-pp-cli",
		"sandbox",
		"guide",
		"--deliver",
		"webhook:" + server.URL,
	}

	err := Execute()
	if err == nil {
		t.Fatalf("sandbox guide should reject --deliver")
	}
	if !strings.Contains(err.Error(), "sandbox guide does not support --deliver") {
		t.Fatalf("error should explain --deliver is unsupported, got %v", err)
	}
	if deliveryCount != 0 {
		t.Fatalf("delivery request count: want 0, got %d", deliveryCount)
	}
}

func containsString(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
