// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCH: setup-check tests the local-only setup readiness preflight.

package cli

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/zalando/go-keyring"
	"straddle-pp-cli/internal/config"
)

func runCLIForSetupTest(t *testing.T, args ...string) (string, string, error) {
	t.Helper()

	cmd := RootCmd()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)
	cmd.SetArgs(args)

	err := cmd.Execute()
	return stdout.String(), stderr.String(), err
}

func setupTestHome(t *testing.T) string {
	t.Helper()

	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("STRADDLE_CONFIG", "")
	t.Setenv("STRADDLE_BASE_URL", "")
	t.Setenv("STRADDLE_TOKEN", "")
	return home
}

func writeSetupConfig(t *testing.T, home string, body string) string {
	t.Helper()

	path := filepath.Join(home, ".config", "straddle-pp-cli", "config.toml")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("creating config dir: %v", err)
	}
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("writing config: %v", err)
	}
	return path
}

func TestSetupCheckJSONLocalOnlyNoSecrets(t *testing.T) {
	home := setupTestHome(t)
	configPath := writeSetupConfig(t, home, "base_url = \"https://sandbox.straddle.com\"\ntoken = \"secret-token-value\"\n")

	stdout, stderr, err := runCLIForSetupTest(t, "setup", "check", "--json", "--config", configPath)
	if err != nil {
		t.Fatalf("setup check --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("setup check --json wrote stderr: %q", stderr)
	}
	if strings.Contains(stdout, "secret-token-value") {
		t.Fatalf("setup check --json leaked token value:\n%s", stdout)
	}

	var got setupCheckResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "setup check" || !got.LocalPreview {
		t.Fatalf("setup command metadata mismatch: %#v", got)
	}
	if got.Config.Path != configPath || !got.Config.Loadable || !got.Config.Exists {
		t.Fatalf("config status mismatch: %#v", got.Config)
	}
	if got.Config.BaseURL != "https://sandbox.straddle.com" || got.Config.BaseURLSource != "config" {
		t.Fatalf("base_url status mismatch: %#v", got.Config)
	}
	if got.Environment.Classification != "sandbox" {
		t.Fatalf("environment classification = %q, want sandbox", got.Environment.Classification)
	}
	if !got.Auth.Configured || got.Auth.Source != "config" {
		t.Fatalf("auth source status mismatch: %#v", got.Auth)
	}
	if got.Safety["calls_straddle_api"] || got.Safety["calls_docs_endpoint"] || got.Safety["executes_mcp"] || got.Safety["posts_webhook"] || got.Safety["writes_production"] {
		t.Fatalf("setup check must report local-only safety flags, got %#v", got.Safety)
	}
	if !got.DocsSearch.LocalCommandAvailable || !got.SandboxGuide.LocalCommandAvailable {
		t.Fatalf("local companion command readiness missing: docs=%#v sandbox=%#v", got.DocsSearch, got.SandboxGuide)
	}
	for _, step := range []string{
		"straddle-pp-cli auth set-token --stdin",
		"straddle-pp-cli docs search \"charges\" --source commands --json",
		"straddle-pp-cli sandbox guide --json",
	} {
		if !containsSetupString(got.NextSteps, step) {
			t.Fatalf("next_steps missing %q: %#v", step, got.NextSteps)
		}
	}
	if !containsSetupString(got.NextSteps, "straddle-pp-cli doctor --json") {
		t.Fatalf("sandbox next_steps should include doctor: %#v", got.NextSteps)
	}
}

func TestSetupCheckNoConfigLeavesBaseURLUnsetAndDoesNotCreateProfileStore(t *testing.T) {
	home := setupTestHome(t)

	stdout, stderr, err := runCLIForSetupTest(t, "setup", "check", "--json")
	if err != nil {
		t.Fatalf("setup check no config returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("setup check no config wrote stderr: %q", stderr)
	}
	if strings.Contains(stdout, "https://sandbox.straddle.com") {
		t.Fatalf("setup check no config leaked generated sandbox default:\n%s", stdout)
	}

	var got setupCheckResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check no config emitted invalid JSON: %v\n%s", err, stdout)
	}
	wantConfigPath := filepath.Join(home, ".config", "straddle-pp-cli", "config.toml")
	if got.Config.Path != wantConfigPath || got.Config.Exists || !got.Config.Loadable {
		t.Fatalf("config status mismatch: %#v", got.Config)
	}
	if got.Config.BaseURL != "" || got.Config.BaseURLSource != "unset" {
		t.Fatalf("base_url status mismatch: %#v", got.Config)
	}
	if got.Environment.Classification != "unset" || got.Environment.Source != "unset" || got.Environment.BaseURL != "" {
		t.Fatalf("environment status mismatch: %#v", got.Environment)
	}
	if got.Profiles.Count != 0 || len(got.Profiles.Names) != 0 {
		t.Fatalf("profiles should be empty without store, got %#v", got.Profiles)
	}
	if _, err := os.Stat(filepath.Join(home, ".straddle-pp-cli")); !os.IsNotExist(err) {
		t.Fatalf("setup check should not create profile store directory, stat err=%v", err)
	}
}

func TestSetupCheckWithMissingProfileDoesNotCreateProfileStore(t *testing.T) {
	home := setupTestHome(t)

	stdout, stderr, err := runCLIForSetupTest(t, "--profile", "ghost", "setup", "check", "--json")
	if err != nil {
		t.Fatalf("setup check with missing profile returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("setup check with missing profile wrote stderr: %q", stderr)
	}
	if strings.Contains(stdout, "profile") && strings.Contains(stdout, "not found") {
		t.Fatalf("setup check should not fail on missing profile, got output:\n%s", stdout)
	}

	var got setupCheckResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check with missing profile emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "setup check" {
		t.Fatalf("command = %q, want setup check", got.Command)
	}
	if got.Profiles.Count != 0 || len(got.Profiles.Names) != 0 {
		t.Fatalf("profiles should be empty without store, got %#v", got.Profiles)
	}
	if _, err := os.Stat(filepath.Join(home, ".straddle-pp-cli")); !os.IsNotExist(err) {
		t.Fatalf("setup check with missing profile should not create profile store directory, stat err=%v", err)
	}
}

func TestSetupCheckInvalidConfigReturnsStructuredReadiness(t *testing.T) {
	home := setupTestHome(t)
	configPath := writeSetupConfig(t, home, "base_url = \"https://sandbox.straddle.com\"\ntoken = \"secret-token-value\"\ninvalid = [\n")

	stdout, stderr, err := runCLIForSetupTest(t, "setup", "check", "--json", "--config", configPath)
	if err != nil {
		t.Fatalf("setup check invalid config returned hard error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("setup check invalid config wrote stderr: %q", stderr)
	}
	if strings.Contains(stdout, "secret-token-value") {
		t.Fatalf("setup check invalid config leaked token value:\n%s", stdout)
	}

	var got setupCheckResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check invalid config emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Config.Path != configPath || !got.Config.Exists || got.Config.Loadable {
		t.Fatalf("invalid config status mismatch: %#v", got.Config)
	}
	if got.Config.BaseURL != "" || got.Config.BaseURLSource != "unset" {
		t.Fatalf("invalid config base_url status mismatch: %#v", got.Config)
	}
	if got.Environment.Classification != "unset" || got.Environment.Source != "unset" || got.Environment.BaseURL != "" {
		t.Fatalf("invalid config environment status mismatch: %#v", got.Environment)
	}
}

func TestSetupCheckSandboxClassification(t *testing.T) {
	home := setupTestHome(t)
	configPath := writeSetupConfig(t, home, "base_url = \"https://sandbox.straddle.com\"\n")

	stdout, _, err := runCLIForSetupTest(t, "setup", "check", "--json", "--config", configPath)
	if err != nil {
		t.Fatalf("setup check sandbox returned error: %v", err)
	}
	var got setupCheckResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check sandbox emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Environment.Classification != "sandbox" {
		t.Fatalf("classification = %q, want sandbox", got.Environment.Classification)
	}
}

func TestSetupCheckSpoofedStraddleHostsClassifyCustom(t *testing.T) {
	for _, tc := range []struct {
		name    string
		baseURL string
	}{
		{name: "sandbox", baseURL: "https://sandbox.straddle.com.example"},
		{name: "production", baseURL: "https://production.straddle.com.example"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			home := setupTestHome(t)
			configPath := writeSetupConfig(t, home, "base_url = \""+tc.baseURL+"\"\n")

			stdout, _, err := runCLIForSetupTest(t, "setup", "check", "--json", "--config", configPath)
			if err != nil {
				t.Fatalf("setup check spoofed host returned error: %v", err)
			}

			var got setupCheckResponse
			if err := json.Unmarshal([]byte(stdout), &got); err != nil {
				t.Fatalf("setup check spoofed host emitted invalid JSON: %v\n%s", err, stdout)
			}
			if got.Environment.Classification != "custom" {
				t.Fatalf("classification = %q, want custom", got.Environment.Classification)
			}
		})
	}
}

func TestSetupCheckProductionClassificationIsLocalOnly(t *testing.T) {
	home := setupTestHome(t)
	configPath := writeSetupConfig(t, home, "base_url = \"https://production.straddle.com\"\n")

	stdout, stderr, err := runCLIForSetupTest(t, "setup", "check", "--json", "--config", configPath)
	if err != nil {
		t.Fatalf("setup check production returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("setup check production wrote stderr: %q", stderr)
	}

	var got setupCheckResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check production emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Environment.Classification != "production" {
		t.Fatalf("classification = %q, want production", got.Environment.Classification)
	}
	if got.Safety["calls_straddle_api"] || got.Safety["writes_production"] {
		t.Fatalf("production classification must stay local-only, got safety %#v", got.Safety)
	}
	if containsSetupString(got.NextSteps, "straddle-pp-cli doctor --json") {
		t.Fatalf("production next_steps must not include unqualified doctor: %#v", got.NextSteps)
	}
}

func TestSetupCheckCustomClassificationDoesNotSuggestDoctor(t *testing.T) {
	home := setupTestHome(t)
	configPath := writeSetupConfig(t, home, "base_url = \"https://api.example.test\"\n")

	stdout, stderr, err := runCLIForSetupTest(t, "setup", "check", "--json", "--config", configPath)
	if err != nil {
		t.Fatalf("setup check custom returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("setup check custom wrote stderr: %q", stderr)
	}

	var got setupCheckResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check custom emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Environment.Classification != "custom" {
		t.Fatalf("classification = %q, want custom", got.Environment.Classification)
	}
	if containsSetupString(got.NextSteps, "straddle-pp-cli doctor --json") {
		t.Fatalf("custom next_steps must not include unqualified doctor: %#v", got.NextSteps)
	}
}

func TestSetupCheckAgentUsesTargetEnvelope(t *testing.T) {
	home := setupTestHome(t)
	configPath := writeSetupConfig(t, home, "base_url = \"https://sandbox.straddle.com\"\n")

	stdout, stderr, err := runCLIForSetupTest(t, "setup", "check", "--agent", "--config", configPath)
	if err != nil {
		t.Fatalf("setup check --agent returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("setup check --agent wrote stderr: %q", stderr)
	}

	var got struct {
		SchemaVersion string             `json:"schema_version"`
		Data          setupCheckResponse `json:"data"`
		Warnings      []string           `json:"warnings"`
		TraceID       any                `json:"trace_id"`
		Error         any                `json:"error"`
	}
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check --agent emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.SchemaVersion != "1.0" {
		t.Fatalf("schema_version = %q, want 1.0", got.SchemaVersion)
	}
	if got.Data.Command != "setup check" || got.Data.Environment.Classification != "sandbox" {
		t.Fatalf("agent data mismatch: %#v", got.Data)
	}
	if got.Warnings == nil || got.TraceID != nil || got.Error != nil {
		t.Fatalf("target envelope metadata mismatch: warnings=%#v trace=%#v error=%#v", got.Warnings, got.TraceID, got.Error)
	}
}

func TestSetupCheckClassifiesAvailableKeychainAuth(t *testing.T) {
	keyring.MockInit()
	home := setupTestHome(t)
	token := "setup-keychain-secret"
	if err := keyring.Set(config.DefaultKeychainService, config.DefaultKeychainAccount, token); err != nil {
		t.Fatalf("set keychain token: %v", err)
	}
	configPath := writeSetupConfig(t, home, "base_url = \"https://sandbox.straddle.com\"\nkeychain_service = \""+config.DefaultKeychainService+"\"\nkeychain_account = \""+config.DefaultKeychainAccount+"\"\n")

	stdout, stderr, err := runCLIForSetupTest(t, "setup", "check", "--json", "--config", configPath)
	if err != nil {
		t.Fatalf("setup check keychain returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("setup check keychain wrote stderr: %q", stderr)
	}
	if strings.Contains(stdout, token) {
		t.Fatalf("setup check leaked keychain token:\n%s", stdout)
	}

	var got setupCheckResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check keychain emitted invalid JSON: %v\n%s", err, stdout)
	}
	if !got.Auth.Configured || got.Auth.Source != "keychain" {
		t.Fatalf("setup check auth mismatch: %#v", got.Auth)
	}
}

func TestSetupCheckClassifiesUnavailableKeychainAuth(t *testing.T) {
	keyring.MockInit()
	home := setupTestHome(t)
	configPath := writeSetupConfig(t, home, "base_url = \"https://sandbox.straddle.com\"\nkeychain_service = \""+config.DefaultKeychainService+"\"\nkeychain_account = \""+config.DefaultKeychainAccount+"\"\n")

	stdout, stderr, err := runCLIForSetupTest(t, "setup", "check", "--json", "--config", configPath)
	if err != nil {
		t.Fatalf("setup check missing keychain returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("setup check missing keychain wrote stderr: %q", stderr)
	}

	var got setupCheckResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("setup check missing keychain emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Auth.Configured || got.Auth.Source != "keychain_unavailable" {
		t.Fatalf("setup check unavailable keychain auth mismatch: %#v", got.Auth)
	}
}

func TestSetupCheckRejectsDeliverBeforeDelivery(t *testing.T) {
	var deliveryCount int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		deliveryCount++
		t.Fatalf("setup check should reject --deliver before posting delivery output")
	}))
	defer server.Close()

	home := setupTestHome(t)
	configPath := writeSetupConfig(t, home, "base_url = \"https://sandbox.straddle.com\"\n")

	oldArgs := os.Args
	t.Cleanup(func() {
		os.Args = oldArgs
	})
	os.Args = []string{
		"straddle-pp-cli",
		"setup",
		"check",
		"--config",
		configPath,
		"--deliver",
		"webhook:" + server.URL,
	}

	err := Execute()
	if err == nil {
		t.Fatalf("setup check should reject --deliver")
	}
	if !strings.Contains(err.Error(), "setup check does not support --deliver") {
		t.Fatalf("error should explain --deliver is unsupported, got %v", err)
	}
	if deliveryCount != 0 {
		t.Fatalf("delivery request count: want 0, got %d", deliveryCount)
	}
}

func containsSetupString(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
