// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCH: shipcheck-local covers local executable public-preview readiness verification.

package cli

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestShipcheckLocalJSONSuccessWithoutMCP(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "shipcheck", "local", "--json")
	if err != nil {
		t.Fatalf("shipcheck local --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("shipcheck local wrote stderr: %q", stderr)
	}

	var got shipcheckLocalResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("shipcheck local --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "shipcheck local" || !got.Passed {
		t.Fatalf("wrong shipcheck response: %#v", got)
	}
	if len(got.Checks) < 4 {
		t.Fatalf("shipcheck should report concrete checks, got %#v", got.Checks)
	}
	if !got.Safety.LocalOnly || !got.Safety.CredentialFree || !got.Safety.NoAPICalls || !got.Safety.NoDocsEndpointCalls || !got.Safety.NoProductionWrites {
		t.Fatalf("shipcheck safety should prove local credential-free execution: %#v", got.Safety)
	}
	if got.Safety.ChildProcessExecuted || got.Safety.ChildEnvAllowlisted || got.Safety.ChildProcessSandboxed {
		t.Fatalf("shipcheck without --mcp-binary should not claim child-process proof: %#v", got.Safety)
	}
	if got.Safety.CallsGitHub || got.Safety.CallsNPM || got.Safety.CallsHomebrew || got.Safety.Publishes || got.Safety.Signs || got.Safety.Notarizes || got.Safety.ReadsSecrets {
		t.Fatalf("shipcheck safety should reject external release or secret surfaces: %#v", got.Safety)
	}
	if strings.Contains(strings.ToLower(stdout), "bearer ") || strings.Contains(stdout, "STRADDLE_TOKEN=") || strings.Contains(stdout, "sk_live") || strings.Contains(stdout, "sk_test") {
		t.Fatalf("shipcheck local should not emit token literals:\n%s", stdout)
	}
}

func TestShipcheckLocalCommandTreeRequiredPaths(t *testing.T) {
	payload, err := buildShipcheckLocalResponse(RootCmd(), "")
	if err != nil {
		t.Fatalf("buildShipcheckLocalResponse returned error: %v", err)
	}
	check := shipcheckCheckByName(t, payload.Checks, "command_tree")
	if !check.Passed {
		t.Fatalf("command_tree check failed: %#v", check)
	}
	for _, want := range requiredShipcheckCommandPaths() {
		if !containsString(check.Evidence, want) {
			t.Fatalf("command_tree evidence missing %q: %#v", want, check.Evidence)
		}
	}
}

func TestShipcheckLocalWorkflowNames(t *testing.T) {
	payload, err := buildShipcheckLocalResponse(RootCmd(), "")
	if err != nil {
		t.Fatalf("buildShipcheckLocalResponse returned error: %v", err)
	}
	check := shipcheckCheckByName(t, payload.Checks, "workflow_plans")
	if !check.Passed {
		t.Fatalf("workflow_plans check failed: %#v", check)
	}
	for _, want := range []string{"reconciliation", "fraud-monitoring", "collections", "reporting", "monitoring"} {
		if !containsString(check.Evidence, want) {
			t.Fatalf("workflow_plans evidence missing %q: %#v", want, check.Evidence)
		}
	}
}

func TestShipcheckLocalFakeMCPSuccess(t *testing.T) {
	binary := writeFakeMCPBinary(t, requiredShipcheckMCPTools())

	stdout, stderr, err := runCLIForDocsTest(t, "shipcheck", "local", "--mcp-binary", binary, "--json")
	if err != nil {
		t.Fatalf("shipcheck local fake MCP returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("shipcheck local fake MCP wrote stderr: %q", stderr)
	}

	var got shipcheckLocalResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("shipcheck local fake MCP emitted invalid JSON: %v\n%s", err, stdout)
	}
	if !got.Passed {
		t.Fatalf("shipcheck local fake MCP should pass: %#v", got)
	}
	if !got.Safety.ChildProcessExecuted || !got.Safety.ChildEnvAllowlisted || got.Safety.ChildProcessSandboxed {
		t.Fatalf("shipcheck local fake MCP should state child process was executed with allowlisted env and no sandbox: %#v", got.Safety)
	}
	if got.Safety.NoAPICalls || got.Safety.NoSecretsRead || got.Safety.NoGitHubCalls || got.Safety.NoNPMCalls || got.Safety.NoHomebrewCalls {
		t.Fatalf("shipcheck local fake MCP should not overclaim child-process behavior: %#v", got.Safety)
	}
	check := shipcheckCheckByName(t, got.Checks, "mcp_tools")
	if !check.Passed {
		t.Fatalf("mcp_tools should pass: %#v", check)
	}
	for _, want := range requiredShipcheckMCPTools() {
		if !containsString(check.Evidence, want) {
			t.Fatalf("mcp_tools evidence missing %q: %#v", want, check.Evidence)
		}
	}
	if strings.Contains(stdout, binary) {
		t.Fatalf("shipcheck local should not print local binary paths:\n%s", stdout)
	}
}

func TestShipcheckLocalFakeMCPMissingRequiredToolFails(t *testing.T) {
	tools := []string{}
	for _, name := range requiredShipcheckMCPTools() {
		if name != "release_plan" {
			tools = append(tools, name)
		}
	}
	binary := writeFakeMCPBinary(t, tools)

	stdout, _, err := runCLIForDocsTest(t, "shipcheck", "local", "--mcp-binary", binary, "--json")
	if err == nil {
		t.Fatalf("shipcheck local should fail when MCP tool is missing")
	}
	if !strings.Contains(err.Error(), "release_plan") {
		t.Fatalf("error should mention missing release_plan, got %v", err)
	}
	var got shipcheckLocalResponse
	if unmarshalErr := json.Unmarshal([]byte(stdout), &got); unmarshalErr != nil {
		t.Fatalf("failed shipcheck should still emit JSON: %v\n%s", unmarshalErr, stdout)
	}
	if got.Passed {
		t.Fatalf("shipcheck should not pass with missing MCP tool: %#v", got)
	}
	check := shipcheckCheckByName(t, got.Checks, "mcp_tools")
	if check.Passed || !strings.Contains(check.Note, "release_plan") {
		t.Fatalf("mcp_tools should record missing release_plan: %#v", check)
	}
}

func TestShipcheckLocalRejectsDeliverBeforeDelivery(t *testing.T) {
	target := filepath.Join(t.TempDir(), "shipcheck-delivery.json")
	home := t.TempDir()
	t.Setenv("HOME", home)

	oldArgs := os.Args
	t.Cleanup(func() {
		os.Args = oldArgs
	})
	os.Args = []string{
		"straddle-pp-cli",
		"shipcheck",
		"local",
		"--deliver",
		"file:" + target,
		"--profile",
		"missing-profile",
	}

	err := Execute()
	if err == nil {
		t.Fatalf("shipcheck local should reject --deliver")
	}
	if !strings.Contains(err.Error(), "shipcheck local does not support --deliver") {
		t.Fatalf("error should explain --deliver is unsupported, got %v", err)
	}
	if _, statErr := os.Stat(target); !os.IsNotExist(statErr) {
		t.Fatalf("shipcheck local should reject --deliver before writing output, stat err=%v", statErr)
	}
	if _, statErr := os.Stat(filepath.Join(home, ".straddle-pp-cli")); !os.IsNotExist(statErr) {
		t.Fatalf("shipcheck local should reject --deliver before loading profile state, stat err=%v", statErr)
	}
}

func TestShipcheckLocalRejectsSecretLiteralMCPBinary(t *testing.T) {
	_, _, err := runCLIForDocsTest(t, "shipcheck", "local", "--mcp-binary", "straddle-pp-mcp --token sk_test_fixture", "--json")
	if err == nil {
		t.Fatalf("shipcheck local should reject token literals in --mcp-binary")
	}
	var cliErr *cliError
	if !errors.As(err, &cliErr) || cliErr.code != 2 {
		t.Fatalf("token literal rejection should be a usage error, got %#v", err)
	}
	if !strings.Contains(strings.ToLower(err.Error()), "token") {
		t.Fatalf("error should mention token literal rejection, got %v", err)
	}
}

func shipcheckCheckByName(t *testing.T, checks []shipcheckCheck, name string) shipcheckCheck {
	t.Helper()
	for _, check := range checks {
		if check.Name == name {
			return check
		}
	}
	t.Fatalf("missing check %q in %#v", name, checks)
	return shipcheckCheck{}
}
