// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCH: shipcheck-local adds a local executable verifier for public-preview readiness.

package cli

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os/exec"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

type shipcheckSafety struct {
	LocalOnly              bool `json:"local_only"`
	CredentialFree         bool `json:"credential_free"`
	NoAPICalls             bool `json:"no_api_calls"`
	NoDocsEndpointCalls    bool `json:"no_docs_endpoint_calls"`
	NoGitHubCalls          bool `json:"no_github_calls"`
	NoNPMCalls             bool `json:"no_npm_calls"`
	NoHomebrewCalls        bool `json:"no_homebrew_calls"`
	NoPublishing           bool `json:"no_publishing"`
	NoSigning              bool `json:"no_signing"`
	NoNotarization         bool `json:"no_notarization"`
	NoSecretsRead          bool `json:"no_secrets_read"`
	NoProductionWrites     bool `json:"no_production_writes"`
	ReadOnlyMCP            bool `json:"read_only_mcp"`
	ChildProcessExecuted   bool `json:"child_process_executed"`
	ChildProcessSandboxed  bool `json:"child_process_sandboxed"`
	ChildEnvAllowlisted    bool `json:"child_env_allowlisted"`
	CallsGitHub            bool `json:"calls_github"`
	CallsNPM               bool `json:"calls_npm"`
	CallsHomebrew          bool `json:"calls_homebrew"`
	Publishes              bool `json:"publishes"`
	Signs                  bool `json:"signs"`
	Notarizes              bool `json:"notarizes"`
	ReadsSecrets           bool `json:"reads_secrets"`
	WritesProduction       bool `json:"writes_production"`
	OptionalMCPBinaryProof bool `json:"optional_mcp_binary_proof"`
}

type shipcheckCheck struct {
	Name     string   `json:"name"`
	Passed   bool     `json:"passed"`
	Note     string   `json:"note,omitempty"`
	Evidence []string `json:"evidence,omitempty"`
}

type shipcheckLocalResponse struct {
	Command string           `json:"command"`
	Passed  bool             `json:"passed"`
	Checks  []shipcheckCheck `json:"checks"`
	Safety  shipcheckSafety  `json:"safety"`
}

func newShipcheckCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "shipcheck",
		Short: "Verify local public-preview readiness",
		Long:  "Verify local public-preview readiness without credentials, service calls, publishing, signing, notarization, or production writes.",
	}
	cmd.AddCommand(newShipcheckLocalCmd(flags))
	return cmd
}

func newShipcheckLocalCmd(flags *rootFlags) *cobra.Command {
	var mcpBinary string
	cmd := &cobra.Command{
		Use:   "local",
		Short: "Run local public-preview readiness checks",
		Long: `Run local public-preview readiness checks.

This verifier inspects the in-process CLI command tree, local workflow plan names, local docs command-search indexing, and optional local stdio MCP tools/list. It does not call Straddle APIs, docs endpoints, GitHub, npm, Homebrew, publish, sign, notarize, read secrets, or write production.`,
		Example: `  straddle-pp-cli shipcheck local
  straddle-pp-cli shipcheck local --json
  straddle-pp-cli shipcheck local --mcp-binary ./bin/straddle-pp-mcp --agent`,
		Annotations: map[string]string{
			"mcp:read-only":              "true",
			localOnlyNoPreloadAnnotation: "true",
		},
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if flags.deliverSpec != "" {
				return usageErr(fmt.Errorf("shipcheck local does not support --deliver; use normal stdout, JSON, or agent output"))
			}
			payload, checkErr := buildShipcheckLocalResponse(cmd.Root(), mcpBinary)
			if renderErr := renderShipcheckLocalResponse(cmd, flags, payload); renderErr != nil {
				return renderErr
			}
			if checkErr != nil {
				return checkErr
			}
			if !payload.Passed {
				return apiErr(fmt.Errorf("shipcheck local failed"))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&mcpBinary, "mcp-binary", "", "Optional path or command name for a local stdio straddle-pp-mcp binary to verify with initialize plus tools/list")
	return cmd
}

func buildShipcheckLocalResponse(root *cobra.Command, mcpBinary string) (shipcheckLocalResponse, error) {
	payload := shipcheckLocalResponse{
		Command: "shipcheck local",
		Safety:  defaultShipcheckSafety(strings.TrimSpace(mcpBinary) != ""),
	}
	payload.Checks = append(payload.Checks,
		checkShipcheckCommandTree(root),
		checkShipcheckWorkflowPlans(),
		checkShipcheckDocsCommandSearch(),
		checkShipcheckSafetyContract(),
	)

	var firstErr error
	if strings.TrimSpace(mcpBinary) != "" {
		check, err := checkShipcheckMCPTools(root, mcpBinary)
		payload.Checks = append(payload.Checks, check)
		if err != nil {
			firstErr = err
		}
	}

	payload.Passed = true
	for _, check := range payload.Checks {
		if !check.Passed {
			payload.Passed = false
			if firstErr == nil {
				firstErr = apiErr(fmt.Errorf("shipcheck local failed check %q: %s", check.Name, check.Note))
			}
		}
	}
	return payload, firstErr
}

func defaultShipcheckSafety(hasMCPBinary bool) shipcheckSafety {
	return shipcheckSafety{
		LocalOnly:              true,
		CredentialFree:         true,
		NoAPICalls:             !hasMCPBinary,
		NoDocsEndpointCalls:    !hasMCPBinary,
		NoGitHubCalls:          !hasMCPBinary,
		NoNPMCalls:             !hasMCPBinary,
		NoHomebrewCalls:        !hasMCPBinary,
		NoPublishing:           true,
		NoSigning:              true,
		NoNotarization:         true,
		NoSecretsRead:          !hasMCPBinary,
		NoProductionWrites:     true,
		ReadOnlyMCP:            true,
		ChildProcessExecuted:   hasMCPBinary,
		ChildProcessSandboxed:  false,
		ChildEnvAllowlisted:    hasMCPBinary,
		CallsGitHub:            false,
		CallsNPM:               false,
		CallsHomebrew:          false,
		Publishes:              false,
		Signs:                  false,
		Notarizes:              false,
		ReadsSecrets:           false,
		WritesProduction:       false,
		OptionalMCPBinaryProof: hasMCPBinary,
	}
}

func checkShipcheckCommandTree(root *cobra.Command) shipcheckCheck {
	check := shipcheckCheck{Name: "command_tree", Passed: true}
	for _, path := range requiredShipcheckCommandPaths() {
		if !shipcheckCommandPathExists(root, path) {
			check.Passed = false
			check.Note = "missing required command path(s)"
			check.Evidence = append(check.Evidence, "missing: "+path)
			continue
		}
		check.Evidence = append(check.Evidence, path)
	}
	if check.Passed {
		check.Note = "required public-preview and read command paths are present"
	}
	return check
}

func requiredShipcheckCommandPaths() []string {
	return []string{
		"about",
		"setup check",
		"docs search",
		"sandbox guide",
		"workflow plan",
		"release plan",
		"credentials plan",
		"mcp config",
		"smoke plan",
		"smoke run",
		"customers list",
		"payments",
		"charges get",
		"payouts get",
		"funding-events list",
	}
}

func shipcheckCommandPathExists(root *cobra.Command, path string) bool {
	if root == nil {
		return false
	}
	cmd, _, err := root.Find(strings.Fields(path))
	return err == nil && cmd != nil && cmd.Runnable()
}

func checkShipcheckWorkflowPlans() shipcheckCheck {
	required := []string{"reconciliation", "fraud-monitoring", "collections", "reporting", "monitoring"}
	available := map[string]bool{}
	for _, name := range workflowPlanNames() {
		available[name] = true
	}
	check := shipcheckCheck{Name: "workflow_plans", Passed: true}
	for _, name := range required {
		if !available[name] {
			check.Passed = false
			check.Note = "missing required workflow plan(s)"
			check.Evidence = append(check.Evidence, "missing: "+name)
			continue
		}
		check.Evidence = append(check.Evidence, name)
	}
	if check.Passed {
		check.Note = "required workflow plans are present"
	}
	return check
}

func checkShipcheckDocsCommandSearch() shipcheckCheck {
	check := shipcheckCheck{Name: "docs_command_search", Passed: true}
	for _, query := range []string{"workflow plan", "mcp config"} {
		matches := rankWhich(whichIndex, query, 1)
		if len(matches) == 0 || matches[0].Entry.Command != query {
			check.Passed = false
			check.Note = "docs search --source commands does not find required helper command(s)"
			check.Evidence = append(check.Evidence, "missing: "+query)
			continue
		}
		check.Evidence = append(check.Evidence, query)
	}
	if check.Passed {
		check.Note = "local helper commands are indexed by docs search --source commands"
	}
	return check
}

func checkShipcheckSafetyContract() shipcheckCheck {
	return shipcheckCheck{
		Name:   "safety",
		Passed: true,
		Note:   "local verifier blocks release actions and production writes; optional MCP proof executes a local child process with an allowlisted environment",
		Evidence: []string{
			"no publish, sign, or notarize",
			"no production writes",
			"parent CLI sends only MCP initialize and tools/list when --mcp-binary is used",
			"child process environment is allowlisted",
			"child process is not sandboxed by this command",
		},
	}
}

func checkShipcheckMCPTools(root *cobra.Command, binary string) (shipcheckCheck, error) {
	check := shipcheckCheck{
		Name: "mcp_tools",
		Note: "local stdio MCP initialize plus tools/list only",
	}
	validated, err := validateSmokeMCPBinary(binary)
	if err != nil {
		check.Note = err.Error()
		return check, err
	}

	ctx := context.Background()
	if root != nil {
		ctx = root.Context()
	}
	tools, err := runLocalMCPToolsList(ctx, validated, "straddle-pp-cli-shipcheck")
	if err != nil {
		check.Note = err.Error()
		return check, err
	}
	missing := missingShipcheckMCPTools(tools)
	if len(missing) > 0 {
		check.Note = "local stdio MCP tools/list missing required tool(s): " + strings.Join(missing, ", ")
		check.Evidence = sortedKeys(tools)
		return check, apiErr(fmt.Errorf("MCP tools/list missing required tool(s): %s", strings.Join(missing, ", ")))
	}
	check.Passed = true
	check.Evidence = requiredShipcheckMCPTools()
	return check, nil
}

func runLocalMCPToolsList(ctx context.Context, binary string, clientName string) (map[string]bool, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	var cancel context.CancelFunc
	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	process := exec.CommandContext(ctx, binary)
	process.Env = smokeMCPProcessEnv()

	stdin, err := process.StdinPipe()
	if err != nil {
		return nil, usageErr(fmt.Errorf("prepare MCP stdin: %w", err))
	}
	stdout, err := process.StdoutPipe()
	if err != nil {
		return nil, usageErr(fmt.Errorf("prepare MCP stdout: %w", err))
	}
	if err := process.Start(); err != nil {
		return nil, usageErr(fmt.Errorf("start MCP binary: %w", err))
	}
	defer func() {
		_ = process.Process.Kill()
		_ = process.Wait()
	}()

	scanner := bufio.NewScanner(stdout)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	encoder := json.NewEncoder(stdin)

	if err := encoder.Encode(map[string]any{
		"jsonrpc": "2.0",
		"id":      1,
		"method":  "initialize",
		"params": map[string]any{
			"protocolVersion": "2024-11-05",
			"capabilities":    map[string]any{},
			"clientInfo": map[string]string{
				"name":    clientName,
				"version": "0",
			},
		},
	}); err != nil {
		return nil, apiErr(fmt.Errorf("write MCP initialize request: %w", err))
	}
	if _, err := readSmokeMCPResponse(scanner, "1"); err != nil {
		return nil, err
	}
	if err := encoder.Encode(map[string]any{
		"jsonrpc": "2.0",
		"method":  "notifications/initialized",
		"params":  map[string]any{},
	}); err != nil {
		return nil, apiErr(fmt.Errorf("write MCP initialized notification: %w", err))
	}
	if err := encoder.Encode(map[string]any{
		"jsonrpc": "2.0",
		"id":      2,
		"method":  "tools/list",
		"params":  map[string]any{},
	}); err != nil {
		return nil, apiErr(fmt.Errorf("write MCP tools/list request: %w", err))
	}
	response, err := readSmokeMCPResponse(scanner, "2")
	if err != nil {
		return nil, err
	}
	return smokeMCPToolNames(response), nil
}

func requiredShipcheckMCPTools() []string {
	return []string{
		"mcp_config",
		"docs_search",
		"workflow_plan",
		"release_plan",
		"credentials_plan",
		"smoke_run",
		"setup_check",
		"shipcheck_local",
	}
}

func missingShipcheckMCPTools(tools map[string]bool) []string {
	var missing []string
	for _, name := range requiredShipcheckMCPTools() {
		if !tools[name] {
			missing = append(missing, name)
		}
	}
	return missing
}

func sortedKeys(values map[string]bool) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func renderShipcheckLocalResponse(cmd *cobra.Command, flags *rootFlags, payload shipcheckLocalResponse) error {
	asJSON := flags.asJSON || flags.agent || !isTerminal(cmd.OutOrStdout())
	if asJSON {
		return printJSONFiltered(cmd.OutOrStdout(), payload, flags)
	}
	w := cmd.OutOrStdout()
	status := "failed"
	if payload.Passed {
		status = "passed"
	}
	fmt.Fprintf(w, "Shipcheck local: %s\n", status)
	for _, check := range payload.Checks {
		checkStatus := "failed"
		if check.Passed {
			checkStatus = "passed"
		}
		fmt.Fprintf(w, "  %s: %s", check.Name, checkStatus)
		if check.Note != "" {
			fmt.Fprintf(w, " - %s", check.Note)
		}
		fmt.Fprintln(w)
	}
	return nil
}
