// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCH: shipcheck-local and public-shipcheck-approval-file cover local public-preview readiness and explicit launch approval validation.

package cli

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"runtime/debug"
	"strings"
	"testing"
)

func TestShipcheckLocalJSONSuccessWithoutMCP(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "shipcheck", "local", "--json")
	if err != nil {
		t.Fatalf("shipcheck local --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("shipcheck local wrote stderr: %q", stderr)
	}

	var got shipcheckLocalResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("shipcheck local --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "shipcheck local" || !got.Passed {
		t.Fatalf("wrong shipcheck response: %#v", got)
	}
	if len(got.Checks) < 4 {
		t.Fatalf("shipcheck should report concrete checks, got %#v", got.Checks)
	}
	if !got.Safety.LocalOnly || !got.Safety.CredentialFree || !got.Safety.NoAPICalls || !got.Safety.NoDocsEndpointCalls || !got.Safety.NoProductionWrites {
		t.Fatalf("shipcheck safety should prove local credential-free execution: %#v", got.Safety)
	}
	if got.Safety.ChildProcessExecuted || got.Safety.ChildEnvAllowlisted || got.Safety.ChildProcessSandboxed {
		t.Fatalf("shipcheck without --mcp-binary should not claim child-process proof: %#v", got.Safety)
	}
	if got.Safety.CallsGitHub || got.Safety.CallsNPM || got.Safety.CallsHomebrew || got.Safety.Publishes || got.Safety.Signs || got.Safety.Notarizes || got.Safety.ReadsSecrets {
		t.Fatalf("shipcheck safety should reject external release or secret surfaces: %#v", got.Safety)
	}
	if strings.Contains(strings.ToLower(stdout), "bearer ") || strings.Contains(stdout, "STRADDLE_TOKEN=") || strings.Contains(stdout, "sk_live") || strings.Contains(stdout, "sk_test") {
		t.Fatalf("shipcheck local should not emit token literals:\n%s", stdout)
	}
}

func TestShipcheckPublicJSONBlocksPublicLaunchButProvesLocalPreview(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "shipcheck", "public", "--json")
	if err == nil {
		t.Fatalf("shipcheck public should fail until public launch approvals are recorded")
	}
	if !strings.Contains(stderr, "owner_approval") {
		t.Fatalf("shipcheck public stderr should name the first public blocker, got %q", stderr)
	}

	var got shipcheckPublicResponse
	if unmarshalErr := json.Unmarshal([]byte(stdout), &got); unmarshalErr != nil {
		t.Fatalf("shipcheck public --json emitted invalid JSON: %v\n%s", unmarshalErr, stdout)
	}
	if got.Command != "shipcheck public" || got.Ready || !got.LocalPreviewPassed || !got.LocalPreview.Passed {
		t.Fatalf("wrong public shipcheck response: %#v", got)
	}
	for _, want := range []string{"local_preview", "owner_approval", "public_distribution", "docs_support", "desktop_mcp", "live_smoke", "signing_notarization"} {
		check := shipcheckCheckByName(t, got.Checks, want)
		if want == "local_preview" && !check.Passed {
			t.Fatalf("local preview should pass inside public shipcheck: %#v", check)
		}
		if want != "local_preview" && check.Passed {
			t.Fatalf("%s should block public readiness until approvals exist: %#v", want, check)
		}
	}
	if !shipcheckEvidenceContains(shipcheckCheckByName(t, got.Checks, "owner_approval").Evidence, "release plan owner-decisions") {
		t.Fatalf("owner approval blocker should point to release plan owner decisions: %#v", got.Checks)
	}
	if !shipcheckEvidenceContains(shipcheckCheckByName(t, got.Checks, "live_smoke").Evidence, "smoke plan approval") {
		t.Fatalf("live smoke blocker should point to smoke plan approval: %#v", got.Checks)
	}
	if len(got.NextApprovalSteps) == 0 {
		t.Fatalf("public shipcheck should include concrete approval steps: %#v", got)
	}
	if !got.Safety.LocalOnly || !got.Safety.CredentialFree || !got.Safety.NoAPICalls || !got.Safety.NoDocsEndpointCalls || !got.Safety.NoProductionWrites || !got.Safety.NoPublishing {
		t.Fatalf("public shipcheck safety should prove local non-publishing execution: %#v", got.Safety)
	}
	if got.Safety.CallsGitHub || got.Safety.CallsNPM || got.Safety.CallsHomebrew || got.Safety.Publishes || got.Safety.Signs || got.Safety.Notarizes || got.Safety.ReadsSecrets {
		t.Fatalf("public shipcheck safety should reject external release or secret surfaces: %#v", got.Safety)
	}
	if strings.Contains(strings.ToLower(stdout), "bearer ") || strings.Contains(stdout, "STRADDLE_TOKEN=") || strings.Contains(stdout, "sk_live") || strings.Contains(stdout, "sk_test") {
		t.Fatalf("shipcheck public should not emit token literals:\n%s", stdout)
	}
}

func TestShipcheckPublicApprovalFileMakesPublicReady(t *testing.T) {
	withShipcheckCleanCommit(t, "1111111111111111111111111111111111111111")
	approvalPath := writeShipcheckPublicApprovalFile(t, nil)

	stdout, stderr, err := runCLIForDocsTest(t, "shipcheck", "public", "--approval-file", approvalPath, "--json")
	if err != nil {
		t.Fatalf("shipcheck public with approval file returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("shipcheck public with approval file wrote stderr: %q", stderr)
	}

	var got shipcheckPublicResponse
	if unmarshalErr := json.Unmarshal([]byte(stdout), &got); unmarshalErr != nil {
		t.Fatalf("shipcheck public --approval-file emitted invalid JSON: %v\n%s", unmarshalErr, stdout)
	}
	if got.Command != "shipcheck public" || !got.Ready || !got.LocalPreviewPassed || !got.LocalPreview.Passed {
		t.Fatalf("wrong public shipcheck approval response: %#v", got)
	}
	for _, want := range []string{"local_preview", "approval_file", "owner_approval", "public_distribution", "docs_support", "desktop_mcp", "live_smoke", "signing_notarization"} {
		check := shipcheckCheckByName(t, got.Checks, want)
		if !check.Passed {
			t.Fatalf("%s should pass with strict approval file: %#v", want, check)
		}
	}
	if !shipcheckEvidenceContains(shipcheckCheckByName(t, got.Checks, "owner_approval").Evidence, "approved by Public Launch Approver") {
		t.Fatalf("approved public check should include approval evidence: %#v", got.Checks)
	}
	if !got.Safety.LocalOnly || !got.Safety.CredentialFree || !got.Safety.NoAPICalls || !got.Safety.NoDocsEndpointCalls || !got.Safety.NoProductionWrites || !got.Safety.NoPublishing {
		t.Fatalf("public shipcheck safety should stay local-only with approval file: %#v", got.Safety)
	}
	if got.Safety.CallsGitHub || got.Safety.CallsNPM || got.Safety.CallsHomebrew || got.Safety.Publishes || got.Safety.Signs || got.Safety.Notarizes || got.Safety.ReadsSecrets {
		t.Fatalf("public shipcheck approval should not execute release, secret, signing, or external surfaces: %#v", got.Safety)
	}
	if strings.Contains(strings.ToLower(stdout), "bearer ") || strings.Contains(stdout, "STRADDLE_TOKEN=") || strings.Contains(stdout, "sk_live") || strings.Contains(stdout, "sk_test") {
		t.Fatalf("shipcheck public approval output should not emit token literals:\n%s", stdout)
	}
}

func TestShipcheckPublicApprovalTemplatePrintsStrictCurrentCommitTemplate(t *testing.T) {
	commit := "1111111111111111111111111111111111111111"
	withShipcheckCleanCommit(t, commit)

	stdout, stderr, err := runCLIForDocsTest(t, "shipcheck", "public", "--approval-template")
	if err != nil {
		t.Fatalf("shipcheck public --approval-template returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("shipcheck public --approval-template wrote stderr: %q", stderr)
	}

	var got shipcheckPublicApprovalFile
	decoder := json.NewDecoder(strings.NewReader(stdout))
	decoder.DisallowUnknownFields()
	if decodeErr := decoder.Decode(&got); decodeErr != nil {
		t.Fatalf("approval template should be strict JSON matching the approval file shape: %v\n%s", decodeErr, stdout)
	}
	if decoder.Decode(&struct{}{}) == nil {
		t.Fatalf("approval template should contain exactly one JSON object:\n%s", stdout)
	}
	if got.Approver != "" || got.ApprovedAt != "" {
		t.Fatalf("approval template should leave approver and approved_at empty for the reviewer: %#v", got)
	}
	if got.LocalPreviewCommit != commit {
		t.Fatalf("approval template should include current local preview commit %q, got %#v", commit, got)
	}
	for _, name := range requiredShipcheckPublicApprovals() {
		value := approvalValue(got, name)
		if value == nil {
			t.Fatalf("approval template missing approval field %s: %#v", name, got)
		}
		if *value {
			t.Fatalf("approval template should not pre-approve %s: %#v", name, got)
		}
		if got.Evidence == nil {
			t.Fatalf("approval template missing evidence object: %#v", got)
		}
		evidence, ok := got.Evidence[name]
		if !ok {
			t.Fatalf("approval template evidence missing key %s: %#v", name, got.Evidence)
		}
		if evidence != "" {
			t.Fatalf("approval template evidence.%s should be empty for reviewer-supplied evidence, got %q", name, evidence)
		}
	}
	if strings.Contains(stdout, "local_preview_passed") || strings.Contains(stdout, "checks") || strings.Contains(stdout, "next_approval_steps") {
		t.Fatalf("approval template should not run or render public shipcheck response:\n%s", stdout)
	}
	if strings.Contains(strings.ToLower(stdout), "bearer ") || strings.Contains(stdout, "STRADDLE_TOKEN=") || strings.Contains(stdout, "sk_live") || strings.Contains(stdout, "sk_test") {
		t.Fatalf("approval template should not emit token literals:\n%s", stdout)
	}
}

func TestShipcheckPublicApprovalTemplateRejectsModifiedBuild(t *testing.T) {
	commit := "1111111111111111111111111111111111111111"
	withShipcheckCleanCommit(t, commit)
	shipcheckReadBuildInfo = func() (*debug.BuildInfo, bool) {
		return &debug.BuildInfo{Settings: []debug.BuildSetting{
			{Key: "vcs.revision", Value: commit},
			{Key: "vcs.modified", Value: "true"},
		}}, true
	}

	_, _, err := runCLIForDocsTest(t, "shipcheck", "public", "--approval-template")
	if err == nil {
		t.Fatalf("shipcheck public --approval-template should reject modified build")
	}
	if !strings.Contains(strings.ToLower(err.Error()), "modified") {
		t.Fatalf("modified build error should be clear, got %v", err)
	}
}

func TestShipcheckPublicApprovalFileRejectsInvalidApprovals(t *testing.T) {
	withShipcheckCleanCommit(t, "1111111111111111111111111111111111111111")
	tests := []struct {
		name      string
		overrides map[string]any
		want      string
	}{
		{
			name:      "missing approval",
			overrides: map[string]any{"owner_approval": nil},
			want:      "owner_approval",
		},
		{
			name:      "false approval",
			overrides: map[string]any{"desktop_mcp": false},
			want:      "desktop_mcp",
		},
		{
			name:      "unknown top-level field",
			overrides: map[string]any{"unexpected": true},
			want:      "unknown field",
		},
		{
			name:      "token literal",
			overrides: map[string]any{"evidence": map[string]any{"owner_approval": "Bearer fixture-token"}},
			want:      "token literals",
		},
		{
			name:      "commit mismatch",
			overrides: map[string]any{"local_preview_commit": "0000000000000000000000000000000000000000"},
			want:      "local_preview_commit",
		},
		{
			name:      "unknown evidence field",
			overrides: map[string]any{"evidence": map[string]any{"unexpected": "not part of public launch approval"}},
			want:      "unexpected",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			approvalPath := writeShipcheckPublicApprovalFile(t, tc.overrides)

			_, _, err := runCLIForDocsTest(t, "shipcheck", "public", "--approval-file", approvalPath, "--json")
			if err == nil {
				t.Fatalf("shipcheck public should reject invalid approval file")
			}
			if !strings.Contains(strings.ToLower(err.Error()), strings.ToLower(tc.want)) {
				t.Fatalf("error should mention %q, got %v", tc.want, err)
			}
		})
	}
}

func TestShipcheckPublicApprovalFileRejectsModifiedBuild(t *testing.T) {
	commit := "1111111111111111111111111111111111111111"
	withShipcheckCleanCommit(t, commit)
	approvalPath := writeShipcheckPublicApprovalFile(t, nil)
	shipcheckReadBuildInfo = func() (*debug.BuildInfo, bool) {
		return &debug.BuildInfo{Settings: []debug.BuildSetting{
			{Key: "vcs.revision", Value: commit},
			{Key: "vcs.modified", Value: "true"},
		}}, true
	}

	_, _, err := runCLIForDocsTest(t, "shipcheck", "public", "--approval-file", approvalPath, "--json")
	if err == nil {
		t.Fatalf("shipcheck public should reject approval for modified build")
	}
	if !strings.Contains(strings.ToLower(err.Error()), "modified") {
		t.Fatalf("modified build error should be clear, got %v", err)
	}
}

func TestShipcheckPublicAgentUsesTargetEnvelope(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "shipcheck", "public", "--agent")
	if err == nil {
		t.Fatalf("shipcheck public --agent should fail until public launch approvals are recorded")
	}
	if !strings.Contains(stderr, "owner_approval") {
		t.Fatalf("shipcheck public --agent stderr should name the first public blocker, got %q", stderr)
	}

	var got struct {
		SchemaVersion string                  `json:"schema_version"`
		Data          shipcheckPublicResponse `json:"data"`
		Warnings      []string                `json:"warnings"`
		Error         any                     `json:"error"`
		Results       any                     `json:"results"`
		Meta          any                     `json:"meta"`
	}
	if unmarshalErr := json.Unmarshal([]byte(stdout), &got); unmarshalErr != nil {
		t.Fatalf("shipcheck public --agent emitted invalid JSON: %v\n%s", unmarshalErr, stdout)
	}
	if got.SchemaVersion != "1.0" || got.Error != nil || got.Warnings == nil || len(got.Warnings) != 0 {
		t.Fatalf("wrong agent envelope: %#v", got)
	}
	if got.Results != nil || got.Meta != nil {
		t.Fatalf("agent envelope should not include results/meta: %#v", got)
	}
	if got.Data.Command != "shipcheck public" || got.Data.Ready || !got.Data.LocalPreviewPassed {
		t.Fatalf("agent envelope missing public shipcheck data: %#v", got.Data)
	}
}

func TestShipcheckPublicRejectsDeliverBeforeDelivery(t *testing.T) {
	target := filepath.Join(t.TempDir(), "shipcheck-public-delivery.json")
	home := t.TempDir()
	t.Setenv("HOME", home)

	oldArgs := os.Args
	t.Cleanup(func() {
		os.Args = oldArgs
	})
	os.Args = []string{
		"straddle-pp-cli",
		"shipcheck",
		"public",
		"--deliver",
		"file:" + target,
		"--profile",
		"missing-profile",
	}

	err := Execute()
	if err == nil {
		t.Fatalf("shipcheck public should reject --deliver")
	}
	if !strings.Contains(err.Error(), "shipcheck public does not support --deliver") {
		t.Fatalf("error should explain --deliver is unsupported, got %v", err)
	}
	if _, statErr := os.Stat(target); !os.IsNotExist(statErr) {
		t.Fatalf("shipcheck public should reject --deliver before writing output, stat err=%v", statErr)
	}
	if _, statErr := os.Stat(filepath.Join(home, ".straddle-pp-cli")); !os.IsNotExist(statErr) {
		t.Fatalf("shipcheck public should reject --deliver before loading profile state, stat err=%v", statErr)
	}
}

func TestShipcheckLocalCommandTreeRequiredPaths(t *testing.T) {
	payload, err := buildShipcheckLocalResponse(RootCmd(), "")
	if err != nil {
		t.Fatalf("buildShipcheckLocalResponse returned error: %v", err)
	}
	check := shipcheckCheckByName(t, payload.Checks, "command_tree")
	if !check.Passed {
		t.Fatalf("command_tree check failed: %#v", check)
	}
	for _, want := range requiredShipcheckCommandPaths() {
		if !containsString(check.Evidence, want) {
			t.Fatalf("command_tree evidence missing %q: %#v", want, check.Evidence)
		}
	}
}

func TestShipcheckLocalObjectiveSurfaces(t *testing.T) {
	payload, err := buildShipcheckLocalResponse(RootCmd(), "")
	if err != nil {
		t.Fatalf("buildShipcheckLocalResponse returned error: %v", err)
	}
	check := shipcheckCheckByName(t, payload.Checks, "objective_surfaces")
	if !check.Passed {
		t.Fatalf("objective_surfaces check failed: %#v", check)
	}
	for _, want := range []string{
		"presentation: about word art with local preview metadata",
		"presentation command: about",
		"agent-friendly output: agent-context",
		"setup: setup check",
		"customers: customers list",
		"payments: payments",
		"reconciliation data source: funding-events list",
		"fraud review: customers review get-customer",
		"collections: charges resubmit create",
		"reporting: reports",
		"monitoring: tail",
		"sandbox testing: sandbox guide",
		"docs search: docs search",
		"MCP: mcp config",
		"Ramp benchmark: benchmark ramp",
		"release readiness: release plan",
		"workflow: reconciliation",
		"workflow: fraud-monitoring",
		"workflow: collections",
		"workflow: reporting",
		"workflow: monitoring",
	} {
		if !containsString(check.Evidence, want) {
			t.Fatalf("objective surface evidence missing %q: %#v", want, check.Evidence)
		}
	}
}

func TestShipcheckLocalProvenanceSuccess(t *testing.T) {
	packageDir, sourceHash := writeShipcheckProvenanceFixture(t, "source-openapi", "transformed-spec")

	check := checkShipcheckProvenanceFromDirs([]string{filepath.Join(packageDir, "internal", "cli")})

	if !check.Passed {
		t.Fatalf("provenance check should pass: %#v", check)
	}
	for _, want := range []string{
		"generator: CLI Printing Press 4.2.0",
		"docs openapi: ",
		"checksum: matched sha256:" + sourceHash,
		"mcp sibling: straddle-pp-mcp",
	} {
		if !shipcheckEvidenceContains(check.Evidence, want) {
			t.Fatalf("provenance evidence missing %q: %#v", want, check.Evidence)
		}
	}
}

func TestShipcheckLocalProvenancePackagedMetadataDiscovery(t *testing.T) {
	packageDir, sourceHash := writeShipcheckProvenanceFixture(t, "source-openapi", "transformed-spec")
	distDir := filepath.Join(packageDir, "dist", "local")
	if err := os.MkdirAll(filepath.Join(distDir, "nested-run-dir"), 0o755); err != nil {
		t.Fatalf("create packaged run dir: %v", err)
	}
	copyShipcheckFixtureFile(t, filepath.Join(packageDir, ".printing-press.json"), filepath.Join(distDir, ".printing-press.json"))
	writeShipcheckExecutableFixture(t, filepath.Join(distDir, "straddle-pp-cli"))
	writeShipcheckExecutableFixture(t, filepath.Join(distDir, "straddle-pp-mcp"))

	check := checkShipcheckProvenanceFromDirs([]string{filepath.Join(distDir, "nested-run-dir")})

	if !check.Passed {
		t.Fatalf("packaged provenance check should pass from a trimpath-style package dir: %#v", check)
	}
	for _, want := range []string{
		"checksum: matched sha256:" + sourceHash,
		"mcp sibling: straddle-pp-mcp exists next to metadata",
	} {
		if !shipcheckEvidenceContains(check.Evidence, want) {
			t.Fatalf("packaged provenance evidence missing %q: %#v", want, check.Evidence)
		}
	}
}

func TestShipcheckLocalProvenanceSearchDirsPreferExecutableDir(t *testing.T) {
	dirs := shipcheckProvenanceSearchDirsFrom(
		filepath.Join("repo", "packages", "cli", "straddle-pp-cli"),
		filepath.Join("repo", "packages", "cli", "straddle-pp-cli", "internal", "cli", "shipcheck.go"),
		filepath.Join("dist", "local", "straddle-pp-cli"),
	)

	want := []string{
		filepath.Join("dist", "local"),
		filepath.Join("repo", "packages", "cli", "straddle-pp-cli"),
		filepath.Join("repo", "packages", "cli", "straddle-pp-cli", "internal", "cli"),
	}
	if len(dirs) != len(want) {
		t.Fatalf("unexpected search dirs %#v", dirs)
	}
	for index := range want {
		if dirs[index] != want[index] {
			t.Fatalf("search dir %d = %q, want %q in %#v", index, dirs[index], want[index], dirs)
		}
	}
}

func TestShipcheckLocalProvenanceMissingConfigFails(t *testing.T) {
	packageDir := filepath.Join(t.TempDir(), "packages", "cli", "straddle-pp-cli")
	if err := os.MkdirAll(filepath.Join(packageDir, "internal", "cli"), 0o755); err != nil {
		t.Fatalf("create fixture package dir: %v", err)
	}

	check := checkShipcheckProvenanceFromDirs([]string{filepath.Join(packageDir, "internal", "cli")})

	if check.Passed {
		t.Fatalf("provenance check should fail without .printing-press.json: %#v", check)
	}
	if !strings.Contains(check.Note, "missing .printing-press.json") {
		t.Fatalf("missing config error should be clear, got %#v", check)
	}
}

func TestShipcheckLocalProvenanceChecksumMismatchFails(t *testing.T) {
	packageDir, sourceHash := writeShipcheckProvenanceFixture(t, "source-openapi", "transformed-spec")
	writeShipcheckPrintingPressConfig(t, packageDir, shipcheckProvenanceFixtureConfig{
		SourcePath: shipcheckProvenanceFixtureSourcePath(packageDir),
		Checksum:   "sha256:0000000000000000000000000000000000000000000000000000000000000000",
	})

	check := checkShipcheckProvenanceFromDirs([]string{packageDir})

	if check.Passed {
		t.Fatalf("provenance check should fail on checksum mismatch: %#v", check)
	}
	if !strings.Contains(check.Note, "checksum mismatch") {
		t.Fatalf("checksum mismatch should be clear, got %#v", check)
	}
	if !shipcheckEvidenceContains(check.Evidence, "got sha256:"+sourceHash) {
		t.Fatalf("checksum mismatch evidence should include actual source hash: %#v", check.Evidence)
	}
}

func TestShipcheckLocalProvenanceInvalidChecksumFailsWithMissingSource(t *testing.T) {
	packageDir, _ := writeShipcheckProvenanceFixture(t, "source-openapi", "transformed-spec")
	sourcePath := shipcheckProvenanceFixtureSourcePath(packageDir)
	if err := os.Remove(sourcePath); err != nil {
		t.Fatalf("remove source OpenAPI fixture: %v", err)
	}
	writeShipcheckPrintingPressConfig(t, packageDir, shipcheckProvenanceFixtureConfig{
		SourcePath: sourcePath,
		Checksum:   "sha256:not-a-real-hash",
	})

	check := checkShipcheckProvenanceFromDirs([]string{packageDir})

	if check.Passed {
		t.Fatalf("invalid checksum should fail even when source is missing: %#v", check)
	}
	if !strings.Contains(check.Note, "sha256:<64 hex characters>") {
		t.Fatalf("invalid checksum failure should be clear, got %#v", check)
	}
}

func TestShipcheckLocalProvenanceRejectsBackupOpenAPIPath(t *testing.T) {
	packageDir, sourceHash := writeShipcheckProvenanceFixture(t, "source-openapi", "transformed-spec")
	writeShipcheckPrintingPressConfig(t, packageDir, shipcheckProvenanceFixtureConfig{
		SourcePath: shipcheckProvenanceFixtureSourcePath(packageDir) + ".backup",
		Checksum:   "sha256:" + sourceHash,
	})

	check := checkShipcheckProvenanceFromDirs([]string{packageDir})

	if check.Passed {
		t.Fatalf("backup OpenAPI path should not pass source identity validation: %#v", check)
	}
	if !strings.Contains(check.Note, "must point spec_path or spec_url") {
		t.Fatalf("backup OpenAPI path failure should be clear, got %#v", check)
	}
}

func TestShipcheckLocalProvenanceMissingSourcePassesWithRecordedChecksum(t *testing.T) {
	packageDir, _ := writeShipcheckProvenanceFixture(t, "source-openapi", "transformed-spec")
	sourcePath := shipcheckProvenanceFixtureSourcePath(packageDir)
	if err := os.Remove(sourcePath); err != nil {
		t.Fatalf("remove source OpenAPI fixture: %v", err)
	}

	check := checkShipcheckProvenanceFromDirs([]string{packageDir})

	if !check.Passed {
		t.Fatalf("missing source should not fail portable local readiness: %#v", check)
	}
	if !strings.Contains(check.Note, "recorded checksum evidence") {
		t.Fatalf("missing source should be a recorded-checksum warning, got %#v", check)
	}
	if !shipcheckEvidenceContains(check.Evidence, "checksum: source unavailable") {
		t.Fatalf("missing source evidence should be clear: %#v", check.Evidence)
	}
}

func TestShipcheckLocalProvenanceMissingSourceFailsInStrictMode(t *testing.T) {
	t.Setenv(shipcheckStrictProvenanceEnv, "1")
	packageDir, _ := writeShipcheckProvenanceFixture(t, "source-openapi", "transformed-spec")
	sourcePath := shipcheckProvenanceFixtureSourcePath(packageDir)
	if err := os.Remove(sourcePath); err != nil {
		t.Fatalf("remove source OpenAPI fixture: %v", err)
	}

	check := checkShipcheckProvenanceFromDirs([]string{packageDir})

	if check.Passed {
		t.Fatalf("strict provenance check should fail when source OpenAPI is absent: %#v", check)
	}
	if !strings.Contains(check.Note, "strict provenance mode") {
		t.Fatalf("strict missing-source failure should be clear, got %#v", check)
	}
}

func TestShipcheckLocalProvenanceUnexpectedMCPBinaryFails(t *testing.T) {
	packageDir, sourceHash := writeShipcheckProvenanceFixture(t, "source-openapi", "transformed-spec")
	writeShipcheckPrintingPressConfig(t, packageDir, shipcheckProvenanceFixtureConfig{
		SourcePath: shipcheckProvenanceFixtureSourcePath(packageDir),
		Checksum:   "sha256:" + sourceHash,
		MCPBinary:  "other-mcp",
	})

	check := checkShipcheckProvenanceFromDirs([]string{packageDir})

	if check.Passed {
		t.Fatalf("provenance check should fail on unexpected mcp_binary: %#v", check)
	}
	if !strings.Contains(check.Note, "mcp_binary must be straddle-pp-mcp") {
		t.Fatalf("unexpected mcp_binary should be clear, got %#v", check)
	}
}

func TestShipcheckLocalProvenancePackagedMissingMCPBinaryFails(t *testing.T) {
	packageDir, _ := writeShipcheckProvenanceFixture(t, "source-openapi", "transformed-spec")
	distDir := filepath.Join(packageDir, "dist", "local")
	if err := os.MkdirAll(distDir, 0o755); err != nil {
		t.Fatalf("create packaged dir: %v", err)
	}
	copyShipcheckFixtureFile(t, filepath.Join(packageDir, ".printing-press.json"), filepath.Join(distDir, ".printing-press.json"))
	writeShipcheckExecutableFixture(t, filepath.Join(distDir, "straddle-pp-cli"))

	check := checkShipcheckProvenanceFromDirs([]string{distDir})

	if check.Passed {
		t.Fatalf("packaged provenance check should fail when MCP sibling is absent: %#v", check)
	}
	if !strings.Contains(check.Note, "missing generated MCP sibling") {
		t.Fatalf("packaged missing MCP sibling should be clear, got %#v", check)
	}
}

func TestShipcheckLocalProvenanceDoesNotCompareTransformedSpecJSON(t *testing.T) {
	packageDir, _ := writeShipcheckProvenanceFixture(t, "source-openapi", "different-transformed-spec")

	check := checkShipcheckProvenanceFromDirs([]string{packageDir})

	if !check.Passed {
		t.Fatalf("provenance check should pass without comparing generated spec.json: %#v", check)
	}
	if !shipcheckEvidenceContains(check.Evidence, "generated spec.json: not compared") {
		t.Fatalf("provenance evidence should state transformed spec.json is not compared: %#v", check.Evidence)
	}
}

func TestShipcheckLocalWorkflowNames(t *testing.T) {
	payload, err := buildShipcheckLocalResponse(RootCmd(), "")
	if err != nil {
		t.Fatalf("buildShipcheckLocalResponse returned error: %v", err)
	}
	check := shipcheckCheckByName(t, payload.Checks, "workflow_plans")
	if !check.Passed {
		t.Fatalf("workflow_plans check failed: %#v", check)
	}
	for _, want := range []string{"reconciliation", "fraud-monitoring", "collections", "reporting", "monitoring"} {
		if !containsString(check.Evidence, want) {
			t.Fatalf("workflow_plans evidence missing %q: %#v", want, check.Evidence)
		}
	}
}

func TestShipcheckLocalFakeMCPSuccess(t *testing.T) {
	binary := writeFakeMCPBinary(t, requiredShipcheckMCPTools())

	stdout, stderr, err := runCLIForDocsTest(t, "shipcheck", "local", "--mcp-binary", binary, "--json")
	if err != nil {
		t.Fatalf("shipcheck local fake MCP returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("shipcheck local fake MCP wrote stderr: %q", stderr)
	}

	var got shipcheckLocalResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("shipcheck local fake MCP emitted invalid JSON: %v\n%s", err, stdout)
	}
	if !got.Passed {
		t.Fatalf("shipcheck local fake MCP should pass: %#v", got)
	}
	if !got.Safety.ChildProcessExecuted || !got.Safety.ChildEnvAllowlisted || got.Safety.ChildProcessSandboxed {
		t.Fatalf("shipcheck local fake MCP should state child process was executed with allowlisted env and no sandbox: %#v", got.Safety)
	}
	if got.Safety.NoAPICalls || got.Safety.NoSecretsRead || got.Safety.NoGitHubCalls || got.Safety.NoNPMCalls || got.Safety.NoHomebrewCalls {
		t.Fatalf("shipcheck local fake MCP should not overclaim child-process behavior: %#v", got.Safety)
	}
	check := shipcheckCheckByName(t, got.Checks, "mcp_tools")
	if !check.Passed {
		t.Fatalf("mcp_tools should pass: %#v", check)
	}
	for _, want := range requiredShipcheckMCPTools() {
		if !containsString(check.Evidence, want) {
			t.Fatalf("mcp_tools evidence missing %q: %#v", want, check.Evidence)
		}
	}
	if strings.Contains(stdout, binary) {
		t.Fatalf("shipcheck local should not print local binary paths:\n%s", stdout)
	}
}

func TestShipcheckLocalFakeMCPMissingRequiredToolFails(t *testing.T) {
	tools := []string{}
	for _, name := range requiredShipcheckMCPTools() {
		if name != "release_plan" {
			tools = append(tools, name)
		}
	}
	binary := writeFakeMCPBinary(t, tools)

	stdout, _, err := runCLIForDocsTest(t, "shipcheck", "local", "--mcp-binary", binary, "--json")
	if err == nil {
		t.Fatalf("shipcheck local should fail when MCP tool is missing")
	}
	if !strings.Contains(err.Error(), "release_plan") {
		t.Fatalf("error should mention missing release_plan, got %v", err)
	}
	var got shipcheckLocalResponse
	if unmarshalErr := json.Unmarshal([]byte(stdout), &got); unmarshalErr != nil {
		t.Fatalf("failed shipcheck should still emit JSON: %v\n%s", unmarshalErr, stdout)
	}
	if got.Passed {
		t.Fatalf("shipcheck should not pass with missing MCP tool: %#v", got)
	}
	check := shipcheckCheckByName(t, got.Checks, "mcp_tools")
	if check.Passed || !strings.Contains(check.Note, "release_plan") {
		t.Fatalf("mcp_tools should record missing release_plan: %#v", check)
	}
}

func TestShipcheckLocalRejectsDeliverBeforeDelivery(t *testing.T) {
	target := filepath.Join(t.TempDir(), "shipcheck-delivery.json")
	home := t.TempDir()
	t.Setenv("HOME", home)

	oldArgs := os.Args
	t.Cleanup(func() {
		os.Args = oldArgs
	})
	os.Args = []string{
		"straddle-pp-cli",
		"shipcheck",
		"local",
		"--deliver",
		"file:" + target,
		"--profile",
		"missing-profile",
	}

	err := Execute()
	if err == nil {
		t.Fatalf("shipcheck local should reject --deliver")
	}
	if !strings.Contains(err.Error(), "shipcheck local does not support --deliver") {
		t.Fatalf("error should explain --deliver is unsupported, got %v", err)
	}
	if _, statErr := os.Stat(target); !os.IsNotExist(statErr) {
		t.Fatalf("shipcheck local should reject --deliver before writing output, stat err=%v", statErr)
	}
	if _, statErr := os.Stat(filepath.Join(home, ".straddle-pp-cli")); !os.IsNotExist(statErr) {
		t.Fatalf("shipcheck local should reject --deliver before loading profile state, stat err=%v", statErr)
	}
}

func TestShipcheckLocalRejectsSecretLiteralMCPBinary(t *testing.T) {
	_, _, err := runCLIForDocsTest(t, "shipcheck", "local", "--mcp-binary", "straddle-pp-mcp --token sk_test_fixture", "--json")
	if err == nil {
		t.Fatalf("shipcheck local should reject token literals in --mcp-binary")
	}
	var cliErr *cliError
	if !errors.As(err, &cliErr) || cliErr.code != 2 {
		t.Fatalf("token literal rejection should be a usage error, got %#v", err)
	}
	if !strings.Contains(strings.ToLower(err.Error()), "token") {
		t.Fatalf("error should mention token literal rejection, got %v", err)
	}
}

func shipcheckCheckByName(t *testing.T, checks []shipcheckCheck, name string) shipcheckCheck {
	t.Helper()
	for _, check := range checks {
		if check.Name == name {
			return check
		}
	}
	t.Fatalf("missing check %q in %#v", name, checks)
	return shipcheckCheck{}
}

type shipcheckProvenanceFixtureConfig struct {
	SourcePath string
	Checksum   string
	MCPBinary  string
}

func writeShipcheckProvenanceFixture(t *testing.T, sourceOpenAPI string, transformedSpec string) (string, string) {
	t.Helper()
	tempDir := t.TempDir()
	packageDir := filepath.Join(tempDir, "repo", "packages", "cli", "straddle-pp-cli")
	if err := os.MkdirAll(filepath.Join(packageDir, "internal", "cli"), 0o755); err != nil {
		t.Fatalf("create fixture package dir: %v", err)
	}
	sourcePath := shipcheckProvenanceFixtureSourcePath(packageDir)
	if err := os.MkdirAll(filepath.Dir(sourcePath), 0o755); err != nil {
		t.Fatalf("create fixture docs dir: %v", err)
	}
	if err := os.WriteFile(sourcePath, []byte(sourceOpenAPI), 0o644); err != nil {
		t.Fatalf("write fixture source OpenAPI: %v", err)
	}
	if err := os.WriteFile(filepath.Join(packageDir, "spec.json"), []byte(transformedSpec), 0o644); err != nil {
		t.Fatalf("write transformed spec fixture: %v", err)
	}
	sourceHash := sha256StringHex(sourceOpenAPI)
	writeShipcheckPrintingPressConfig(t, packageDir, shipcheckProvenanceFixtureConfig{
		SourcePath: sourcePath,
		Checksum:   "sha256:" + sourceHash,
	})
	return packageDir, sourceHash
}

func shipcheckProvenanceFixtureSourcePath(packageDir string) string {
	return filepath.Clean(filepath.Join(packageDir, "..", "..", "..", "straddle", "sdks", "straddle-docs", "docs", "api-reference", "openapi.json"))
}

func writeShipcheckPrintingPressConfig(t *testing.T, packageDir string, config shipcheckProvenanceFixtureConfig) {
	t.Helper()
	mcpBinary := config.MCPBinary
	if mcpBinary == "" {
		mcpBinary = "straddle-pp-mcp"
	}
	raw, err := json.MarshalIndent(map[string]any{
		"printing_press_version": "4.2.0",
		"printer_name":           "hello-keith",
		"spec_path":              config.SourcePath,
		"spec_url":               config.SourcePath,
		"spec_checksum":          config.Checksum,
		"mcp_binary":             mcpBinary,
	}, "", "  ")
	if err != nil {
		t.Fatalf("marshal fixture .printing-press.json: %v", err)
	}
	if err := os.WriteFile(filepath.Join(packageDir, ".printing-press.json"), raw, 0o644); err != nil {
		t.Fatalf("write fixture .printing-press.json: %v", err)
	}
}

func copyShipcheckFixtureFile(t *testing.T, source string, target string) {
	t.Helper()
	raw, err := os.ReadFile(source)
	if err != nil {
		t.Fatalf("read fixture file %s: %v", source, err)
	}
	if err := os.WriteFile(target, raw, 0o644); err != nil {
		t.Fatalf("copy fixture file to %s: %v", target, err)
	}
}

func writeShipcheckExecutableFixture(t *testing.T, path string) {
	t.Helper()
	if err := os.WriteFile(path, []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
		t.Fatalf("write executable fixture %s: %v", path, err)
	}
}

func sha256StringHex(value string) string {
	sum := sha256.Sum256([]byte(value))
	return hex.EncodeToString(sum[:])
}

func shipcheckEvidenceContains(evidence []string, want string) bool {
	for _, item := range evidence {
		if strings.Contains(item, want) {
			return true
		}
	}
	return false
}

func withShipcheckCleanCommit(t *testing.T, commit string) {
	t.Helper()

	oldReadBuildInfo := shipcheckReadBuildInfo
	oldWorktreeModified := shipcheckWorktreeModified
	shipcheckReadBuildInfo = func() (*debug.BuildInfo, bool) {
		return &debug.BuildInfo{Settings: []debug.BuildSetting{
			{Key: "vcs.revision", Value: commit},
			{Key: "vcs.modified", Value: "false"},
		}}, true
	}
	shipcheckWorktreeModified = func(string) (bool, error) {
		return false, nil
	}
	t.Cleanup(func() {
		shipcheckReadBuildInfo = oldReadBuildInfo
		shipcheckWorktreeModified = oldWorktreeModified
	})
}

func writeShipcheckPublicApprovalFile(t *testing.T, overrides map[string]any) string {
	t.Helper()

	commit, err := currentShipcheckGitCommit()
	if err != nil {
		t.Fatalf("get current git commit for approval fixture: %v", err)
	}
	evidence := map[string]any{}
	for _, name := range requiredShipcheckPublicApprovals() {
		evidence[name] = name + " approved in local test fixture"
	}
	approval := map[string]any{
		"approver":             "Public Launch Approver",
		"approved_at":          "2026-05-10T00:00:00Z",
		"local_preview_commit": commit,
		"owner_approval":       true,
		"public_distribution":  true,
		"docs_support":         true,
		"desktop_mcp":          true,
		"live_smoke":           true,
		"signing_notarization": true,
		"evidence":             evidence,
	}
	for key, value := range overrides {
		if value == nil {
			delete(approval, key)
			continue
		}
		approval[key] = value
	}

	data, err := json.Marshal(approval)
	if err != nil {
		t.Fatalf("marshal public approval file: %v", err)
	}
	path := filepath.Join(t.TempDir(), "public-approval.json")
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatalf("write public approval file: %v", err)
	}
	return path
}
