// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

const fakeMCPBinaryPrefix = "fake-straddle-pp-mcp"

// PATCH: smoke-plan covers local-only approved live-smoke planning guidance and safety metadata.
// PATCH: smoke-run-approval-gated covers approval gates plus fake server and fake MCP smoke execution.
// PATCH: smoke-run-approval-gated covers redacted transcript artifact writing.
func TestMain(m *testing.M) {
	if isFakeMCPHelperProcess() {
		os.Exit(runFakeMCPHelperProcess())
	}
	os.Exit(m.Run())
}

func TestSmokePlanNoArgJSONReturnsScopesAndSafety(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", "--json")
	if err != nil {
		t.Fatalf("smoke plan --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke plan wrote stderr: %q", stderr)
	}

	var got smokePlanResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke plan --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "smoke plan" {
		t.Fatalf("command = %q, want smoke plan", got.Command)
	}
	wantScopes := []string{"setup", "customers", "payments", "funding", "mcp", "approval", "all"}
	if strings.Join(got.AvailableScopes, ",") != strings.Join(wantScopes, ",") {
		t.Fatalf("available scopes = %#v, want %#v", got.AvailableScopes, wantScopes)
	}
	if !got.Safety.GuidanceOnly || !got.Safety.LocalOnly || !got.Safety.RequiresExplicitApproval {
		t.Fatalf("smoke plan should be local guidance requiring approval: %#v", got.Safety)
	}
	if !got.Safety.RequiresSandboxOrApprovedCredential || !got.Safety.RequiresCredentialThroughSecureFlow {
		t.Fatalf("smoke plan should require approved credentials through a secure flow: %#v", got.Safety)
	}
	if !got.Safety.ReadOnlyIntendedCommandsOnly || !got.Safety.NoWrites || !got.Safety.NoTokenLiterals || !got.Safety.NoLiveExecutionInCommand {
		t.Fatalf("smoke plan should be read-only guidance without tokens or live execution: %#v", got.Safety)
	}
	if got.Safety.MakesAPICalls || got.Safety.CallsDocsEndpoint || got.Safety.ExecutesMCP || got.Safety.PostsWebhook || got.Safety.WritesSandbox || got.Safety.WritesProduction {
		t.Fatalf("smoke plan should not touch APIs, docs, MCP, webhooks, sandbox, or production: %#v", got.Safety)
	}
}

func TestSmokePlanScopesIncludeExpectedCommands(t *testing.T) {
	tests := map[string][]string{
		"setup": {
			"straddle-pp-cli setup check --json",
		},
		"customers": {
			"straddle-pp-cli setup check --json",
			"straddle-pp-cli customers list --dry-run --agent",
		},
		"payments": {
			"straddle-pp-cli payments --dry-run --agent",
		},
		"funding": {
			"straddle-pp-cli funding-events list --dry-run --agent",
		},
		"mcp": {
			"straddle-pp-cli setup check --json",
		},
		"approval": {
			"straddle-pp-cli smoke plan setup --json",
			"straddle-pp-cli smoke plan customers --json",
			"straddle-pp-cli docs search sandbox --source commands --json",
		},
	}

	for scope, wantCommands := range tests {
		t.Run(scope, func(t *testing.T) {
			stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", scope, "--json")
			if err != nil {
				t.Fatalf("smoke plan %s --json returned error: %v", scope, err)
			}
			if stderr != "" {
				t.Fatalf("smoke plan %s wrote stderr: %q", scope, stderr)
			}

			var got smokePlanResponse
			if err := json.Unmarshal([]byte(stdout), &got); err != nil {
				t.Fatalf("smoke plan %s --json emitted invalid JSON: %v\n%s", scope, err, stdout)
			}
			if got.Scope != scope || got.ScopePlan == nil {
				t.Fatalf("expected %s scope plan, got %#v", scope, got)
			}
			for _, want := range wantCommands {
				if !containsString(got.ScopePlan.CommandSuggestions, want) {
					t.Fatalf("%s scope commands = %#v, want %q", scope, got.ScopePlan.CommandSuggestions, want)
				}
			}
			if len(got.ScopePlan.DocsQueries) == 0 {
				t.Fatalf("%s scope should include docs lookup topics", scope)
			}
			if strings.Contains(stdout, "STRADDLE_TOKEN=") || strings.Contains(stdout, "Bearer ") {
				t.Fatalf("smoke plan should not emit token literals or bearer examples:\n%s", stdout)
			}
		})
	}
}

func TestSmokePlanCommandSuggestionsResolveToRealCommands(t *testing.T) {
	root := newRootCmd(&rootFlags{})
	for _, plan := range smokeScopePlans() {
		t.Run(plan.Name, func(t *testing.T) {
			for _, suggestion := range plan.CommandSuggestions {
				path := commandPathFromSuggestion(t, suggestion)
				cmd, _, err := root.Find(path)
				if err != nil {
					t.Fatalf("suggestion %q did not resolve: %v", suggestion, err)
				}
				if cmd == nil {
					t.Fatalf("suggestion %q resolved to nil command", suggestion)
				}
				if cmd.Run == nil && cmd.RunE == nil {
					t.Fatalf("suggestion %q resolved to %q without executable behavior", suggestion, cmd.CommandPath())
				}
			}
		})
	}
}

func TestSmokePlanApprovalIncludesApprovalPacketFields(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", "approval", "--json")
	if err != nil {
		t.Fatalf("smoke plan approval --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke plan approval wrote stderr: %q", stderr)
	}

	var got smokePlanResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke plan approval --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Scope != "approval" || got.ScopePlan == nil {
		t.Fatalf("expected approval scope plan, got %#v", got)
	}

	plan := got.ScopePlan
	if plan.ApprovalPacketFields == nil {
		t.Fatalf("approval scope should include approval packet fields: %#v", plan)
	}
	if plan.ApprovalPacketFields.TargetEnvironmentAndBaseURLClassification == "" {
		t.Fatalf("approval packet should require target environment and base URL classification: %#v", plan.ApprovalPacketFields)
	}
	if plan.ApprovalPacketFields.CredentialSourceAndSecureSecretFlow == "" {
		t.Fatalf("approval packet should require credential source and secure secret flow: %#v", plan.ApprovalPacketFields)
	}
	if !containsString(plan.ApprovalPacketFields.AllowedScopeOrCommands, "read-only only") {
		t.Fatalf("approval packet should require read-only allowed scope or commands: %#v", plan.ApprovalPacketFields.AllowedScopeOrCommands)
	}
	if plan.ApprovalPacketFields.TranscriptArtifactPath == "" {
		t.Fatalf("approval packet should require transcript artifact path: %#v", plan.ApprovalPacketFields)
	}
	if plan.ApprovalPacketFields.ReviewerSignoff == "" {
		t.Fatalf("approval packet should require reviewer signoff: %#v", plan.ApprovalPacketFields)
	}
	if plan.ExpectedEvidence == nil {
		t.Fatalf("approval scope should include expected evidence: %#v", plan)
	}
	if plan.ExpectedEvidence.RedactedCommand == "" || plan.ExpectedEvidence.ExitCode == "" || plan.ExpectedEvidence.EndpointOrToolName == "" {
		t.Fatalf("approval expected evidence should require redacted command, exit code, and endpoint or tool name: %#v", plan.ExpectedEvidence)
	}
	if plan.ExpectedEvidence.EnvironmentClassification == "" || plan.ExpectedEvidence.ObjectCountOrEmptyListProof == "" || plan.ExpectedEvidence.NoTokenExposure == "" {
		t.Fatalf("approval expected evidence should require environment classification, object count or empty-list proof, and no token exposure: %#v", plan.ExpectedEvidence)
	}
	if len(plan.StopCriteria) < 7 {
		t.Fatalf("approval scope should include stop criteria, got %#v", plan.StopCriteria)
	}
	for _, want := range []string{"production URL unexpectedly", "write-looking operation", "token printed", "prompt for token literal", "401/403 after one retry", "HTTP 5xx", "not safely shareable"} {
		if !containsSubstring(plan.StopCriteria, want) {
			t.Fatalf("approval stop criteria = %#v, want substring %q", plan.StopCriteria, want)
		}
	}
	if plan.TranscriptGuidance == nil || plan.TranscriptGuidance.ArtifactPath == "" || plan.TranscriptGuidance.Redaction == "" || plan.TranscriptGuidance.Shareability == "" {
		t.Fatalf("approval scope should include transcript guidance: %#v", plan.TranscriptGuidance)
	}
	if strings.Contains(stdout, "STRADDLE_TOKEN=") || strings.Contains(stdout, "Bearer ") {
		t.Fatalf("approval scope should not emit token literals or bearer examples:\n%s", stdout)
	}
}

func TestSmokePlanApprovalTerminalRendersApprovalDetails(t *testing.T) {
	restoreTerminal := forceTerminalForSmokePlanTest(t)
	defer restoreTerminal()

	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", "approval")
	if err != nil {
		t.Fatalf("smoke plan approval returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke plan approval wrote stderr: %q", stderr)
	}

	for _, want := range []string{
		"Smoke plan: approval",
		"Local proof commands:",
		"straddle-pp-cli smoke plan setup --json",
		"straddle-pp-cli smoke plan customers --json",
		"straddle-pp-cli docs search sandbox --source commands --json",
		"Approval packet fields:",
		"target_environment_and_base_url_classification",
		"credential_source_and_secure_secret_flow",
		"allowed_scope_or_commands",
		"read-only only",
		"transcript_artifact_path",
		"reviewer_signoff",
		"Expected evidence:",
		"redacted_command",
		"exit_code",
		"endpoint_or_tool_name",
		"environment_classification",
		"object_count_or_empty_list_proof",
		"no_token_exposure",
		"Stop criteria:",
		"production URL unexpectedly",
		"write-looking operation",
		"token printed",
		"401/403 after one retry",
		"HTTP 5xx",
		"not safely shareable",
		"Transcript guidance:",
		"artifact_path",
		"redaction",
		"shareability",
	} {
		if !strings.Contains(stdout, want) {
			t.Fatalf("terminal output omitted %q:\n%s", want, stdout)
		}
	}
	if strings.Contains(stdout, "STRADDLE_TOKEN=") || strings.Contains(stdout, "Bearer ") {
		t.Fatalf("approval terminal output should not emit token literals or bearer examples:\n%s", stdout)
	}
}

func TestSmokePlanAllIncludesEveryScopePlan(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", "all", "--json")
	if err != nil {
		t.Fatalf("smoke plan all --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke plan all wrote stderr: %q", stderr)
	}

	var got smokePlanResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke plan all --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Scope != "all" {
		t.Fatalf("scope = %q, want all", got.Scope)
	}
	if len(got.ScopePlans) != 6 {
		t.Fatalf("all scope should include six concrete scope plans, got %d: %#v", len(got.ScopePlans), got.ScopePlans)
	}
	if got.ScopePlan != nil {
		t.Fatalf("all scope should use scope_plans, not scope_plan: %#v", got.ScopePlan)
	}
}

func TestSmokePlanInvalidScopeReturnsUsageError(t *testing.T) {
	_, _, err := runCLIForDocsTest(t, "smoke", "plan", "not-a-scope", "--json")
	if err == nil {
		t.Fatalf("smoke plan should reject invalid scopes")
	}
	var cliErr *cliError
	if !errors.As(err, &cliErr) || cliErr.code != 2 {
		t.Fatalf("invalid scope should be a usage error, got %#v", err)
	}
	if !strings.Contains(err.Error(), "supported scopes") {
		t.Fatalf("invalid scope error should list supported scopes, got %v", err)
	}
}

func TestSmokePlanAgentUsesTargetEnvelope(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", "payments", "--agent")
	if err != nil {
		t.Fatalf("smoke plan --agent returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke plan --agent wrote stderr: %q", stderr)
	}

	var got struct {
		SchemaVersion string `json:"schema_version"`
		Data          struct {
			Command   string          `json:"command"`
			Scope     string          `json:"scope"`
			ScopePlan *smokeScopePlan `json:"scope_plan"`
			Safety    smokeSafety     `json:"safety"`
		} `json:"data"`
		Warnings []string        `json:"warnings"`
		Results  json.RawMessage `json:"results"`
		Meta     json.RawMessage `json:"meta"`
	}
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke plan --agent emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.SchemaVersion != "1.0" {
		t.Fatalf("schema_version: want 1.0, got %q", got.SchemaVersion)
	}
	if got.Data.Command != "smoke plan" || got.Data.Scope != "payments" || got.Data.ScopePlan == nil {
		t.Fatalf("agent data should contain payments smoke plan: %#v", got.Data)
	}
	if !got.Data.Safety.GuidanceOnly || got.Data.Safety.MakesAPICalls || got.Data.Safety.ExecutesMCP || !got.Data.Safety.NoLiveExecutionInCommand {
		t.Fatalf("agent safety should remain local guidance only: %#v", got.Data.Safety)
	}
	if got.Warnings == nil {
		t.Fatalf("warnings should be an empty array, not null")
	}
	if got.Results != nil || got.Meta != nil {
		t.Fatalf("target envelope should not include top-level results/meta")
	}
}

func TestSmokePlanRejectsDeliverBeforeDelivery(t *testing.T) {
	target := filepath.Join(t.TempDir(), "smoke-plan-delivery.json")

	oldArgs := os.Args
	t.Cleanup(func() {
		os.Args = oldArgs
	})
	os.Args = []string{
		"straddle-pp-cli",
		"smoke",
		"plan",
		"--deliver",
		"file:" + target,
	}

	err := Execute()
	if err == nil {
		t.Fatalf("smoke plan should reject --deliver")
	}
	if !strings.Contains(err.Error(), "smoke plan does not support --deliver") {
		t.Fatalf("error should explain --deliver is unsupported, got %v", err)
	}
	if _, statErr := os.Stat(target); !os.IsNotExist(statErr) {
		t.Fatalf("smoke plan should reject --deliver before writing output, stat err=%v", statErr)
	}
}

func TestSmokeRunMissingApprovalFileReturnsUsageError(t *testing.T) {
	_, _, err := runCLIForDocsTest(t, "smoke", "run", "setup", "--json")
	if err == nil {
		t.Fatalf("smoke run should require --approval-file")
	}
	var cliErr *cliError
	if !errors.As(err, &cliErr) || cliErr.code != 2 {
		t.Fatalf("missing approval file should be a usage error, got %#v", err)
	}
	if !strings.Contains(err.Error(), "approval-file") {
		t.Fatalf("error should mention approval-file, got %v", err)
	}
}

func TestSmokeRunRejectsProductionBaseURL(t *testing.T) {
	approvalPath := writeSmokeApprovalFile(t, map[string]any{
		"base_url": "https://api.straddle.com",
	})

	_, _, err := runCLIForDocsTest(t, "smoke", "run", "setup", "--approval-file", approvalPath, "--json")
	if err == nil {
		t.Fatalf("smoke run should reject production-looking base URLs")
	}
	if !strings.Contains(err.Error(), "production") {
		t.Fatalf("error should explain production-looking base URL rejection, got %v", err)
	}
}

func TestSmokeRunRejectsScopeMismatch(t *testing.T) {
	approvalPath := writeSmokeApprovalFile(t, map[string]any{
		"allowed_scope": "customers",
	})

	_, _, err := runCLIForDocsTest(t, "smoke", "run", "setup", "--approval-file", approvalPath, "--json")
	if err == nil {
		t.Fatalf("smoke run should reject approval scope mismatch")
	}
	if !strings.Contains(err.Error(), "allowed_scope") {
		t.Fatalf("error should mention allowed_scope mismatch, got %v", err)
	}
}

func TestSmokeRunRejectsTokenLiteralInApprovalFile(t *testing.T) {
	tests := map[string]map[string]any{
		"authorization_header": {
			"authorization": "Bearer fixture-token-literal",
		},
		"plain_token_field": {
			"token": "fixture-token-literal",
		},
	}

	for name, overrides := range tests {
		t.Run(name, func(t *testing.T) {
			approvalPath := writeSmokeApprovalFile(t, overrides)

			_, _, err := runCLIForDocsTest(t, "smoke", "run", "setup", "--approval-file", approvalPath, "--json")
			if err == nil {
				t.Fatalf("smoke run should reject token literals in approval file")
			}
			if !strings.Contains(strings.ToLower(err.Error()), "token") {
				t.Fatalf("error should mention token literal rejection, got %v", err)
			}
		})
	}
}

func TestSmokeRunRejectsBaseURLWithCredentialBearingParts(t *testing.T) {
	tests := map[string]string{
		"fragment": "https://example.test#token",
		"query":    "https://example.test?page=1",
		"userinfo": "https://user:secret@example.test",
	}

	for name, baseURL := range tests {
		t.Run(name, func(t *testing.T) {
			approvalPath := writeSmokeApprovalFile(t, map[string]any{
				"base_url": baseURL,
			})

			_, _, err := runCLIForDocsTest(t, "smoke", "run", "setup", "--approval-file", approvalPath, "--json")
			if err == nil {
				t.Fatalf("smoke run should reject credential-bearing base_url %q", baseURL)
			}
			if !strings.Contains(err.Error(), "base_url") {
				t.Fatalf("error should mention base_url rejection, got %v", err)
			}
		})
	}
}

func TestSmokeRunRejectsUnsupportedFirstSliceScopes(t *testing.T) {
	approvalPath := writeSmokeApprovalFile(t, map[string]any{})

	for _, scope := range []string{"all", "payments", "funding"} {
		t.Run(scope, func(t *testing.T) {
			_, _, err := runCLIForDocsTest(t, "smoke", "run", scope, "--approval-file", approvalPath, "--json")
			if err == nil {
				t.Fatalf("smoke run should reject unsupported scope %q", scope)
			}
			if !strings.Contains(err.Error(), "supported run scopes are setup, customers, mcp") {
				t.Fatalf("error should list supported run scopes, got %v", err)
			}
		})
	}
}

func TestSmokeRunSetupDoesNotCallAPI(t *testing.T) {
	var requestCount int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestCount++
		t.Fatalf("setup smoke should not call API, got %s %s", r.Method, r.URL.Path)
	}))
	defer server.Close()

	transcriptPath := filepath.Join(t.TempDir(), "nested", "smoke", "setup-transcript.json")
	approvalPath := writeSmokeApprovalFile(t, map[string]any{
		"allowed_scope":   "setup",
		"base_url":        server.URL,
		"transcript_path": transcriptPath,
	})

	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "run", "setup", "--approval-file", approvalPath, "--json")
	if err != nil {
		t.Fatalf("smoke run setup returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke run setup wrote stderr: %q", stderr)
	}
	if requestCount != 0 {
		t.Fatalf("setup smoke should not call API, got %d requests", requestCount)
	}

	var got smokeRunResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke run setup --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "smoke run" || got.Scope != "setup" || !got.Approved || !got.ReadOnly {
		t.Fatalf("wrong setup smoke response: %#v", got)
	}
	if got.BaseURL != server.URL {
		t.Fatalf("base_url = %q, want %q", got.BaseURL, server.URL)
	}
	if len(got.Checks) != 1 || got.Checks[0].Name != "approval" || !got.Checks[0].Passed {
		t.Fatalf("setup smoke should report local approval check only: %#v", got.Checks)
	}
	if strings.Contains(stdout, "fixture-smoke-token") || strings.Contains(stdout, "Bearer ") {
		t.Fatalf("smoke run setup should not print token values:\n%s", stdout)
	}

	transcript := readSmokeTranscript(t, transcriptPath)
	if transcript.Command != "smoke run" || transcript.Scope != "setup" || transcript.Environment != "local-test" {
		t.Fatalf("setup transcript has wrong command evidence: %#v", transcript)
	}
	if transcript.BaseURL != server.URL || transcript.CredentialSource != "env:STRADDLE_TOKEN" || transcript.TranscriptPath != transcriptPath {
		t.Fatalf("setup transcript has wrong redacted approval evidence: %#v", transcript)
	}
	if len(transcript.Checks) != 1 || transcript.Checks[0].Name != "approval" || !transcript.Checks[0].Passed {
		t.Fatalf("setup transcript should include approval check: %#v", transcript.Checks)
	}
	assertSmokeTranscriptRedacted(t, transcriptPath)
	assertSmokeTranscriptMode(t, transcriptPath)
	assertSmokeTranscriptDirMode(t, filepath.Dir(transcriptPath))
}

func TestSmokeRunCustomersUsesLocalApprovedBaseURL(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "fixture-smoke-token")

	var requestCount int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestCount++
		if r.Method != http.MethodGet {
			t.Fatalf("method: want GET, got %s", r.Method)
		}
		if r.URL.Path != "/v1/customers" {
			t.Fatalf("path: want /v1/customers, got %s", r.URL.Path)
		}
		if got := r.Header.Get("Authorization"); got != "Bearer fixture-smoke-token" {
			t.Fatalf("Authorization header was not set from STRADDLE_TOKEN, got %q", got)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"data":[{"id":"customer_123","name":"Fixture Customer"}]}`))
	}))
	defer server.Close()

	transcriptPath := filepath.Join(t.TempDir(), "nested", "customers", "smoke-transcript.json")
	approvalPath := writeSmokeApprovalFile(t, map[string]any{
		"allowed_scope":   "customers",
		"base_url":        server.URL,
		"transcript_path": transcriptPath,
	})

	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "run", "customers", "--approval-file", approvalPath, "--json")
	if err != nil {
		t.Fatalf("smoke run customers returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke run customers wrote stderr: %q", stderr)
	}
	if requestCount != 1 {
		t.Fatalf("customers smoke request count: want 1, got %d", requestCount)
	}

	var got smokeRunResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke run customers --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "smoke run" || got.Scope != "customers" || !got.Approved || !got.ReadOnly {
		t.Fatalf("wrong customers smoke response: %#v", got)
	}
	if len(got.Checks) != 2 {
		t.Fatalf("customers smoke should report approval and customers list checks: %#v", got.Checks)
	}
	if got.Checks[1].Name != "customers_list" || got.Checks[1].Method != http.MethodGet || got.Checks[1].Path != "/v1/customers" || got.Checks[1].StatusCode != http.StatusOK {
		t.Fatalf("wrong customers list check: %#v", got.Checks[1])
	}
	if got.Checks[1].ObjectCount != 1 {
		t.Fatalf("object_count = %d, want 1", got.Checks[1].ObjectCount)
	}
	if strings.Contains(stdout, "fixture-smoke-token") || strings.Contains(stdout, "Bearer ") {
		t.Fatalf("smoke run customers should not print token values:\n%s", stdout)
	}

	transcript := readSmokeTranscript(t, transcriptPath)
	if transcript.Command != "smoke run" || transcript.Scope != "customers" || transcript.Environment != "local-test" {
		t.Fatalf("customers transcript has wrong command evidence: %#v", transcript)
	}
	if transcript.BaseURL != server.URL || transcript.CredentialSource != "env:STRADDLE_TOKEN" || transcript.TranscriptPath != transcriptPath {
		t.Fatalf("customers transcript has wrong redacted approval evidence: %#v", transcript)
	}
	if len(transcript.Checks) != 2 {
		t.Fatalf("customers transcript should report approval and customers list checks: %#v", transcript.Checks)
	}
	if transcript.Checks[1].Name != "customers_list" || !transcript.Checks[1].Passed || transcript.Checks[1].StatusCode != http.StatusOK || transcript.Checks[1].ObjectCount != 1 {
		t.Fatalf("customers transcript has wrong customers list check: %#v", transcript.Checks[1])
	}
	assertSmokeTranscriptRedacted(t, transcriptPath)
	assertSmokeTranscriptMode(t, transcriptPath)
	assertSmokeTranscriptDirMode(t, filepath.Dir(transcriptPath))
}

func TestSmokeRunCustomersWritesFailedTranscriptBeforeReturningError(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "fixture-smoke-token")

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Fatalf("method: want GET, got %s", r.Method)
		}
		if r.URL.Path != "/v1/customers" {
			t.Fatalf("path: want /v1/customers, got %s", r.URL.Path)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusServiceUnavailable)
		_, _ = w.Write([]byte(`{"error":"temporary fixture failure","token":"not a real token"}`))
	}))
	defer server.Close()

	transcriptPath := filepath.Join(t.TempDir(), "failed", "customers", "smoke-transcript.json")
	approvalPath := writeSmokeApprovalFile(t, map[string]any{
		"allowed_scope":   "customers",
		"base_url":        server.URL,
		"transcript_path": transcriptPath,
	})

	_, _, err := runCLIForDocsTest(t, "smoke", "run", "customers", "--approval-file", approvalPath, "--json")
	if err == nil {
		t.Fatalf("smoke run customers should return an error for non-2xx responses")
	}
	if !strings.Contains(err.Error(), "HTTP 503") {
		t.Fatalf("non-2xx error should mention status code, got %v", err)
	}

	transcript := readSmokeTranscript(t, transcriptPath)
	if transcript.Command != "smoke run" || transcript.Scope != "customers" || transcript.BaseURL != server.URL {
		t.Fatalf("failed customers transcript has wrong run evidence: %#v", transcript)
	}
	if len(transcript.Checks) != 2 {
		t.Fatalf("failed customers transcript should include approval and customers list checks: %#v", transcript.Checks)
	}
	failedCheck := transcript.Checks[1]
	if failedCheck.Name != "customers_list" || failedCheck.Passed || failedCheck.StatusCode != http.StatusServiceUnavailable {
		t.Fatalf("failed customers transcript should contain failed customers_list check: %#v", failedCheck)
	}
	if failedCheck.ObjectCount != 0 {
		t.Fatalf("failed customers transcript should not persist response body data, got object_count %d", failedCheck.ObjectCount)
	}
	assertSmokeTranscriptRedacted(t, transcriptPath)
	assertSmokeTranscriptMode(t, transcriptPath)
	assertSmokeTranscriptDirMode(t, filepath.Dir(transcriptPath))
}

func TestSmokeRunMCPSucceedsAgainstFakeMCPAndWritesTranscript(t *testing.T) {
	for _, item := range []struct {
		key   string
		value string
	}{
		{key: "TOKEN", value: "fixture-token"},
		{key: "SECRET", value: "fixture-secret"},
		{key: "API_KEY", value: "fixture-api-key"},
		{key: "AWS_ACCESS_KEY_ID", value: "fixture-aws-access-key-id"},
		{key: "AWS_SECRET_ACCESS_KEY", value: "fixture-aws-secret-access-key"},
		{key: "STRADDLE_TOKEN", value: "fixture-smoke-token"},
	} {
		t.Setenv(item.key, item.value)
	}

	mcpBinary := writeFakeMCPBinary(t, []string{"mcp_config", "smoke_run", "setup_check"})
	transcriptPath := filepath.Join(t.TempDir(), "nested", "mcp", "smoke-transcript.json")
	approvalPath := writeSmokeApprovalFile(t, map[string]any{
		"allowed_scope":     "mcp",
		"base_url":          "http://127.0.0.1:1",
		"credential_source": "none",
		"transcript_path":   transcriptPath,
	})

	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "run", "mcp", "--approval-file", approvalPath, "--mcp-binary", mcpBinary, "--json")
	if err != nil {
		t.Fatalf("smoke run mcp returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke run mcp wrote stderr: %q", stderr)
	}

	var got smokeRunResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke run mcp --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "smoke run" || got.Scope != "mcp" || !got.Approved || !got.ReadOnly {
		t.Fatalf("wrong mcp smoke response: %#v", got)
	}
	if len(got.Checks) != 2 {
		t.Fatalf("mcp smoke should report approval and MCP tools/list checks: %#v", got.Checks)
	}
	check := got.Checks[1]
	if check.Name != "mcp_tools_list" || !check.Passed || check.Method != "tools/list" || check.Path != "stdio" || check.ToolCount != 3 {
		t.Fatalf("wrong MCP tools/list check: %#v", check)
	}
	if !strings.Contains(check.Note, "local stdio MCP") || !strings.Contains(check.Note, "no Straddle API call") {
		t.Fatalf("MCP check should clearly be local stdio and not an API call: %#v", check)
	}
	if strings.Contains(stdout, "fixture-smoke-token") || strings.Contains(stdout, "Bearer ") {
		t.Fatalf("smoke run mcp should not print token values:\n%s", stdout)
	}

	transcript := readSmokeTranscript(t, transcriptPath)
	if transcript.Command != "smoke run" || transcript.Scope != "mcp" || transcript.Environment != "local-test" {
		t.Fatalf("mcp transcript has wrong command evidence: %#v", transcript)
	}
	if transcript.BaseURL != "http://127.0.0.1:1" || transcript.CredentialSource != "none" || transcript.TranscriptPath != transcriptPath {
		t.Fatalf("mcp transcript has wrong redacted approval evidence: %#v", transcript)
	}
	if len(transcript.Checks) != 2 || transcript.Checks[1].Name != "mcp_tools_list" || !transcript.Checks[1].Passed || transcript.Checks[1].ToolCount != 3 {
		t.Fatalf("mcp transcript has wrong tools/list evidence: %#v", transcript.Checks)
	}
	assertSmokeTranscriptRedacted(t, transcriptPath)
	assertSmokeTranscriptMode(t, transcriptPath)
	assertSmokeTranscriptDirMode(t, filepath.Dir(transcriptPath))
}

func TestSmokeRunMCPMissingRequiredToolsFailsAndWritesTranscript(t *testing.T) {
	tests := []struct {
		name  string
		tools []string
		want  string
	}{
		{
			name:  "missing mcp_config",
			tools: []string{"smoke_run", "setup_check"},
			want:  "mcp_config",
		},
		{
			name:  "missing smoke_run",
			tools: []string{"mcp_config", "setup_check"},
			want:  "smoke_run",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mcpBinary := writeFakeMCPBinary(t, tt.tools)
			transcriptPath := filepath.Join(t.TempDir(), "failed", "mcp", "smoke-transcript.json")
			approvalPath := writeSmokeApprovalFile(t, map[string]any{
				"allowed_scope":     "mcp",
				"credential_source": "none",
				"transcript_path":   transcriptPath,
			})

			stdout, _, err := runCLIForDocsTest(t, "smoke", "run", "mcp", "--approval-file", approvalPath, "--mcp-binary", mcpBinary, "--json")
			if err == nil {
				t.Fatalf("smoke run mcp should fail when %s is missing", tt.want)
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("mcp missing-tool error should mention %s, got %v", tt.want, err)
			}
			if strings.Contains(stdout, "fixture-smoke-token") || strings.Contains(stdout, "Bearer ") {
				t.Fatalf("smoke run mcp failure should not print token values:\n%s", stdout)
			}

			transcript := readSmokeTranscript(t, transcriptPath)
			if transcript.Command != "smoke run" || transcript.Scope != "mcp" {
				t.Fatalf("failed mcp transcript has wrong run evidence: %#v", transcript)
			}
			if len(transcript.Checks) != 2 {
				t.Fatalf("failed mcp transcript should include approval and MCP tools/list checks: %#v", transcript.Checks)
			}
			failedCheck := transcript.Checks[1]
			if failedCheck.Name != "mcp_tools_list" || failedCheck.Passed || failedCheck.Method != "tools/list" || failedCheck.Path != "stdio" || failedCheck.ToolCount != len(tt.tools) {
				t.Fatalf("failed mcp transcript should contain failed tools/list check: %#v", failedCheck)
			}
			if !strings.Contains(failedCheck.Note, tt.want) {
				t.Fatalf("failed mcp transcript note should mention %s: %#v", tt.want, failedCheck)
			}
			assertSmokeTranscriptRedacted(t, transcriptPath)
			assertSmokeTranscriptMode(t, transcriptPath)
			assertSmokeTranscriptDirMode(t, filepath.Dir(transcriptPath))
		})
	}
}

func TestSmokeRunMCPRejectsUnsafeBinaryInputs(t *testing.T) {
	approvalPath := writeSmokeApprovalFile(t, map[string]any{"allowed_scope": "mcp"})
	tests := []struct {
		name   string
		binary string
		want   string
	}{
		{
			name:   "blank",
			binary: " ",
			want:   "mcp binary must not be blank",
		},
		{
			name:   "token literal",
			binary: "Bearer fixture-secret-token",
			want:   "mcp binary must not contain token literals",
		},
		{
			name:   "straddle token env assignment",
			binary: "STRADDLE_TOKEN=fixture-secret-token straddle-pp-mcp",
			want:   "mcp binary must not contain secret environment assignments",
		},
		{
			name:   "generic secret env assignment",
			binary: "CUSTOM_SECRET=fixture-secret straddle-pp-mcp",
			want:   "mcp binary must not contain secret environment assignments",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			stdout, _, err := runCLIForDocsTest(t, "smoke", "run", "mcp", "--approval-file", approvalPath, "--mcp-binary", tt.binary, "--json")
			if err == nil {
				t.Fatalf("smoke run mcp should reject %s binary", tt.name)
			}
			var cliErr *cliError
			if !errors.As(err, &cliErr) || cliErr.code != 2 {
				t.Fatalf("%s should be a usage error, got %#v", tt.name, err)
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("%s error should contain %q, got %v", tt.name, tt.want, err)
			}
			if strings.Contains(stdout, "fixture-secret-token") || strings.Contains(stdout, "Bearer ") {
				t.Fatalf("unsafe binary rejection should not print token values:\n%s", stdout)
			}
		})
	}
}

func TestSmokeRunRewritesPermissiveTranscriptWithPrivateMode(t *testing.T) {
	transcriptPath := filepath.Join(t.TempDir(), "existing-transcript.json")
	if err := os.WriteFile(transcriptPath, []byte(`{"old":true}`), 0o644); err != nil {
		t.Fatalf("write existing permissive transcript: %v", err)
	}
	if err := os.Chmod(transcriptPath, 0o644); err != nil {
		t.Fatalf("set existing permissive transcript mode: %v", err)
	}

	approvalPath := writeSmokeApprovalFile(t, map[string]any{
		"allowed_scope":   "setup",
		"transcript_path": transcriptPath,
	})

	_, _, err := runCLIForDocsTest(t, "smoke", "run", "setup", "--approval-file", approvalPath, "--json")
	if err != nil {
		t.Fatalf("smoke run setup returned error: %v", err)
	}

	transcript := readSmokeTranscript(t, transcriptPath)
	if transcript.Command != "smoke run" || transcript.Scope != "setup" {
		t.Fatalf("rewritten transcript has wrong smoke evidence: %#v", transcript)
	}
	assertSmokeTranscriptMode(t, transcriptPath)
}

func TestSmokeRunCustomersDoesNotSendEnvTokenToUntrustedApprovedBaseURL(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "fixture-smoke-token")

	var authorization string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		authorization = r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"data":[]}`))
	}))
	defer server.Close()

	approvalPath := writeSmokeApprovalFile(t, map[string]any{
		"allowed_scope":     "customers",
		"base_url":          "http://" + server.Listener.Addr().String(),
		"credential_source": "manual-approved-fixture",
	})

	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "run", "customers", "--approval-file", approvalPath, "--json")
	if err != nil {
		t.Fatalf("smoke run customers returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke run customers wrote stderr: %q", stderr)
	}
	if authorization != "" {
		t.Fatalf("customers smoke should not forward STRADDLE_TOKEN unless credential_source and trusted host allow it, got %q", authorization)
	}
	if strings.Contains(stdout, "fixture-smoke-token") || strings.Contains(stdout, "Bearer ") {
		t.Fatalf("smoke run customers should not print token values:\n%s", stdout)
	}
}

func TestSmokeRunEnvTokenRequiresEnvSourceAndTrustedBaseURL(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "fixture-smoke-token")

	tests := []struct {
		name     string
		approval smokeApprovalFile
		want     string
	}{
		{
			name: "trusted sandbox env source",
			approval: smokeApprovalFile{
				BaseURL:          "https://sandbox.straddle.com",
				CredentialSource: "env:STRADDLE_TOKEN",
			},
			want: "fixture-smoke-token",
		},
		{
			name: "http sandbox env source",
			approval: smokeApprovalFile{
				BaseURL:          "http://sandbox.straddle.com",
				CredentialSource: "env:STRADDLE_TOKEN",
			},
		},
		{
			name: "custom host env source",
			approval: smokeApprovalFile{
				BaseURL:          "https://example.test",
				CredentialSource: "env:STRADDLE_TOKEN",
			},
		},
		{
			name: "trusted host non env source",
			approval: smokeApprovalFile{
				BaseURL:          "https://sandbox.straddle.com",
				CredentialSource: "manual-approved-fixture",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := smokeRunEnvToken(tc.approval); got != tc.want {
				t.Fatalf("smokeRunEnvToken() = %q, want %q", got, tc.want)
			}
		})
	}
}

func commandPathFromSuggestion(t *testing.T, suggestion string) []string {
	t.Helper()

	parts := strings.Fields(suggestion)
	if len(parts) == 0 {
		t.Fatalf("empty command suggestion")
	}
	if parts[0] != "straddle-pp-cli" {
		t.Fatalf("suggestion should start with straddle-pp-cli, got %q", suggestion)
	}

	var path []string
	for _, part := range parts[1:] {
		if strings.HasPrefix(part, "--") {
			break
		}
		path = append(path, part)
	}
	if len(path) == 0 {
		t.Fatalf("suggestion should include a command path, got %q", suggestion)
	}
	return path
}

func writeSmokeApprovalFile(t *testing.T, overrides map[string]any) string {
	t.Helper()

	approval := map[string]any{
		"approver":                   "Smoke Reviewer",
		"environment":                "local-test",
		"base_url":                   "http://127.0.0.1:1",
		"credential_source":          "env:STRADDLE_TOKEN",
		"allowed_scope":              "setup",
		"read_only":                  true,
		"transcript_path":            filepath.Join(t.TempDir(), "smoke-transcript.json"),
		"stop_criteria_acknowledged": true,
	}
	for key, value := range overrides {
		if value == nil {
			delete(approval, key)
			continue
		}
		approval[key] = value
	}

	data, err := json.Marshal(approval)
	if err != nil {
		t.Fatalf("marshal approval file: %v", err)
	}
	path := filepath.Join(t.TempDir(), "approval.json")
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatalf("write approval file: %v", err)
	}
	return path
}

func readSmokeTranscript(t *testing.T, path string) smokeRunResponse {
	t.Helper()

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read smoke transcript: %v", err)
	}
	var got smokeRunResponse
	if err := json.Unmarshal(raw, &got); err != nil {
		t.Fatalf("smoke transcript should be valid JSON: %v\n%s", err, string(raw))
	}
	return got
}

func writeFakeMCPBinary(t *testing.T, toolNames []string) string {
	t.Helper()

	exe, err := os.Executable()
	if err != nil {
		t.Fatalf("resolve test executable: %v", err)
	}

	path := filepath.Join(t.TempDir(), fakeMCPBinaryName())
	source, err := os.Open(exe)
	if err != nil {
		t.Fatalf("open test executable: %v", err)
	}
	defer source.Close()
	target, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o700)
	if err != nil {
		t.Fatalf("create fake MCP binary: %v", err)
	}
	if _, err := io.Copy(target, source); err != nil {
		_ = target.Close()
		t.Fatalf("copy test executable to fake MCP binary: %v", err)
	}
	if err := target.Close(); err != nil {
		t.Fatalf("close fake MCP binary: %v", err)
	}
	if err := os.Chmod(path, 0o700); err != nil {
		t.Fatalf("chmod fake MCP binary: %v", err)
	}

	config := struct {
		Tools []string `json:"tools"`
	}{
		Tools: toolNames,
	}
	data, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("marshal fake MCP config: %v", err)
	}
	if err := os.WriteFile(path+".json", data, 0o600); err != nil {
		t.Fatalf("write fake MCP config: %v", err)
	}
	return path
}

func fakeMCPBinaryName() string {
	if runtime.GOOS == "windows" {
		return fakeMCPBinaryPrefix + ".exe"
	}
	return fakeMCPBinaryPrefix
}

func isFakeMCPHelperProcess() bool {
	return strings.HasPrefix(filepath.Base(os.Args[0]), fakeMCPBinaryPrefix)
}

func runFakeMCPHelperProcess() int {
	for _, key := range []string{"TOKEN", "SECRET", "API_KEY", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "STRADDLE_TOKEN"} {
		if _, ok := os.LookupEnv(key); ok {
			_, _ = io.WriteString(os.Stderr, key+" leaked to fake MCP\n")
			return 42
		}
	}

	raw, err := os.ReadFile(os.Args[0] + ".json")
	if err != nil {
		_, _ = io.WriteString(os.Stderr, "read fake MCP config: "+err.Error()+"\n")
		return 1
	}
	var config struct {
		Tools []string `json:"tools"`
	}
	if err := json.Unmarshal(raw, &config); err != nil {
		_, _ = io.WriteString(os.Stderr, "decode fake MCP config: "+err.Error()+"\n")
		return 1
	}

	decoder := json.NewDecoder(os.Stdin)
	encoder := json.NewEncoder(os.Stdout)

	if !fakeMCPReadMethod(decoder, "initialize") {
		return 1
	}
	if err := encoder.Encode(map[string]any{
		"jsonrpc": "2.0",
		"id":      1,
		"result": map[string]any{
			"protocolVersion": "2024-11-05",
			"capabilities": map[string]any{
				"tools": map[string]any{},
			},
			"serverInfo": map[string]string{
				"name":    "fake-straddle-pp-mcp",
				"version": "0",
			},
		},
	}); err != nil {
		_, _ = io.WriteString(os.Stderr, "write fake MCP initialize response: "+err.Error()+"\n")
		return 1
	}
	if !fakeMCPReadMethod(decoder, "notifications/initialized") {
		return 1
	}
	if !fakeMCPReadMethod(decoder, "tools/list") {
		return 1
	}

	tools := make([]map[string]string, 0, len(config.Tools))
	for _, name := range config.Tools {
		tools = append(tools, map[string]string{"name": name})
	}
	if err := encoder.Encode(map[string]any{
		"jsonrpc": "2.0",
		"id":      2,
		"result": map[string]any{
			"tools": tools,
		},
	}); err != nil {
		_, _ = io.WriteString(os.Stderr, "write fake MCP tools/list response: "+err.Error()+"\n")
		return 1
	}
	return 0
}

func fakeMCPReadMethod(decoder *json.Decoder, want string) bool {
	var request struct {
		Method string `json:"method"`
	}
	if err := decoder.Decode(&request); err != nil {
		_, _ = io.WriteString(os.Stderr, "read fake MCP "+want+" request: "+err.Error()+"\n")
		return false
	}
	if request.Method != want {
		_, _ = io.WriteString(os.Stderr, "fake MCP got method "+request.Method+", want "+want+"\n")
		return false
	}
	return true
}

func assertSmokeTranscriptRedacted(t *testing.T, path string) {
	t.Helper()

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read smoke transcript for redaction check: %v", err)
	}
	content := string(raw)
	for _, forbidden := range []string{"fixture-smoke-token", "Bearer ", "temporary fixture failure", "not a real token"} {
		if strings.Contains(content, forbidden) {
			t.Fatalf("smoke transcript should not contain %q:\n%s", forbidden, content)
		}
	}
}

func assertSmokeTranscriptMode(t *testing.T, path string) {
	t.Helper()

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat smoke transcript: %v", err)
	}
	if got := info.Mode().Perm(); got != 0o600 {
		t.Fatalf("smoke transcript mode = %v, want 0600", got)
	}
}

func assertSmokeTranscriptDirMode(t *testing.T, path string) {
	t.Helper()

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat smoke transcript directory: %v", err)
	}
	if got := info.Mode().Perm(); got != 0o700 {
		t.Fatalf("smoke transcript directory mode = %v, want 0700", got)
	}
}

func containsSubstring(items []string, want string) bool {
	for _, item := range items {
		if strings.Contains(item, want) {
			return true
		}
	}
	return false
}

func forceTerminalForSmokePlanTest(t *testing.T) func() {
	t.Helper()

	old := isTerminalWriter
	isTerminalWriter = func(io.Writer) bool {
		return true
	}
	return func() {
		isTerminalWriter = old
	}
}
