// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCH: smoke-plan adds local-only approved live-smoke planning guidance without live execution.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

type smokeSafety struct {
	GuidanceOnly                        bool   `json:"guidance_only"`
	LocalOnly                           bool   `json:"local_only"`
	MakesAPICalls                       bool   `json:"makes_api_calls"`
	CallsDocsEndpoint                   bool   `json:"calls_docs_endpoint"`
	ExecutesMCP                         bool   `json:"executes_mcp"`
	PostsWebhook                        bool   `json:"posts_webhook"`
	WritesSandbox                       bool   `json:"writes_sandbox"`
	WritesProduction                    bool   `json:"writes_production"`
	RequiresExplicitApproval            bool   `json:"requires_explicit_approval"`
	RequiresSandboxOrApprovedCredential bool   `json:"requires_sandbox_or_approved_credential"`
	RequiresCredentialThroughSecureFlow bool   `json:"requires_credential_through_secure_flow"`
	ReadOnlyIntendedCommandsOnly        bool   `json:"read_only_intended_commands_only"`
	NoWrites                            bool   `json:"no_writes"`
	NoTokenLiterals                     bool   `json:"no_token_literals"`
	NoLiveExecutionInCommand            bool   `json:"no_live_execution_in_command"`
	CredentialGuidance                  string `json:"credential_guidance"`
	ApprovalGuidance                    string `json:"approval_guidance"`
}

type smokeScopePlan struct {
	Name               string   `json:"name"`
	Title              string   `json:"title"`
	Summary            string   `json:"summary"`
	ApprovalChecklist  []string `json:"approval_checklist"`
	DocsQueries        []string `json:"docs_queries"`
	CommandSuggestions []string `json:"command_suggestions"`
	MCPGuidance        []string `json:"mcp_guidance,omitempty"`
}

type smokePlanResponse struct {
	Command               string           `json:"command"`
	Scope                 string           `json:"scope,omitempty"`
	AvailableScopes       []string         `json:"available_scopes,omitempty"`
	ScopePlan             *smokeScopePlan  `json:"scope_plan,omitempty"`
	ScopePlans            []smokeScopePlan `json:"scope_plans,omitempty"`
	Safety                smokeSafety      `json:"safety"`
	RunbookPurpose        string           `json:"runbook_purpose"`
	DocsLookupInstruction string           `json:"docs_lookup_instruction"`
}

func newSmokeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "smoke",
		Short: "Plan approved read-only live smoke checks",
		Long:  "Plan approved read-only live smoke checks without calling Straddle APIs, docs endpoints, MCP, webhooks, sandbox, or production.",
	}
	cmd.AddCommand(newSmokePlanCmd(flags))
	return cmd
}

func newSmokePlanCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "plan [scope]",
		Short: "Generate a local-only live-smoke runbook",
		Long: `Generate a local-only runbook for a future approved read-only live smoke.

This command is guidance-only. It does not call Straddle APIs, does not call docs endpoints, does not execute MCP tools, does not post webhooks, and does not touch sandbox or production.`,
		Example: `  straddle-pp-cli smoke plan
  straddle-pp-cli smoke plan all --json
  straddle-pp-cli smoke plan customers --agent`,
		Annotations: map[string]string{
			"mcp:read-only": "true",
		},
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if flags.deliverSpec != "" {
				return usageErr(fmt.Errorf("smoke plan does not support --deliver; use normal stdout, JSON, or agent output"))
			}

			scope := ""
			if len(args) == 1 {
				scope = strings.ToLower(strings.TrimSpace(args[0]))
			}
			payload, err := buildSmokePlanResponse(scope)
			if err != nil {
				return usageErr(err)
			}
			return renderSmokePlanResponse(cmd, flags, payload)
		},
	}
	return cmd
}

func buildSmokePlanResponse(scope string) (smokePlanResponse, error) {
	payload := smokePlanResponse{
		Command:         "smoke plan",
		AvailableScopes: smokeScopeNames(),
		Safety: smokeSafety{
			GuidanceOnly:                        true,
			LocalOnly:                           true,
			MakesAPICalls:                       false,
			CallsDocsEndpoint:                   false,
			ExecutesMCP:                         false,
			PostsWebhook:                        false,
			WritesSandbox:                       false,
			WritesProduction:                    false,
			RequiresExplicitApproval:            true,
			RequiresSandboxOrApprovedCredential: true,
			RequiresCredentialThroughSecureFlow: true,
			ReadOnlyIntendedCommandsOnly:        true,
			NoWrites:                            true,
			NoTokenLiterals:                     true,
			NoLiveExecutionInCommand:            true,
			CredentialGuidance:                  "Future live smoke requires a sandbox or approved environment credential supplied through the caller's secure secret flow. Do not paste, log, or pass token literals in argv.",
			ApprovalGuidance:                    "Get explicit approval for the environment, credential scope, and read-only command list before running any live smoke.",
		},
		RunbookPurpose:        "Prepare a future approved read-only smoke run. This command only prints the plan.",
		DocsLookupInstruction: "Review the docs lookup topics manually before live execution to verify current fields, statuses, pagination, and MCP behavior. This command does not perform docs lookup.",
	}
	if scope == "" {
		return payload, nil
	}
	if scope == "all" {
		payload.Scope = scope
		payload.ScopePlans = smokeScopePlans()
		return payload, nil
	}
	plan, ok := smokeScopePlanByName(scope)
	if !ok {
		return payload, fmt.Errorf("invalid smoke scope %q: supported scopes are %s", scope, strings.Join(smokeScopeNames(), ", "))
	}
	payload.Scope = plan.Name
	payload.ScopePlan = &plan
	return payload, nil
}

func renderSmokePlanResponse(cmd *cobra.Command, flags *rootFlags, payload smokePlanResponse) error {
	asJSON := flags.asJSON || flags.agent || !isTerminal(cmd.OutOrStdout())
	if asJSON {
		return printJSONFiltered(cmd.OutOrStdout(), payload, flags)
	}

	w := cmd.OutOrStdout()
	if payload.Scope == "" {
		fmt.Fprintln(w, "Smoke plan")
		fmt.Fprintln(w, "Safety: local guidance only, no API calls, no docs calls, no MCP execution, no sandbox or production access.")
		fmt.Fprintln(w, "Live smoke later requires explicit approval and a sandbox or approved credential through a secure secret flow.")
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Scopes:")
		for _, scope := range payload.AvailableScopes {
			fmt.Fprintf(w, "  %s\n", scope)
		}
		return nil
	}
	if payload.Scope == "all" {
		fmt.Fprintln(w, "Smoke plan: all")
		fmt.Fprintln(w, "Safety: local guidance only. Future live execution requires explicit approval and read-only commands.")
		for _, plan := range payload.ScopePlans {
			fmt.Fprintf(w, "  %s - %s\n", plan.Name, plan.Summary)
		}
		return nil
	}

	plan := payload.ScopePlan
	fmt.Fprintf(w, "Smoke plan: %s\n", plan.Name)
	fmt.Fprintln(w, "Safety: local guidance only. No live execution happens here.")
	fmt.Fprintln(w, "Suggested commands:")
	for _, suggestion := range plan.CommandSuggestions {
		fmt.Fprintf(w, "  %s\n", suggestion)
	}
	if len(plan.MCPGuidance) > 0 {
		fmt.Fprintln(w, "MCP guidance:")
		for _, guidance := range plan.MCPGuidance {
			fmt.Fprintf(w, "  %s\n", guidance)
		}
	}
	return nil
}

func smokeScopeNames() []string {
	return []string{"setup", "customers", "payments", "funding", "mcp", "all"}
}

func smokeScopePlanByName(name string) (smokeScopePlan, bool) {
	for _, plan := range smokeScopePlans() {
		if plan.Name == name {
			return plan, true
		}
	}
	return smokeScopePlan{}, false
}

func smokeScopePlans() []smokeScopePlan {
	return []smokeScopePlan{
		{
			Name:    "setup",
			Title:   "Setup readiness",
			Summary: "Confirm local configuration, environment classification, auth source, and MCP sibling presence before any live read.",
			ApprovalChecklist: []string{
				"Explicit approval names the target environment.",
				"Credential is supplied through a secure secret flow.",
				"No token literal appears in commands, docs, logs, or argv.",
			},
			DocsQueries: []string{
				"authentication environments sandbox production base url",
				"pagination response structure customers charges payouts funding events",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
			},
		},
		{
			Name:    "customers",
			Title:   "Customer read smoke",
			Summary: "Plan read-only customer listing and current docs verification.",
			ApprovalChecklist: []string{
				"Explicit approval allows read-only customer listing.",
				"Credential scope is sandbox or another approved non-production read scope unless approval says otherwise.",
				"Only list or dry-run command shapes are used.",
			},
			DocsQueries: []string{
				"customers list search filters pagination",
				"customer status identity verification status details",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli customers list --dry-run --agent",
			},
		},
		{
			Name:    "payments",
			Title:   "Payment read smoke",
			Summary: "Plan read-only charge and payout list checks without creating or changing payments.",
			ApprovalChecklist: []string{
				"Explicit approval allows read-only charge and payout listing.",
				"Payment writes such as create, update, cancel, hold, release, and resubmit are out of scope.",
				"Dry-run request-shape checks happen before any approved live reads.",
			},
			DocsQueries: []string{
				"charges list filters status pagination",
				"payouts list filters status pagination",
				"payment status lifecycle charge payout",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli payments --dry-run --agent",
			},
		},
		{
			Name:    "funding",
			Title:   "Funding event read smoke",
			Summary: "Plan read-only funding event listing and reconciliation field checks.",
			ApprovalChecklist: []string{
				"Explicit approval allows read-only funding event listing.",
				"Settlement and reconciliation checks do not post webhooks or run write commands.",
				"Dry-run request-shape checks happen before any approved live reads.",
			},
			DocsQueries: []string{
				"funding events list filters reconciliation settlement",
				"funding event status charge payout relationship",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli funding-events list --dry-run --agent",
			},
		},
		{
			Name:    "mcp",
			Title:   "MCP tools/list smoke",
			Summary: "Plan a credential-free MCP sibling tools/list check and confirm read-only shell-out metadata.",
			ApprovalChecklist: []string{
				"Explicit approval is required before using MCP tools against live credentials.",
				"Credential-free tools/list smoke is allowed as local process inspection.",
				"No MCP tool is called against Straddle APIs from this planning command.",
			},
			DocsQueries: []string{
				"MCP tools/list read only annotations shell out tools",
				"Straddle MCP setup local stdio tools list",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
			},
			MCPGuidance: []string{
				"Build the local straddle-pp-mcp sibling from this repo before smoke.",
				"Run a local JSON-RPC initialize plus tools/list smoke against the stdio MCP process.",
				"Confirm smoke_plan appears with readOnlyHint true and destructiveHint false.",
				"Do not call API-backed MCP tools without explicit approval and secure credentials.",
			},
		},
	}
}
