// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCH: smoke-plan adds local-only approved live-smoke planning guidance without live execution.
// PATCH: smoke-run-approval-gated adds narrow approval-file-gated setup and customers smoke execution.
// PATCH: smoke-run-approval-gated writes the redacted smoke run response to the approved transcript artifact path.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

type smokeSafety struct {
	GuidanceOnly                        bool   `json:"guidance_only"`
	LocalOnly                           bool   `json:"local_only"`
	MakesAPICalls                       bool   `json:"makes_api_calls"`
	CallsDocsEndpoint                   bool   `json:"calls_docs_endpoint"`
	ExecutesMCP                         bool   `json:"executes_mcp"`
	PostsWebhook                        bool   `json:"posts_webhook"`
	WritesSandbox                       bool   `json:"writes_sandbox"`
	WritesProduction                    bool   `json:"writes_production"`
	RequiresExplicitApproval            bool   `json:"requires_explicit_approval"`
	RequiresSandboxOrApprovedCredential bool   `json:"requires_sandbox_or_approved_credential"`
	RequiresCredentialThroughSecureFlow bool   `json:"requires_credential_through_secure_flow"`
	ReadOnlyIntendedCommandsOnly        bool   `json:"read_only_intended_commands_only"`
	NoWrites                            bool   `json:"no_writes"`
	NoTokenLiterals                     bool   `json:"no_token_literals"`
	NoLiveExecutionInCommand            bool   `json:"no_live_execution_in_command"`
	CredentialGuidance                  string `json:"credential_guidance"`
	ApprovalGuidance                    string `json:"approval_guidance"`
}

type smokeScopePlan struct {
	Name                 string                     `json:"name"`
	Title                string                     `json:"title"`
	Summary              string                     `json:"summary"`
	ApprovalChecklist    []string                   `json:"approval_checklist"`
	DocsQueries          []string                   `json:"docs_queries"`
	CommandSuggestions   []string                   `json:"command_suggestions"`
	MCPGuidance          []string                   `json:"mcp_guidance,omitempty"`
	ApprovalPacketFields *smokeApprovalPacketFields `json:"approval_packet_fields,omitempty"`
	ExpectedEvidence     *smokeExpectedEvidence     `json:"expected_evidence,omitempty"`
	StopCriteria         []string                   `json:"stop_criteria,omitempty"`
	TranscriptGuidance   *smokeTranscriptGuidance   `json:"transcript_guidance,omitempty"`
}

type smokeApprovalPacketFields struct {
	TargetEnvironmentAndBaseURLClassification string   `json:"target_environment_and_base_url_classification,omitempty"`
	CredentialSourceAndSecureSecretFlow       string   `json:"credential_source_and_secure_secret_flow,omitempty"`
	AllowedScopeOrCommands                    []string `json:"allowed_scope_or_commands,omitempty"`
	TranscriptArtifactPath                    string   `json:"transcript_artifact_path,omitempty"`
	ReviewerSignoff                           string   `json:"reviewer_signoff,omitempty"`
}

type smokeExpectedEvidence struct {
	RedactedCommand             string `json:"redacted_command,omitempty"`
	ExitCode                    string `json:"exit_code,omitempty"`
	EndpointOrToolName          string `json:"endpoint_or_tool_name,omitempty"`
	EnvironmentClassification   string `json:"environment_classification,omitempty"`
	ObjectCountOrEmptyListProof string `json:"object_count_or_empty_list_proof,omitempty"`
	NoTokenExposure             string `json:"no_token_exposure,omitempty"`
}

type smokeTranscriptGuidance struct {
	ArtifactPath string `json:"artifact_path,omitempty"`
	Redaction    string `json:"redaction,omitempty"`
	Shareability string `json:"shareability,omitempty"`
}

type smokePlanResponse struct {
	Command               string           `json:"command"`
	Scope                 string           `json:"scope,omitempty"`
	AvailableScopes       []string         `json:"available_scopes,omitempty"`
	ScopePlan             *smokeScopePlan  `json:"scope_plan,omitempty"`
	ScopePlans            []smokeScopePlan `json:"scope_plans,omitempty"`
	Safety                smokeSafety      `json:"safety"`
	RunbookPurpose        string           `json:"runbook_purpose"`
	DocsLookupInstruction string           `json:"docs_lookup_instruction"`
}

type smokeApprovalFile struct {
	Approver                 string `json:"approver"`
	Environment              string `json:"environment"`
	BaseURL                  string `json:"base_url"`
	CredentialSource         string `json:"credential_source"`
	AllowedScope             string `json:"allowed_scope"`
	ReadOnly                 bool   `json:"read_only"`
	TranscriptPath           string `json:"transcript_path"`
	StopCriteriaAcknowledged bool   `json:"stop_criteria_acknowledged"`
}

type smokeRunCheck struct {
	Name        string `json:"name"`
	Passed      bool   `json:"passed"`
	Method      string `json:"method,omitempty"`
	Path        string `json:"path,omitempty"`
	StatusCode  int    `json:"status_code,omitempty"`
	ObjectCount int    `json:"object_count,omitempty"`
	Note        string `json:"note,omitempty"`
}

type smokeRunResponse struct {
	Command          string          `json:"command"`
	Scope            string          `json:"scope"`
	Approved         bool            `json:"approved"`
	ReadOnly         bool            `json:"read_only"`
	Environment      string          `json:"environment"`
	BaseURL          string          `json:"base_url"`
	CredentialSource string          `json:"credential_source"`
	TranscriptPath   string          `json:"transcript_path"`
	Checks           []smokeRunCheck `json:"checks"`
}

func newSmokeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "smoke",
		Short: "Plan approved read-only live smoke checks",
		Long:  "Plan approved read-only smoke checks. Planning is local-only. Running a scope requires an explicit approval file.",
	}
	cmd.AddCommand(newSmokePlanCmd(flags))
	cmd.AddCommand(newSmokeRunCmd(flags))
	return cmd
}

func newSmokePlanCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "plan [scope]",
		Short: "Generate a local-only live-smoke runbook",
		Long: `Generate a local-only runbook for a future approved read-only live smoke.

This command is guidance-only. It does not call Straddle APIs, does not call docs endpoints, does not execute MCP tools, does not post webhooks, and does not touch sandbox or production.`,
		Example: `  straddle-pp-cli smoke plan
  straddle-pp-cli smoke plan all --json
  straddle-pp-cli smoke plan customers --agent`,
		Annotations: map[string]string{
			"mcp:read-only": "true",
		},
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if flags.deliverSpec != "" {
				return usageErr(fmt.Errorf("smoke plan does not support --deliver; use normal stdout, JSON, or agent output"))
			}

			scope := ""
			if len(args) == 1 {
				scope = strings.ToLower(strings.TrimSpace(args[0]))
			}
			payload, err := buildSmokePlanResponse(scope)
			if err != nil {
				return usageErr(err)
			}
			return renderSmokePlanResponse(cmd, flags, payload)
		},
	}
	return cmd
}

func newSmokeRunCmd(flags *rootFlags) *cobra.Command {
	var approvalFile string

	cmd := &cobra.Command{
		Use:   "run <scope>",
		Short: "Run approved read-only smoke checks",
		Long: `Run approved read-only smoke checks from an explicit approval file.

This command refuses to run without --approval-file. The first slice supports setup and customers only. Setup performs local checks only. Customers performs a single GET /v1/customers request against the approved base URL.`,
		Example: `  straddle-pp-cli smoke run setup --approval-file ./approval.json --json
  straddle-pp-cli smoke run customers --approval-file ./approval.json --json`,
		Annotations: map[string]string{
			"mcp:read-only": "true",
		},
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if flags.deliverSpec != "" {
				return usageErr(fmt.Errorf("smoke run does not support --deliver; use normal stdout, JSON, or agent output"))
			}

			scope := strings.ToLower(strings.TrimSpace(args[0]))
			payload, err := buildSmokeRunResponse(cmd, flags, scope, approvalFile)
			if err != nil {
				return err
			}
			return renderSmokeRunResponse(cmd, flags, payload)
		},
	}
	cmd.Flags().StringVar(&approvalFile, "approval-file", "", "Path to the JSON approval file for this read-only smoke run")
	return cmd
}

func buildSmokePlanResponse(scope string) (smokePlanResponse, error) {
	payload := smokePlanResponse{
		Command:         "smoke plan",
		AvailableScopes: smokeScopeNames(),
		Safety: smokeSafety{
			GuidanceOnly:                        true,
			LocalOnly:                           true,
			MakesAPICalls:                       false,
			CallsDocsEndpoint:                   false,
			ExecutesMCP:                         false,
			PostsWebhook:                        false,
			WritesSandbox:                       false,
			WritesProduction:                    false,
			RequiresExplicitApproval:            true,
			RequiresSandboxOrApprovedCredential: true,
			RequiresCredentialThroughSecureFlow: true,
			ReadOnlyIntendedCommandsOnly:        true,
			NoWrites:                            true,
			NoTokenLiterals:                     true,
			NoLiveExecutionInCommand:            true,
			CredentialGuidance:                  "Future live smoke requires a sandbox or approved environment credential supplied through the caller's secure secret flow. Do not paste, log, or pass token literals in argv.",
			ApprovalGuidance:                    "Get explicit approval for the environment, credential scope, and read-only command list before running any live smoke.",
		},
		RunbookPurpose:        "Prepare a future approved read-only smoke run. This command only prints the plan.",
		DocsLookupInstruction: "Review the docs lookup topics manually before live execution to verify current fields, statuses, pagination, and MCP behavior. This command does not perform docs lookup.",
	}
	if scope == "" {
		return payload, nil
	}
	if scope == "all" {
		payload.Scope = scope
		payload.ScopePlans = smokeScopePlans()
		return payload, nil
	}
	plan, ok := smokeScopePlanByName(scope)
	if !ok {
		return payload, fmt.Errorf("invalid smoke scope %q: supported scopes are %s", scope, strings.Join(smokeScopeNames(), ", "))
	}
	payload.Scope = plan.Name
	payload.ScopePlan = &plan
	return payload, nil
}

func renderSmokePlanResponse(cmd *cobra.Command, flags *rootFlags, payload smokePlanResponse) error {
	asJSON := flags.asJSON || flags.agent || !isTerminal(cmd.OutOrStdout())
	if asJSON {
		return printJSONFiltered(cmd.OutOrStdout(), payload, flags)
	}

	w := cmd.OutOrStdout()
	if payload.Scope == "" {
		fmt.Fprintln(w, "Smoke plan")
		fmt.Fprintln(w, "Safety: local guidance only, no API calls, no docs calls, no MCP execution, no sandbox or production access.")
		fmt.Fprintln(w, "Live smoke later requires explicit approval and a sandbox or approved credential through a secure secret flow.")
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Scopes:")
		for _, scope := range payload.AvailableScopes {
			fmt.Fprintf(w, "  %s\n", scope)
		}
		return nil
	}
	if payload.Scope == "all" {
		fmt.Fprintln(w, "Smoke plan: all")
		fmt.Fprintln(w, "Safety: local guidance only. Future live execution requires explicit approval and read-only commands.")
		for _, plan := range payload.ScopePlans {
			fmt.Fprintf(w, "  %s - %s\n", plan.Name, plan.Summary)
		}
		return nil
	}

	plan := payload.ScopePlan
	fmt.Fprintf(w, "Smoke plan: %s\n", plan.Name)
	fmt.Fprintln(w, "Safety: local guidance only. No live execution happens here.")
	if plan.Name == "approval" {
		fmt.Fprintln(w, "Local proof commands:")
	} else {
		fmt.Fprintln(w, "Suggested commands:")
	}
	for _, suggestion := range plan.CommandSuggestions {
		fmt.Fprintf(w, "  %s\n", suggestion)
	}
	if len(plan.MCPGuidance) > 0 {
		fmt.Fprintln(w, "MCP guidance:")
		for _, guidance := range plan.MCPGuidance {
			fmt.Fprintf(w, "  %s\n", guidance)
		}
	}
	if plan.Name == "approval" {
		renderSmokeApprovalPlan(w, plan)
	}
	return nil
}

func buildSmokeRunResponse(cmd *cobra.Command, flags *rootFlags, scope string, approvalPath string) (smokeRunResponse, error) {
	if !smokeRunScopeAllowed(scope) {
		return smokeRunResponse{}, usageErr(fmt.Errorf("invalid smoke run scope %q: supported run scopes are setup, customers", scope))
	}

	approval, err := loadSmokeApprovalFile(approvalPath)
	if err != nil {
		return smokeRunResponse{}, err
	}
	if err := validateSmokeApproval(approval, scope); err != nil {
		return smokeRunResponse{}, err
	}

	payload := smokeRunResponse{
		Command:          "smoke run",
		Scope:            scope,
		Approved:         true,
		ReadOnly:         approval.ReadOnly,
		Environment:      approval.Environment,
		BaseURL:          approval.BaseURL,
		CredentialSource: approval.CredentialSource,
		TranscriptPath:   approval.TranscriptPath,
		Checks: []smokeRunCheck{
			{
				Name:   "approval",
				Passed: true,
				Note:   "approval file validated locally before execution",
			},
		},
	}

	switch scope {
	case "setup":
		if err := writeSmokeRunTranscript(approval.TranscriptPath, payload); err != nil {
			return smokeRunResponse{}, err
		}
		return payload, nil
	case "customers":
		check, err := runSmokeCustomersList(cmd, flags, approval)
		payload.Checks = append(payload.Checks, check)
		if transcriptErr := writeSmokeRunTranscript(approval.TranscriptPath, payload); transcriptErr != nil {
			if err != nil {
				return smokeRunResponse{}, fmt.Errorf("%w; additionally failed to write smoke transcript: %v", err, transcriptErr)
			}
			return smokeRunResponse{}, transcriptErr
		}
		if err != nil {
			return payload, err
		}
		return payload, nil
	default:
		return smokeRunResponse{}, usageErr(fmt.Errorf("invalid smoke run scope %q: supported run scopes are setup, customers", scope))
	}
}

func writeSmokeRunTranscript(path string, payload smokeRunResponse) error {
	trimmed := strings.TrimSpace(path)
	if trimmed == "" {
		return usageErr(fmt.Errorf("smoke transcript path is required"))
	}
	if err := os.MkdirAll(filepath.Dir(trimmed), 0o700); err != nil {
		return fmt.Errorf("create smoke transcript directory for %q: %w", trimmed, err)
	}
	if info, err := os.Stat(trimmed); err == nil {
		if info.IsDir() {
			return usageErr(fmt.Errorf("smoke transcript path %q is a directory", trimmed))
		}
		if err := os.Chmod(trimmed, 0o600); err != nil {
			return fmt.Errorf("set smoke transcript permissions for %q: %w", trimmed, err)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat smoke transcript %q: %w", trimmed, err)
	}

	// PATCH: Persist only the already-redacted smokeRunResponse, not approval file contents, headers, or response bodies.
	file, err := os.OpenFile(trimmed, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return fmt.Errorf("write smoke transcript %q: %w", trimmed, err)
	}
	if err := os.Chmod(trimmed, 0o600); err != nil {
		_ = file.Close()
		return fmt.Errorf("set smoke transcript permissions for %q: %w", trimmed, err)
	}
	encoder := json.NewEncoder(file)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(payload); err != nil {
		_ = file.Close()
		return fmt.Errorf("write smoke transcript %q: %w", trimmed, err)
	}
	if err := file.Close(); err != nil {
		return fmt.Errorf("write smoke transcript %q: %w", trimmed, err)
	}
	return nil
}

func renderSmokeRunResponse(cmd *cobra.Command, flags *rootFlags, payload smokeRunResponse) error {
	asJSON := flags.asJSON || flags.agent || !isTerminal(cmd.OutOrStdout())
	if asJSON {
		return printJSONFiltered(cmd.OutOrStdout(), payload, flags)
	}

	w := cmd.OutOrStdout()
	fmt.Fprintf(w, "Smoke run: %s\n", payload.Scope)
	fmt.Fprintf(w, "Environment: %s\n", payload.Environment)
	fmt.Fprintf(w, "Base URL: %s\n", payload.BaseURL)
	for _, check := range payload.Checks {
		status := "failed"
		if check.Passed {
			status = "passed"
		}
		fmt.Fprintf(w, "  %s: %s\n", check.Name, status)
	}
	return nil
}

func smokeRunScopeAllowed(scope string) bool {
	return scope == "setup" || scope == "customers"
}

func loadSmokeApprovalFile(path string) (smokeApprovalFile, error) {
	if strings.TrimSpace(path) == "" {
		return smokeApprovalFile{}, usageErr(fmt.Errorf("smoke run requires --approval-file"))
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return smokeApprovalFile{}, usageErr(fmt.Errorf("read approval file: %w", err))
	}
	if err := rejectSmokeApprovalTokenLiterals(raw); err != nil {
		return smokeApprovalFile{}, usageErr(err)
	}

	var approval smokeApprovalFile
	if err := json.Unmarshal(raw, &approval); err != nil {
		return smokeApprovalFile{}, usageErr(fmt.Errorf("approval file must be JSON: %w", err))
	}
	return approval, nil
}

func validateSmokeApproval(approval smokeApprovalFile, requestedScope string) error {
	missing := make([]string, 0, 5)
	if strings.TrimSpace(approval.Approver) == "" {
		missing = append(missing, "approver")
	}
	if strings.TrimSpace(approval.Environment) == "" {
		missing = append(missing, "environment")
	}
	if strings.TrimSpace(approval.BaseURL) == "" {
		missing = append(missing, "base_url")
	}
	if strings.TrimSpace(approval.CredentialSource) == "" {
		missing = append(missing, "credential_source")
	}
	if strings.TrimSpace(approval.TranscriptPath) == "" {
		missing = append(missing, "transcript_path")
	}
	if len(missing) > 0 {
		return usageErr(fmt.Errorf("approval file missing required field(s): %s", strings.Join(missing, ", ")))
	}
	if !approval.ReadOnly {
		return usageErr(fmt.Errorf("approval file must set read_only true"))
	}
	if !approval.StopCriteriaAcknowledged {
		return usageErr(fmt.Errorf("approval file must set stop_criteria_acknowledged true"))
	}
	if strings.TrimSpace(approval.AllowedScope) == "" {
		return usageErr(fmt.Errorf("approval file missing required field: allowed_scope"))
	}
	if !strings.EqualFold(strings.TrimSpace(approval.AllowedScope), requestedScope) {
		return usageErr(fmt.Errorf("approval file allowed_scope %q does not match requested scope %q", approval.AllowedScope, requestedScope))
	}
	if err := rejectProductionSmokeBaseURL(approval.BaseURL, approval.Environment); err != nil {
		return usageErr(err)
	}
	return nil
}

func rejectSmokeApprovalTokenLiterals(raw []byte) error {
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		return fmt.Errorf("approval file must be JSON: %w", err)
	}
	if smokeApprovalHasTokenLiteral(value, "") {
		return fmt.Errorf("approval file must not contain token literals or bearer credentials")
	}
	return nil
}

func smokeApprovalHasTokenLiteral(value any, key string) bool {
	switch typed := value.(type) {
	case map[string]any:
		for childKey, childValue := range typed {
			if smokeApprovalHasTokenLiteral(childValue, childKey) {
				return true
			}
		}
	case []any:
		for _, childValue := range typed {
			if smokeApprovalHasTokenLiteral(childValue, key) {
				return true
			}
		}
	case string:
		lowerKey := strings.ToLower(strings.TrimSpace(key))
		if isSmokeSensitiveApprovalKey(lowerKey) && strings.TrimSpace(typed) != "" {
			return true
		}
		return smokeApprovalStringLooksLikeTokenLiteral(typed)
	}
	return false
}

func isSmokeSensitiveApprovalKey(key string) bool {
	switch key {
	case "authorization", "bearer", "api_key", "apikey", "access_token", "refresh_token", "secret", "password", "private_key", "token":
		return true
	default:
		return false
	}
}

func smokeApprovalStringLooksLikeTokenLiteral(value string) bool {
	trimmed := strings.TrimSpace(value)
	lower := strings.ToLower(trimmed)
	if strings.Contains(lower, "bearer ") {
		return true
	}
	if strings.Contains(lower, "straddle_token=") {
		return true
	}
	if strings.Contains(lower, "authorization:") {
		return true
	}
	if strings.Contains(lower, "api_key=") || strings.Contains(lower, "secret=") {
		return true
	}
	return strings.Contains(lower, "sk_live") || strings.Contains(lower, "sk_test")
}

func rejectProductionSmokeBaseURL(baseURL string, environment string) error {
	parsed, err := url.Parse(strings.TrimSpace(baseURL))
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return fmt.Errorf("approval file base_url must be an absolute http or https URL")
	}
	if parsed.Scheme != "http" && parsed.Scheme != "https" {
		return fmt.Errorf("approval file base_url must use http or https")
	}
	if parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return fmt.Errorf("approval file base_url must not include credentials, query parameters, or fragments")
	}

	host := strings.ToLower(parsed.Hostname())
	env := strings.ToLower(strings.TrimSpace(environment))
	if strings.Contains(env, "prod") || strings.Contains(host, "prod") {
		return fmt.Errorf("approval file base_url looks production-like and is not allowed")
	}
	if strings.Contains(host, "straddle.com") && host != "sandbox.straddle.com" {
		return fmt.Errorf("approval file base_url looks production-like and is not allowed")
	}
	return nil
}

func runSmokeCustomersList(cmd *cobra.Command, flags *rootFlags, approval smokeApprovalFile) (smokeRunCheck, error) {
	check := smokeRunCheck{
		Name:   "customers_list",
		Method: http.MethodGet,
		Path:   "/v1/customers",
	}
	target := strings.TrimRight(approval.BaseURL, "/") + check.Path
	req, err := http.NewRequestWithContext(cmd.Context(), http.MethodGet, target, nil)
	if err != nil {
		return check, usageErr(fmt.Errorf("build customers smoke request: %w", err))
	}
	if token := smokeRunEnvToken(approval); token != "" {
		if strings.HasPrefix(strings.ToLower(token), "bearer ") {
			req.Header.Set("Authorization", token)
		} else {
			req.Header.Set("Authorization", "Bearer "+token)
		}
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", "straddle-pp-cli-smoke/v1")

	httpClient := &http.Client{Timeout: flags.timeout}
	resp, err := httpClient.Do(req)
	if err != nil {
		return check, apiErr(fmt.Errorf("customers smoke GET /v1/customers failed: %w", err))
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(io.LimitReader(resp.Body, 1024*1024))
	if err != nil {
		return check, apiErr(fmt.Errorf("read customers smoke response: %w", err))
	}
	check.StatusCode = resp.StatusCode
	check.Passed = resp.StatusCode >= 200 && resp.StatusCode < 300
	check.ObjectCount = smokeObjectCount(body)
	if !check.Passed {
		return check, apiErr(fmt.Errorf("customers smoke GET /v1/customers returned HTTP %d", resp.StatusCode))
	}
	return check, nil
}

func smokeObjectCount(body []byte) int {
	var arr []json.RawMessage
	if err := json.Unmarshal(body, &arr); err == nil {
		return len(arr)
	}

	var obj map[string]json.RawMessage
	if err := json.Unmarshal(body, &obj); err != nil {
		return 0
	}
	for _, key := range []string{"data", "results", "items"} {
		raw, ok := obj[key]
		if !ok {
			continue
		}
		if err := json.Unmarshal(raw, &arr); err == nil {
			return len(arr)
		}
	}
	return 0
}

func smokeRunEnvToken(approval smokeApprovalFile) string {
	if !strings.EqualFold(strings.TrimSpace(approval.CredentialSource), "env:STRADDLE_TOKEN") {
		return ""
	}
	if !smokeBaseURLTrustedForEnvToken(approval.BaseURL) {
		return ""
	}
	return strings.TrimSpace(os.Getenv("STRADDLE_TOKEN"))
}

func smokeBaseURLTrustedForEnvToken(baseURL string) bool {
	parsed, err := url.Parse(strings.TrimSpace(baseURL))
	if err != nil {
		return false
	}
	host := strings.ToLower(parsed.Hostname())
	if host == "sandbox.straddle.com" {
		return parsed.Scheme == "https"
	}
	return host == "localhost" || host == "127.0.0.1" || host == "::1"
}

func renderSmokeApprovalPlan(w io.Writer, plan *smokeScopePlan) {
	if plan.ApprovalPacketFields != nil {
		fields := plan.ApprovalPacketFields
		fmt.Fprintln(w, "Approval packet fields:")
		fmt.Fprintf(w, "  target_environment_and_base_url_classification: %s\n", fields.TargetEnvironmentAndBaseURLClassification)
		fmt.Fprintf(w, "  credential_source_and_secure_secret_flow: %s\n", fields.CredentialSourceAndSecureSecretFlow)
		fmt.Fprintln(w, "  allowed_scope_or_commands:")
		for _, scope := range fields.AllowedScopeOrCommands {
			fmt.Fprintf(w, "    %s\n", scope)
		}
		fmt.Fprintf(w, "  transcript_artifact_path: %s\n", fields.TranscriptArtifactPath)
		fmt.Fprintf(w, "  reviewer_signoff: %s\n", fields.ReviewerSignoff)
	}
	if plan.ExpectedEvidence != nil {
		evidence := plan.ExpectedEvidence
		fmt.Fprintln(w, "Expected evidence:")
		fmt.Fprintf(w, "  redacted_command: %s\n", evidence.RedactedCommand)
		fmt.Fprintf(w, "  exit_code: %s\n", evidence.ExitCode)
		fmt.Fprintf(w, "  endpoint_or_tool_name: %s\n", evidence.EndpointOrToolName)
		fmt.Fprintf(w, "  environment_classification: %s\n", evidence.EnvironmentClassification)
		fmt.Fprintf(w, "  object_count_or_empty_list_proof: %s\n", evidence.ObjectCountOrEmptyListProof)
		fmt.Fprintf(w, "  no_token_exposure: %s\n", evidence.NoTokenExposure)
	}
	if len(plan.StopCriteria) > 0 {
		fmt.Fprintln(w, "Stop criteria:")
		for _, criterion := range plan.StopCriteria {
			fmt.Fprintf(w, "  %s\n", criterion)
		}
	}
	if plan.TranscriptGuidance != nil {
		guidance := plan.TranscriptGuidance
		fmt.Fprintln(w, "Transcript guidance:")
		fmt.Fprintf(w, "  artifact_path: %s\n", guidance.ArtifactPath)
		fmt.Fprintf(w, "  redaction: %s\n", guidance.Redaction)
		fmt.Fprintf(w, "  shareability: %s\n", guidance.Shareability)
	}
}

func smokeScopeNames() []string {
	return []string{"setup", "customers", "payments", "funding", "mcp", "approval", "all"}
}

func smokeScopePlanByName(name string) (smokeScopePlan, bool) {
	for _, plan := range smokeScopePlans() {
		if plan.Name == name {
			return plan, true
		}
	}
	return smokeScopePlan{}, false
}

func smokeScopePlans() []smokeScopePlan {
	return []smokeScopePlan{
		{
			Name:    "setup",
			Title:   "Setup readiness",
			Summary: "Confirm local configuration, environment classification, auth source, and MCP sibling presence before any live read.",
			ApprovalChecklist: []string{
				"Explicit approval names the target environment.",
				"Credential is supplied through a secure secret flow.",
				"No token literal appears in commands, docs, logs, or argv.",
			},
			DocsQueries: []string{
				"authentication environments sandbox production base url",
				"pagination response structure customers charges payouts funding events",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
			},
		},
		{
			Name:    "customers",
			Title:   "Customer read smoke",
			Summary: "Plan read-only customer listing and current docs verification.",
			ApprovalChecklist: []string{
				"Explicit approval allows read-only customer listing.",
				"Credential scope is sandbox or another approved non-production read scope unless approval says otherwise.",
				"Only list or dry-run command shapes are used.",
			},
			DocsQueries: []string{
				"customers list search filters pagination",
				"customer status identity verification status details",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli customers list --dry-run --agent",
			},
		},
		{
			Name:    "payments",
			Title:   "Payment read smoke",
			Summary: "Plan read-only charge and payout list checks without creating or changing payments.",
			ApprovalChecklist: []string{
				"Explicit approval allows read-only charge and payout listing.",
				"Payment writes such as create, update, cancel, hold, release, and resubmit are out of scope.",
				"Dry-run request-shape checks happen before any approved live reads.",
			},
			DocsQueries: []string{
				"charges list filters status pagination",
				"payouts list filters status pagination",
				"payment status lifecycle charge payout",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli payments --dry-run --agent",
			},
		},
		{
			Name:    "funding",
			Title:   "Funding event read smoke",
			Summary: "Plan read-only funding event listing and reconciliation field checks.",
			ApprovalChecklist: []string{
				"Explicit approval allows read-only funding event listing.",
				"Settlement and reconciliation checks do not post webhooks or run write commands.",
				"Dry-run request-shape checks happen before any approved live reads.",
			},
			DocsQueries: []string{
				"funding events list filters reconciliation settlement",
				"funding event status charge payout relationship",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
				"straddle-pp-cli funding-events list --dry-run --agent",
			},
		},
		{
			Name:    "mcp",
			Title:   "MCP tools/list smoke",
			Summary: "Plan a credential-free MCP sibling tools/list check and confirm read-only shell-out metadata.",
			ApprovalChecklist: []string{
				"Explicit approval is required before using MCP tools against live credentials.",
				"Credential-free tools/list smoke is allowed as local process inspection.",
				"No MCP tool is called against Straddle APIs from this planning command.",
			},
			DocsQueries: []string{
				"MCP tools/list read only annotations shell out tools",
				"Straddle MCP setup local stdio tools list",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli setup check --json",
			},
			MCPGuidance: []string{
				"Build the local straddle-pp-mcp sibling from this repo before smoke.",
				"Run a local JSON-RPC initialize plus tools/list smoke against the stdio MCP process.",
				"Confirm smoke_plan appears with readOnlyHint true and destructiveHint false.",
				"Do not call API-backed MCP tools without explicit approval and secure credentials.",
			},
		},
		{
			Name:    "approval",
			Title:   "Live smoke approval packet",
			Summary: "Print the written approval fields required before any future read-only live smoke.",
			ApprovalChecklist: []string{
				"Written approval names the target environment and base URL classification.",
				"Written approval names the credential source and secure secret flow.",
				"Written approval limits execution to read-only scope or commands.",
				"Written approval names the redacted transcript artifact path and reviewer signoff owner.",
			},
			DocsQueries: []string{
				"live smoke approval sandbox environment base url read only",
				"docs search commands source sandbox",
			},
			CommandSuggestions: []string{
				"straddle-pp-cli smoke plan setup --json",
				"straddle-pp-cli smoke plan customers --json",
				"straddle-pp-cli docs search sandbox --source commands --json",
			},
			ApprovalPacketFields: &smokeApprovalPacketFields{
				TargetEnvironmentAndBaseURLClassification: "Name the target environment and classify the resolved base URL before execution. Approved first run should be sandbox or another explicitly approved non-production environment.",
				CredentialSourceAndSecureSecretFlow:       "Name the credential source and how the secret is supplied through a secure flow. Do not paste, log, print, store, or pass token literals in argv.",
				AllowedScopeOrCommands: []string{
					"read-only only",
					"Approved scope, for example setup plus customers, or exact commands named in the approval.",
					"No create, update, delete, cancel, hold, release, resubmit, webhook post, publish, sign, or notarize command.",
				},
				TranscriptArtifactPath: "Provide the planned path for the redacted transcript artifact before live execution.",
				ReviewerSignoff:        "Name the reviewer who will approve the redacted transcript after execution.",
			},
			ExpectedEvidence: &smokeExpectedEvidence{
				RedactedCommand:             "Every executed command is recorded with secrets redacted.",
				ExitCode:                    "Each command records its exit code.",
				EndpointOrToolName:          "Each result names the endpoint or local tool checked.",
				EnvironmentClassification:   "Each result records sandbox, approved non-production, custom, or production classification.",
				ObjectCountOrEmptyListProof: "Each list result includes an object count or clear empty-list proof.",
				NoTokenExposure:             "Transcript review confirms no token, bearer credential, or sensitive value exposure.",
			},
			StopCriteria: []string{
				"Stop if the resolved target is a production URL unexpectedly.",
				"Stop if any write-looking operation appears in the command, docs guidance, output, or prompt.",
				"Stop if any token printed in output or logs.",
				"Stop if any prompt for token literal appears.",
				"Stop if unredacted sensitive data appears beyond approved fixtures.",
				"Stop after 401/403 after one retry.",
				"Stop on any HTTP 5xx response.",
				"Stop if output is not safely shareable.",
			},
			TranscriptGuidance: &smokeTranscriptGuidance{
				ArtifactPath: "Use the approval packet transcript artifact path and keep the raw transcript local until reviewed.",
				Redaction:    "Redact secrets, bearer credentials, account identifiers, personal data, and any value outside approved fixtures.",
				Shareability: "Only the redacted transcript may be attached to review or launch evidence.",
			},
		},
	}
}
