// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// PATCH: smoke-plan covers local-only approved live-smoke planning guidance and safety metadata.
func TestSmokePlanNoArgJSONReturnsScopesAndSafety(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", "--json")
	if err != nil {
		t.Fatalf("smoke plan --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke plan wrote stderr: %q", stderr)
	}

	var got smokePlanResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke plan --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Command != "smoke plan" {
		t.Fatalf("command = %q, want smoke plan", got.Command)
	}
	wantScopes := []string{"setup", "customers", "payments", "funding", "mcp", "all"}
	if strings.Join(got.AvailableScopes, ",") != strings.Join(wantScopes, ",") {
		t.Fatalf("available scopes = %#v, want %#v", got.AvailableScopes, wantScopes)
	}
	if !got.Safety.GuidanceOnly || !got.Safety.LocalOnly || !got.Safety.RequiresExplicitApproval {
		t.Fatalf("smoke plan should be local guidance requiring approval: %#v", got.Safety)
	}
	if !got.Safety.RequiresSandboxOrApprovedCredential || !got.Safety.RequiresCredentialThroughSecureFlow {
		t.Fatalf("smoke plan should require approved credentials through a secure flow: %#v", got.Safety)
	}
	if !got.Safety.ReadOnlyIntendedCommandsOnly || !got.Safety.NoWrites || !got.Safety.NoTokenLiterals || !got.Safety.NoLiveExecutionInCommand {
		t.Fatalf("smoke plan should be read-only guidance without tokens or live execution: %#v", got.Safety)
	}
	if got.Safety.MakesAPICalls || got.Safety.CallsDocsEndpoint || got.Safety.ExecutesMCP || got.Safety.PostsWebhook || got.Safety.WritesSandbox || got.Safety.WritesProduction {
		t.Fatalf("smoke plan should not touch APIs, docs, MCP, webhooks, sandbox, or production: %#v", got.Safety)
	}
}

func TestSmokePlanScopesIncludeExpectedCommands(t *testing.T) {
	tests := map[string][]string{
		"setup": {
			"straddle-pp-cli setup check --json",
		},
		"customers": {
			"straddle-pp-cli setup check --json",
			"straddle-pp-cli customers list --dry-run --agent",
		},
		"payments": {
			"straddle-pp-cli payments --dry-run --agent",
		},
		"funding": {
			"straddle-pp-cli funding-events list --dry-run --agent",
		},
		"mcp": {
			"straddle-pp-cli setup check --json",
		},
	}

	for scope, wantCommands := range tests {
		t.Run(scope, func(t *testing.T) {
			stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", scope, "--json")
			if err != nil {
				t.Fatalf("smoke plan %s --json returned error: %v", scope, err)
			}
			if stderr != "" {
				t.Fatalf("smoke plan %s wrote stderr: %q", scope, stderr)
			}

			var got smokePlanResponse
			if err := json.Unmarshal([]byte(stdout), &got); err != nil {
				t.Fatalf("smoke plan %s --json emitted invalid JSON: %v\n%s", scope, err, stdout)
			}
			if got.Scope != scope || got.ScopePlan == nil {
				t.Fatalf("expected %s scope plan, got %#v", scope, got)
			}
			for _, want := range wantCommands {
				if !containsString(got.ScopePlan.CommandSuggestions, want) {
					t.Fatalf("%s scope commands = %#v, want %q", scope, got.ScopePlan.CommandSuggestions, want)
				}
			}
			if len(got.ScopePlan.DocsQueries) == 0 {
				t.Fatalf("%s scope should include docs lookup topics", scope)
			}
			if strings.Contains(stdout, "STRADDLE_TOKEN=") || strings.Contains(stdout, "Bearer ") {
				t.Fatalf("smoke plan should not emit token literals or bearer examples:\n%s", stdout)
			}
		})
	}
}

func TestSmokePlanCommandSuggestionsResolveToRealCommands(t *testing.T) {
	root := newRootCmd(&rootFlags{})
	for _, plan := range smokeScopePlans() {
		t.Run(plan.Name, func(t *testing.T) {
			for _, suggestion := range plan.CommandSuggestions {
				path := commandPathFromSuggestion(t, suggestion)
				cmd, _, err := root.Find(path)
				if err != nil {
					t.Fatalf("suggestion %q did not resolve: %v", suggestion, err)
				}
				if cmd == nil {
					t.Fatalf("suggestion %q resolved to nil command", suggestion)
				}
				if cmd.Run == nil && cmd.RunE == nil {
					t.Fatalf("suggestion %q resolved to %q without executable behavior", suggestion, cmd.CommandPath())
				}
			}
		})
	}
}

func TestSmokePlanAllIncludesEveryScopePlan(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", "all", "--json")
	if err != nil {
		t.Fatalf("smoke plan all --json returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke plan all wrote stderr: %q", stderr)
	}

	var got smokePlanResponse
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke plan all --json emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.Scope != "all" {
		t.Fatalf("scope = %q, want all", got.Scope)
	}
	if len(got.ScopePlans) != 5 {
		t.Fatalf("all scope should include five concrete scope plans, got %d: %#v", len(got.ScopePlans), got.ScopePlans)
	}
	if got.ScopePlan != nil {
		t.Fatalf("all scope should use scope_plans, not scope_plan: %#v", got.ScopePlan)
	}
}

func TestSmokePlanInvalidScopeReturnsUsageError(t *testing.T) {
	_, _, err := runCLIForDocsTest(t, "smoke", "plan", "not-a-scope", "--json")
	if err == nil {
		t.Fatalf("smoke plan should reject invalid scopes")
	}
	var cliErr *cliError
	if !errors.As(err, &cliErr) || cliErr.code != 2 {
		t.Fatalf("invalid scope should be a usage error, got %#v", err)
	}
	if !strings.Contains(err.Error(), "supported scopes") {
		t.Fatalf("invalid scope error should list supported scopes, got %v", err)
	}
}

func TestSmokePlanAgentUsesTargetEnvelope(t *testing.T) {
	stdout, stderr, err := runCLIForDocsTest(t, "smoke", "plan", "payments", "--agent")
	if err != nil {
		t.Fatalf("smoke plan --agent returned error: %v", err)
	}
	if stderr != "" {
		t.Fatalf("smoke plan --agent wrote stderr: %q", stderr)
	}

	var got struct {
		SchemaVersion string `json:"schema_version"`
		Data          struct {
			Command   string          `json:"command"`
			Scope     string          `json:"scope"`
			ScopePlan *smokeScopePlan `json:"scope_plan"`
			Safety    smokeSafety     `json:"safety"`
		} `json:"data"`
		Warnings []string        `json:"warnings"`
		Results  json.RawMessage `json:"results"`
		Meta     json.RawMessage `json:"meta"`
	}
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("smoke plan --agent emitted invalid JSON: %v\n%s", err, stdout)
	}
	if got.SchemaVersion != "1.0" {
		t.Fatalf("schema_version: want 1.0, got %q", got.SchemaVersion)
	}
	if got.Data.Command != "smoke plan" || got.Data.Scope != "payments" || got.Data.ScopePlan == nil {
		t.Fatalf("agent data should contain payments smoke plan: %#v", got.Data)
	}
	if !got.Data.Safety.GuidanceOnly || got.Data.Safety.MakesAPICalls || got.Data.Safety.ExecutesMCP || !got.Data.Safety.NoLiveExecutionInCommand {
		t.Fatalf("agent safety should remain local guidance only: %#v", got.Data.Safety)
	}
	if got.Warnings == nil {
		t.Fatalf("warnings should be an empty array, not null")
	}
	if got.Results != nil || got.Meta != nil {
		t.Fatalf("target envelope should not include top-level results/meta")
	}
}

func TestSmokePlanRejectsDeliverBeforeDelivery(t *testing.T) {
	target := filepath.Join(t.TempDir(), "smoke-plan-delivery.json")

	oldArgs := os.Args
	t.Cleanup(func() {
		os.Args = oldArgs
	})
	os.Args = []string{
		"straddle-pp-cli",
		"smoke",
		"plan",
		"--deliver",
		"file:" + target,
	}

	err := Execute()
	if err == nil {
		t.Fatalf("smoke plan should reject --deliver")
	}
	if !strings.Contains(err.Error(), "smoke plan does not support --deliver") {
		t.Fatalf("error should explain --deliver is unsupported, got %v", err)
	}
	if _, statErr := os.Stat(target); !os.IsNotExist(statErr) {
		t.Fatalf("smoke plan should reject --deliver before writing output, stat err=%v", statErr)
	}
}

func commandPathFromSuggestion(t *testing.T, suggestion string) []string {
	t.Helper()

	parts := strings.Fields(suggestion)
	if len(parts) == 0 {
		t.Fatalf("empty command suggestion")
	}
	if parts[0] != "straddle-pp-cli" {
		t.Fatalf("suggestion should start with straddle-pp-cli, got %q", suggestion)
	}

	var path []string
	for _, part := range parts[1:] {
		if strings.HasPrefix(part, "--") {
			break
		}
		path = append(path, part)
	}
	if len(path) == 0 {
		t.Fatalf("suggestion should include a command path, got %q", suggestion)
	}
	return path
}
