// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"straddle-pp-cli/internal/client"
)

func unsafeTokenGuidance() []string {
	envAssignment := strings.Join([]string{"export", "STRADDLE_TOKEN"}, " ") + "="
	return []string{
		envAssignment + strings.Join([]string{"<", "your-key", ">"}, ""),
		envAssignment + strings.Join([]string{"<", "your-token", ">"}, ""),
		"straddle-pp-cli auth set-token " + strings.Join([]string{"<", "token", ">"}, ""),
	}
}

func assertSafeTokenGuidance(t *testing.T, text string) {
	t.Helper()

	for _, unsafe := range unsafeTokenGuidance() {
		if strings.Contains(text, unsafe) {
			t.Fatalf("token guidance should not include %q in %q", unsafe, text)
		}
	}
	if !strings.Contains(text, "straddle-pp-cli auth set-token --stdin") {
		t.Fatalf("token guidance should prefer stdin auth setup, got %q", text)
	}
	if !strings.Contains(text, "secret manager") {
		t.Fatalf("token guidance should mention secret manager env injection, got %q", text)
	}
}

func TestDoctorJSONUnauthenticatedAuthHintUsesSafeTokenGuidance(t *testing.T) {
	t.Setenv("STRADDLE_TOKEN", "")
	t.Setenv("STRADDLE_BASE_URL", "")
	configPath := filepath.Join(t.TempDir(), "config.toml")
	if err := os.WriteFile(configPath, []byte("base_url = \"\"\n"), 0o600); err != nil {
		t.Fatalf("write config: %v", err)
	}

	stdout, stderr, err := runCLIForAuthTest(t, "", "doctor", "--json", "--config", configPath)
	if err != nil {
		t.Fatalf("doctor --json returned error: %v\nstderr: %s", err, stderr)
	}

	var report map[string]any
	if err := json.Unmarshal([]byte(stdout), &report); err != nil {
		t.Fatalf("parse doctor JSON: %v\nstdout: %s", err, stdout)
	}
	hint, ok := report["auth_hint"].(string)
	if !ok || hint == "" {
		t.Fatalf("doctor JSON should include auth_hint, got %#v", report["auth_hint"])
	}
	assertSafeTokenGuidance(t, hint)
}

func TestClassifyAPIErrorAuthHintsUseSafeTokenGuidance(t *testing.T) {
	tests := []struct {
		name string
		err  error
	}{
		{
			name: "http 400 auth-shaped error",
			err: &client.APIError{
				Method:     "GET",
				Path:       "/v1/customers",
				StatusCode: 400,
				Body:       `{"error":"missing api_key"}`,
			},
		},
		{
			name: "http 401",
			err: &client.APIError{
				Method:     "GET",
				Path:       "/v1/customers",
				StatusCode: 401,
				Body:       `{"error":"unauthorized"}`,
			},
		},
		{
			name: "http 403",
			err: &client.APIError{
				Method:     "GET",
				Path:       "/v1/customers",
				StatusCode: 403,
				Body:       `{"error":"forbidden"}`,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := classifyAPIError(tt.err, nil)
			if err == nil {
				t.Fatalf("classifyAPIError returned nil")
			}
			assertSafeTokenGuidance(t, err.Error())
		})
	}
}
