// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "account-settings get-settings", Description: "Get all resolved settings for the specified account, including inherited values from organization, platform, and system defaults.", Group: "account-settings"},
	{Command: "accounts create", Description: "Creates a new account associated with your Straddle platform integration. This endpoint allows you to set up an account with specified details, including business information and access levels.", Group: "accounts"},
	{Command: "accounts get", Description: "Retrieves the details of an account that has previously been created. Supply the unique account ID that was returned from your previous request, and Straddle will return the corresponding account information.", Group: "accounts"},
	{Command: "accounts list", Description: "Returns a list of accounts associated with your Straddle platform integration. The accounts are returned sorted by creation date, with the most recently created accounts appearing first. This endpoint supports advanced sorting and filtering options.", Group: "accounts"},
	{Command: "accounts update", Description: "Updates an existing account's information. This endpoint allows you to update various account details during onboarding or after the account has been created.", Group: "accounts"},
	{Command: "accounts capability-requests create", Description: "Submits a request to enable a specific capability for an account. Use this endpoint to request additional features or services for an account.", Group: "accounts"},
	{Command: "accounts capability-requests list", Description: "Retrieves a list of capability requests associated with an account. The requests are returned sorted by creation date, with the most recent requests appearing first. This endpoint supports advanced sorting and filtering options.", Group: "accounts"},
	{Command: "accounts onboard account", Description: "Initiates the onboarding process for a new account. This endpoint can only be used for accounts where at least one representative and one bank account have already been created.", Group: "accounts"},
	{Command: "accounts simulate create", Description: "Simulate the status transitions for sandbox accounts. This endpoint can only be used for sandbox accounts.", Group: "accounts"},
	{Command: "bridge create", Description: "Creates a new paykey using a Quiltt token as the source. This endpoint allows you to create a secure payment token linked to a bank account authenticated through Quiltt.", Group: "bridge"},
	{Command: "bridge create-bank-account-paykey", Description: "Use Bridge to create a new paykey using a bank routing and account number as the source. This endpoint allows you to create a secure payment token linked to a specific bank account.", Group: "bridge"},
	{Command: "bridge create-plaid-paykey", Description: "Use Bridge to create a new paykey using a Plaid token as the source. This endpoint allows you to create a secure payment token linked to a bank account authenticated through Plaid.", Group: "bridge"},
	{Command: "bridge create-speedchex", Description: "Creates a new paykey using a Speedchex token as the source. This endpoint allows you to create a secure payment token linked to a bank account authenticated through Speedchex.", Group: "bridge"},
	{Command: "bridge create-tan", Description: "Create tan", Group: "bridge"},
	{Command: "bridge create-token", Description: "Use this endpoint to generate a session token for use in the Bridge widget.", Group: "bridge"},
	{Command: "charges create", Description: "Use charges to collect money from a customer for the sale of goods or services.", Group: "charges"},
	{Command: "charges get", Description: "Retrieves the details of an existing charge. Supply the unique charge `id`, and Straddle will return the corresponding charge information.", Group: "charges"},
	{Command: "charges update", Description: "Change the values of parameters associated with a charge prior to processing. The status of the charge must be `created`, `scheduled`, or `on_hold`.", Group: "charges"},
	{Command: "charges cancel charge", Description: "Cancel a charge to prevent it from being originated for processing. The status of the charge must be `created`, `scheduled`, or `on_hold`.", Group: "charges"},
	{Command: "charges hold charge", Description: "Place a charge on hold to prevent it from being originated for processing. The status of the charge must be `created` or `scheduled`.", Group: "charges"},
	{Command: "charges release charge", Description: "Release a charge from an `on_hold` status to allow it to be rescheduled for processing.", Group: "charges"},
	{Command: "charges resubmit create", Description: "Resubmit a failed or reversed charge.", Group: "charges"},
	{Command: "charges unmask charges-v1-get", Description: "Get a charge by id.", Group: "charges"},
	{Command: "customers create", Description: "Creates a new customer record and automatically initiates identity, fraud, and risk assessment scores. This endpoint allows you to create a customer profile and associate it with paykeys and payments.", Group: "customers"},
	{Command: "customers delete", Description: "Permanently removes a customer record from Straddle. This action cannot be undone and should only be used to satisfy regulatory requirements or for privacy compliance.", Group: "customers"},
	{Command: "customers get", Description: "Retrieves the details of an existing customer. Supply the unique customer ID that was returned from your 'create customer' request, and Straddle will return the corresponding customer information.", Group: "customers"},
	{Command: "customers list", Description: "Lists or searches customers connected to your account. All supported query parameters are optional. If none are provided, the response will include all customers connected to your account. This endpoint supports advanced sorting and filtering options.", Group: "customers"},
	{Command: "customers update", Description: "Updates an existing customer's information. This endpoint allows you to modify the customer's contact details, PII, and metadata.", Group: "customers"},
	{Command: "customers refresh-review update", Description: "Updates the decision of a customer's identity validation. This endpoint allows you to modify the outcome of a customer decision and is useful for correcting or updating the status of a customer's verification.", Group: "customers"},
	{Command: "customers review get-customer", Description: "Retrieves and analyzes the results of a customer's identity validation and fraud score. This endpoint provides a comprehensive breakdown of the validation outcome, including:\n- Risk and correlation scores\n- Reason codes for the decision\n- Results of watchlist screening\n- Any network alerts detected\nUse this endpoint to gain insights into the verification process and make informed decisions about customer onboarding.", Group: "customers"},
	{Command: "customers review update-customer", Description: "Updates the status of a customer's identity decision. This endpoint allows you to modify the outcome of a customer risk screening and is useful for correcting or updating the status of a customer's verification. Note that this endpoint is only available for customers with a current status of `review`.", Group: "customers"},
	{Command: "customers unmasked get-customer", Description: "Retrieves the unmasked details, including PII, of an existing customer. Supply the unique customer ID that was returned from your 'create customer' request, and Straddle will return the corresponding customer information. This endpoint needs to be enabled by Straddle and should only be used when absolutely necessary.", Group: "customers"},
	{Command: "funding-event-payments get", Description: "All the payments that made up the funding event", Group: "funding-event-payments"},
	{Command: "funding-events create", Description: "Simulate a funding event for testing. This endpoint can only be used in the sandbox environment.", Group: "funding-events"},
	{Command: "funding-events get", Description: "Retrieves the details of an existing funding event. Supply the unique funding event `id`, and Straddle will return the individual transaction items that make up the funding event.", Group: "funding-events"},
	{Command: "funding-events list", Description: "Retrieves a list of funding events for your account. This endpoint supports advanced sorting and filtering options.", Group: "funding-events"},
	{Command: "linked-bank-accounts create", Description: "Creates a new linked bank account associated with a Straddle account. This endpoint allows you to associate external bank accounts with a Straddle account for various payment operations such as payment deposits, payout withdrawals, and more.", Group: "linked-bank-accounts"},
	{Command: "linked-bank-accounts get", Description: "Retrieves the details of a linked bank account that has previously been created. Supply the unique linked bank account `id`, and Straddle will return the corresponding information. The response includes masked account details for security purposes.", Group: "linked-bank-accounts"},
	{Command: "linked-bank-accounts list", Description: "Returns a list of bank accounts associated with a specific Straddle account. The linked bank accounts are returned sorted by creation date, with the most recently created appearing first. This endpoint supports pagination to handle accounts with multiple linked bank accounts.", Group: "linked-bank-accounts"},
	{Command: "linked-bank-accounts update", Description: "Updates an existing linked bank account's information. This can be used to update account details during onboarding or to update metadata associated with the linked account. The linked bank account must be in 'created' or 'onboarding' status.", Group: "linked-bank-accounts"},
	{Command: "linked-bank-accounts cancel update", Description: "Cancels an existing linked bank account. This can be used to cancel a linked bank account before it has been reviewed. The linked bank account must be in 'created' status.", Group: "linked-bank-accounts"},
	{Command: "linked-bank-accounts unmask get-linked-bank-account-unmasked", Description: "Retrieves the unmasked details of a linked bank account that has previously been created. Supply the unique linked bank account `id`, and Straddle will return the corresponding information, including sensitive details. This endpoint needs to be enabled by Straddle for your account and should only be used when absolutely necessary.", Group: "linked-bank-accounts"},
	{Command: "organizations create", Description: "Creates a new organization related to your Straddle integration. Organizations can be used to group related accounts and manage permissions across multiple users.", Group: "organizations"},
	{Command: "organizations get-by-id", Description: "Retrieves the details of an Organization that has previously been created. Supply the unique organization ID that was returned from your previous request, and Straddle will return the corresponding organization information.", Group: "organizations"},
	{Command: "organizations list", Description: "Retrieves a list of organizations associated with your Straddle integration. The organizations are returned sorted by creation date, with the most recently created organizations appearing first. This endpoint supports advanced sorting and filtering options to help you find specific organizations.", Group: "organizations"},
	{Command: "paykeys get", Description: "Retrieves the details of an existing paykey. Supply the unique paykey `id` and Straddle will return the corresponding paykey record , including the `paykey` token value and masked bank account details.", Group: "paykeys"},
	{Command: "paykeys list", Description: "Returns a list of paykeys associated with a Straddle account. This endpoint supports advanced sorting and filtering options.", Group: "paykeys"},
	{Command: "paykeys cancel update", Description: "Update", Group: "paykeys"},
	{Command: "paykeys refresh-balance update", Description: "Updates the balance of a paykey. This endpoint allows you to refresh the balance of a paykey.", Group: "paykeys"},
	{Command: "paykeys refresh-review update", Description: "Updates the decision of a paykey's review validation. This endpoint allows you to refresh the outcome of a paykey's decision and is useful for correcting or updating the status of a paykey's verification.", Group: "paykeys"},
	{Command: "paykeys reveal get", Description: "Retrieves the details of a paykey that has previously been created. Supply the unique paykey ID that was returned from your previous request, and Straddle will return the corresponding paykey information including the unmasked token.", Group: "paykeys"},
	{Command: "paykeys review get", Description: "Get additional details about a paykey.", Group: "paykeys"},
	{Command: "paykeys review update", Description: "Update the status of a paykey when in review status", Group: "paykeys"},
	{Command: "paykeys unblock update", Description: "Unblocks a paykey that was previously blocked due to an R29 return code. Only paykeys blocked with R29 returns that have not been previously unblocked are eligible.", Group: "paykeys"},
	{Command: "paykeys unmasked get-paykey", Description: "Retrieves the unmasked details of an existing paykey. Supply the unique paykey `id` and Straddle will return the corresponding paykey record, including the unmasked bank account details. This endpoint needs to be enabled by Straddle for your account and should only be used when absolutely necessary.", Group: "paykeys"},
	{Command: "payments list", Description: "Search for payments, including `charges` and `payouts`, using a variety of criteria. This endpoint supports advanced sorting and filtering options.", Group: "payments"},
	{Command: "payouts create", Description: "Use payouts to send money to your customers.", Group: "payouts"},
	{Command: "payouts get", Description: "Retrieves the details of an existing payout. Supply the unique payout `id` to retrieve the corresponding payout information.", Group: "payouts"},
	{Command: "payouts update", Description: "Update the details of a payout prior to processing. The status of the payout must be `created`, `scheduled`, or `on_hold`.", Group: "payouts"},
	{Command: "payouts cancel payout", Description: "Cancel a payout to prevent it from being processed. The status of the payout must be `created`, `scheduled`, or `on_hold`.", Group: "payouts"},
	{Command: "payouts hold payout", Description: "Hold a payout to prevent it from being processed. The status of the payout must be `created`, `scheduled`, or `on_hold`.", Group: "payouts"},
	{Command: "payouts release payout", Description: "Release a payout from a `hold` status to allow it to be rescheduled for processing.", Group: "payouts"},
	{Command: "payouts resubmit create", Description: "Resubmit a failed or reversed payout.", Group: "payouts"},
	{Command: "payouts unmask payouts-v1-get", Description: "Get a payout by id.", Group: "payouts"},
	{Command: "reports create", Description: "Create", Group: "reports"},
	{Command: "representatives create", Description: "Creates a new representative associated with an account. Representatives are individuals who have legal authority or significant responsibility within the business.", Group: "representatives"},
	{Command: "representatives get", Description: "Retrieves the details of an existing representative. Supply the unique representative ID, and Straddle will return the corresponding representative information.", Group: "representatives"},
	{Command: "representatives list", Description: "Returns a list of representatives associated with a specific account or organization. The representatives are returned sorted by creation date, with the most recently created representatives appearing first. This endpoint supports advanced sorting and filtering options.", Group: "representatives"},
	{Command: "representatives update", Description: "Updates an existing representative's information. This can be used to update personal details, contact information, or the relationship to the account or organization.", Group: "representatives"},
	{Command: "representatives unmask get", Description: "Retrieves the unmasked details of a representative that has previously been created. Supply the unique representative ID, and Straddle will return the corresponding representative information, including sensitive details. This endpoint requires additional authentication and should be used with caution.", Group: "representatives"},
	{Command: "setup check", Description: "Show local setup preflight status without calling Straddle APIs, docs endpoints, MCP, webhooks, or production.", Group: "setup", WhyItMatters: "Local readiness proof before credentials or live reads."},
	{Command: "docs search", Description: "Search product docs, local command capabilities, or reference-doc guidance.", Group: "docs", WhyItMatters: "Find current docs and local helper commands from one command."},
	{Command: "sandbox guide", Description: "Print local sandbox scenario guidance without calling Straddle APIs, docs endpoints, MCP, webhooks, sandbox, or production.", Group: "sandbox", WhyItMatters: "Prepare sandbox test paths without executing them."},
	// PATCH: completion-audit-discovery keeps ops and monitoring helper commands discoverable through docs command search.
	{Command: "ops guide", Description: "Print local operational guidance for reconciliation, fraud monitoring, collections, reporting, and monitoring without calling APIs or writing production data.", Group: "ops", WhyItMatters: "Give operators safe read-first workflow guidance before live execution."},
	{Command: "workflow plan", Description: "Generate local-only structured plans for reconciliation, fraud monitoring, collections, reporting, and monitoring.", Group: "workflow", WhyItMatters: "Turn operational workflows into safe read-first command plans."},
	{Command: "release plan", Description: "Generate local-only public-release readiness guidance without publishing, external service calls, MCP execution, signing, notarization, or secrets.", Group: "release", WhyItMatters: "Separate local proof from public launch approval."},
	{Command: "credentials plan", Description: "Generate local-only credential storage guidance without reading, writing, or printing secrets.", Group: "credentials", WhyItMatters: "Review credential storage posture without touching secret values."},
	{Command: "mcp config", Description: "Generate local MCP client config fragments without installing, writing files, reading secrets, calling APIs, or executing MCP.", Group: "mcp", WhyItMatters: "Prepare desktop MCP config for review."},
	{Command: "mcp bundle", Description: "Create a local desktop MCP bundle directory with a copied MCP binary, manifest, and reviewable config fragments without installing, reading secrets, executing MCP, publishing, signing, or approving launch.", Group: "mcp", WhyItMatters: "Produce a local bundle artifact agents can inspect."},
	{Command: "benchmark ramp", Description: "Emit a local-only Ramp comparison benchmark for CLI, MCP, docs, agent ergonomics, credential guidance, presentation, workflow coverage, and release gaps.", Group: "benchmark", WhyItMatters: "Prove the Ramp reference is tracked as executable evidence, not disposable planning prose."},
	{Command: "smoke plan", Description: "Generate a local-only live-smoke runbook without API calls, docs calls, MCP execution, sandbox, or production access.", Group: "smoke", WhyItMatters: "Prepare approved read-only smoke checks before execution."},
	{Command: "smoke run", Description: "Run explicitly approved read-only smoke checks, including optional local stdio MCP initialize plus tools/list.", Group: "smoke", WhyItMatters: "Execute narrow approved local or read-only proof after approval."},
	// PATCH: completion-audit-discovery lets monitoring queries resolve to the local tail surface instead of unrelated endpoints.
	{Command: "tail", Description: "Monitor local or approved event streams with agent-friendly output for operational debugging.", Group: "monitoring", WhyItMatters: "Make the monitoring surface discoverable from command search."},
	{Command: "shipcheck local", Description: "Run local public-preview readiness checks without credentials, service calls, publishing, signing, notarization, or production writes.", Group: "shipcheck", WhyItMatters: "Executable local proof for agent and public-preview helper readiness."},
	{Command: "shipcheck public", Description: "Run local preview checks and public-launch approval blockers without publishing, service calls, signing, notarization, or production writes.", Group: "shipcheck", WhyItMatters: "Confirm local proof is done while blocking public launch until approvals are recorded."},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  straddle-pp-cli which "stale tickets"
  straddle-pp-cli which "bottleneck"
  straddle-pp-cli which --limit 1 "send message"
  straddle-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
