// Copyright 2026 straddleio. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"reflect"
	"strings"
	"testing"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

func unsafeTokenGuidance() []string {
	envAssignment := strings.Join([]string{"export", "STRADDLE_TOKEN"}, " ") + "="
	return []string{
		envAssignment + strings.Join([]string{"<", "your-key", ">"}, ""),
		envAssignment + strings.Join([]string{"<", "your-token", ">"}, ""),
		"straddle-pp-cli auth set-token " + strings.Join([]string{"<", "token", ">"}, ""),
	}
}

func assertRuntimeAuthGuidance(t *testing.T, text string) {
	t.Helper()

	for _, unsafe := range unsafeTokenGuidance() {
		if strings.Contains(text, unsafe) {
			t.Fatalf("token guidance should not include %q in %q", unsafe, text)
		}
	}
	if !strings.Contains(text, "straddle-pp-cli setup check --json") {
		t.Fatalf("auth guidance should route to setup check first, got %q", text)
	}
	if !strings.Contains(text, "straddle-pp-cli auth set-token --stdin") {
		t.Fatalf("token guidance should prefer stdin auth setup, got %q", text)
	}
	if !strings.Contains(text, "secret manager") {
		t.Fatalf("token guidance should mention secret manager env injection, got %q", text)
	}
	if !strings.Contains(text, "Optional live sandbox reachability") ||
		!strings.Contains(text, "explicit sandbox base URL and credentials") ||
		!strings.Contains(text, "straddle-pp-cli doctor --json") {
		t.Fatalf("doctor guidance should be optional and sandbox-scoped, got %q", text)
	}
}

func toolResultText(t *testing.T, result *mcplib.CallToolResult) string {
	t.Helper()

	if result == nil {
		t.Fatalf("tool result is nil")
	}
	if len(result.Content) != 1 {
		t.Fatalf("tool result should have one content item, got %d", len(result.Content))
	}
	content, ok := result.Content[0].(mcplib.TextContent)
	if !ok {
		t.Fatalf("tool result content should be text, got %T", result.Content[0])
	}
	return content.Text
}

func TestMakeAPIHandlerAuthErrorsUseSafeTokenGuidance(t *testing.T) {
	tests := []struct {
		name       string
		statusCode int
		body       string
	}{
		{
			name:       "http 400 auth-shaped error",
			statusCode: http.StatusBadRequest,
			body:       `{"error":"missing api_key"}`,
		},
		{
			name:       "http 401",
			statusCode: http.StatusUnauthorized,
			body:       `{"error":"unauthorized"}`,
		},
		{
			name:       "http 403",
			statusCode: http.StatusForbidden,
			body:       `{"error":"forbidden"}`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
				w.WriteHeader(tt.statusCode)
				_, _ = w.Write([]byte(tt.body))
			}))
			t.Cleanup(server.Close)

			t.Setenv("HOME", t.TempDir())
			t.Setenv("STRADDLE_BASE_URL", server.URL)
			t.Setenv("STRADDLE_TOKEN", "test-token")

			handler := makeAPIHandler("GET", "/v1/customers", nil, nil)
			result, err := handler(context.Background(), mcplib.CallToolRequest{})
			if err != nil {
				t.Fatalf("handler returned error: %v", err)
			}
			if !result.IsError {
				t.Fatalf("handler result should be an MCP error")
			}

			assertRuntimeAuthGuidance(t, toolResultText(t, result))
		})
	}
}

// PATCH: mcp-count-breakdown verifies the context tool explains endpoint, typed, and runtime MCP counts separately.
// PATCH: sandbox-guide verifies sandbox_guide is included in runtime shell-out metadata.
// PATCH: setup-check verifies setup_check is included in runtime shell-out metadata.
// PATCH: ops-guide verifies ops_guide is included in runtime shell-out metadata.
func TestHandleContextIncludesMCPCountBreakdown(t *testing.T) {
	result, err := handleContext(context.Background(), mcplib.CallToolRequest{})
	if err != nil {
		t.Fatalf("handleContext returned error: %v", err)
	}

	var got struct {
		EndpointToolCount       int      `json:"endpoint_tool_count"`
		TypedFrameworkToolCount int      `json:"typed_framework_tool_count"`
		TypedToolCount          int      `json:"typed_tool_count"`
		RuntimeToolCount        int      `json:"runtime_tool_count"`
		RuntimeShellOutTools    []string `json:"runtime_shell_out_tools"`
		ToolCount               int      `json:"tool_count"`
		ToolCountMeaning        string   `json:"tool_count_meaning"`
	}
	if err := json.Unmarshal([]byte(toolResultText(t, result)), &got); err != nil {
		t.Fatalf("handleContext should return JSON: %v", err)
	}

	wantShellOutTools := []string{
		"analytics",
		"docs_search",
		"import",
		"ops_guide",
		"sandbox_guide",
		"setup_check",
		"sync",
		"tail",
		"workflow_archive",
		"workflow_status",
	}

	if got.EndpointToolCount != 70 {
		t.Fatalf("endpoint_tool_count = %d, want 70", got.EndpointToolCount)
	}
	if got.TypedFrameworkToolCount != 3 {
		t.Fatalf("typed_framework_tool_count = %d, want 3", got.TypedFrameworkToolCount)
	}
	if got.TypedToolCount != 73 {
		t.Fatalf("typed_tool_count = %d, want 73", got.TypedToolCount)
	}
	if got.RuntimeToolCount != 83 {
		t.Fatalf("runtime_tool_count = %d, want 83", got.RuntimeToolCount)
	}
	if got.ToolCount != got.RuntimeToolCount {
		t.Fatalf("tool_count = %d, want runtime_tool_count %d", got.ToolCount, got.RuntimeToolCount)
	}
	if !reflect.DeepEqual(got.RuntimeShellOutTools, wantShellOutTools) {
		t.Fatalf("runtime_shell_out_tools = %#v, want %#v", got.RuntimeShellOutTools, wantShellOutTools)
	}
	if !strings.Contains(got.ToolCountMeaning, "runtime_tool_count") {
		t.Fatalf("tool_count_meaning should explain runtime count, got %q", got.ToolCountMeaning)
	}
}

// PATCH: sandbox-guide verifies the help-only sandbox guide shell-out is read-only.
// PATCH: setup-check verifies the local setup check shell-out is read-only.
// PATCH: ops-guide verifies the local ops guide shell-out is read-only.
func TestRegisterToolsMarksDocsSearchReadOnly(t *testing.T) {
	mcpServer := server.NewMCPServer("test", "0.0.0")
	RegisterTools(mcpServer)

	tools := mcpServer.ListTools()
	for _, name := range []string{"docs_search", "ops_guide", "sandbox_guide", "setup_check"} {
		tool, ok := tools[name]
		if !ok {
			t.Fatalf("%s MCP tool was not registered; tools = %#v", name, tools)
		}
		if tool.Tool.Annotations.ReadOnlyHint == nil || !*tool.Tool.Annotations.ReadOnlyHint {
			t.Fatalf("%s readOnlyHint = %v, want true", name, tool.Tool.Annotations.ReadOnlyHint)
		}
		if tool.Tool.Annotations.DestructiveHint == nil || *tool.Tool.Annotations.DestructiveHint {
			t.Fatalf("%s destructiveHint = %v, want false", name, tool.Tool.Annotations.DestructiveHint)
		}
	}
}

// TestValidateReadOnlyQuery_AllowsSelectAndWITH pins the contract: the MCP
// sql tool's allowlist accepts SELECT and WITH-prefix queries, including
// CTEs, mixed case, leading whitespace, leading SQL comments, and leading
// statement separators. SELECT-form CTEs ("WITH x AS (SELECT ...) SELECT")
// must work because novel CLI sql commands in the public library accept
// them as legitimate read-only queries; the MCP surface keeps parity.
func TestValidateReadOnlyQuery_AllowsSelectAndWITH(t *testing.T) {
	allowed := []string{
		"SELECT 1",
		"select * from resources",
		"  SELECT 1",
		"\tSELECT 1",
		"\nSELECT 1",
		";SELECT 1",
		"-- comment\nSELECT 1",
		"/* comment */ SELECT 1",
		"/* comment */SELECT 1",
		"/**/SELECT 1",
		"-- one\n-- two\nSELECT 1",
		"/* a *//* b */ SELECT 1",
		"WITH r AS (SELECT 1) SELECT * FROM r",
		"with r as (select 1) select * from r",
	}
	for _, q := range allowed {
		if err := validateReadOnlyQuery(q); err != nil {
			t.Errorf("validateReadOnlyQuery(%q) = %v, want nil", q, err)
		}
	}
}

// TestValidateReadOnlyQuery_RejectsBypassVectors covers the comment-prefix
// bypass class that defeated the earlier prefix-blocklist gate. mode=ro on
// modernc.org/sqlite does not block VACUUM INTO (writes a fresh file) or
// ATTACH DATABASE (opens a separate writable handle), so the gate is the
// only defense against those vectors. A successful bypass at this layer
// would let an MCP-trusting agent silently exfiltrate the local database.
func TestValidateReadOnlyQuery_RejectsBypassVectors(t *testing.T) {
	rejected := []string{
		"VACUUM INTO '/tmp/x.db'",
		"ATTACH DATABASE 'file:/tmp/x.db?mode=rwc' AS evil",
		"INSERT INTO resources VALUES ('x', 'y', '{}')",
		"UPDATE resources SET resource_type = 'evil'",
		"DELETE FROM resources",
		"REPLACE INTO resources VALUES ('seed', 'evil', '{}')",
		"DROP TABLE resources",
		"PRAGMA writable_schema = ON",
		"REINDEX",
		"DETACH DATABASE x",
		"/* x */ VACUUM INTO '/tmp/exfil.db'",
		"/* x */VACUUM INTO '/tmp/exfil.db'",
		"-- x\nVACUUM INTO '/tmp/exfil.db'",
		"/**/VACUUM INTO '/tmp/exfil.db'",
		"/* x */ ATTACH DATABASE 'file:/tmp/x.db?mode=rwc' AS evil",
		"-- x\nATTACH DATABASE '/tmp/x.db' AS evil",
		";VACUUM INTO '/tmp/x.db'",
		"; ; VACUUM INTO '/tmp/x.db'",
		"/* a */ /* b */ INSERT INTO t VALUES (1)",
		"/* outer /* not nested */ */ SELECT 1", // SQLite doesn't nest, so trailing "*/" closes; second SELECT remains. Reject, the gate must err on the side of caution when the leading shape is suspicious.
		"-- only a comment",
		"/* only a comment */",
		"",
		"   ",
		";",
	}
	for _, q := range rejected {
		if err := validateReadOnlyQuery(q); err == nil {
			t.Errorf("validateReadOnlyQuery(%q) = nil, want error", q)
		}
	}
}

// TestStripLeadingSQLNoise checks the helper directly so a regression in the
// stripping logic (off-by-one on /* */ length, missing newline handling on
// --) surfaces close to the source rather than only via the integration
// behavior of validateReadOnlyQuery.
func TestStripLeadingSQLNoise(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"SELECT 1", "SELECT 1"},
		{"  SELECT 1", "SELECT 1"},
		{"\t\nSELECT 1", "SELECT 1"},
		{";SELECT 1", "SELECT 1"},
		{";; ;SELECT 1", "SELECT 1"},
		{"-- x\nSELECT 1", "SELECT 1"},
		{"-- x\n-- y\nSELECT 1", "SELECT 1"},
		{"/* x */SELECT 1", "SELECT 1"},
		{"/**/SELECT 1", "SELECT 1"},
		{"/* x */ /* y */ SELECT 1", "SELECT 1"},
		{"-- only", ""},
		{"/* only", ""},
		{"", ""},
	}
	for _, c := range cases {
		got := stripLeadingSQLNoise(c.in)
		if !strings.EqualFold(got, c.want) {
			t.Errorf("stripLeadingSQLNoise(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}
